### ISSUE TITLE
2D graphic BUG in game FF Fates

### ISSUE THREAD

**Issue by rizky895** [weihuoya/citra#104]
![Screenshot_20200617-204805](https://user-images.githubusercontent.com/67057838/84901054-83940b80-b0dd-11ea-886a-3f9324c0c185.png)

There is graphic bug and fps drop in private quarter when you meet your girl.

**Comment by stizzo1** [comment]
It would be a good thing to add:

- The full name of the game

- The device in use

- The SoC

- Possibly a log

Otherwise it is wasted breath for you and unnecessary information for the developer.

**Comment by GENROGAMER** [comment]
is ashamed in the fucking face and buys a better fucking cell phone

Em qua, 17 de jun de 2020 13:44, stizzo1 <notifications@github.com>
escreveu:
