### ISSUE TITLE
Can you fix the graphics and can you make the joystick circle, not square

### ISSUE THREAD

**Issue by GGbert123** [weihuoya/citra#109]
Everything is working great! But I'm just asking if you can fix the graphics instead of switching to separable shader and can you make the joystick something like circle one, not square... Best wishes

**Comment by stizzo1** [comment]
I think it is currently impossible.

Reason: each manufacturer customizes its drivers and each gpu is in its architecture, different from the others.

In addition, they do not release their driver sources.

The second cache exists for this.

**Comment by GGbert123** [comment]
But how did official one have correct graphics while mmj doesn't with no changes in terms of speed?

**Comment by stizzo1** [comment]
> But how did official one have correct graphics while mmj doesn't with no changes in terms of speed?

What you say is incorrect.

The official has the same problems.

The difference is that with the additional cache those problems are partially mitigated.

**Comment by GGbert123** [comment]
Oh thanks
