### ISSUE TITLE
Navigation bar does not disappear

### ISSUE THREAD

**Issue by ChrisM20** [weihuoya/citra#120]
With the change of the menu in the game the navigation bar does not disappear since before there was a menu and it was hidden but now it is not, although it can be changed in phone settings but I do not have it in use although even so I do not know if it would disappear 
![Screenshot_20200711_070759_org citra emu](https://user-images.githubusercontent.com/60308449/87223826-cd22ef80-c345-11ea-8250-abf180d96c46.jpg)

**Comment by stizzo1** [comment]
It is not a bug / issue.

It is specially created to conform to the new sub-menu.

Full screen and swip version:

![Screenshot_2020-07-11-17-10-50-997_org citra emu](https://user-images.githubusercontent.com/43874809/87227334-9925e980-c39a-11ea-9a51-5ef9147dd203.jpg)

Full screen version and screen buttons:
![Screenshot_2020-07-11-17-12-27-785_org citra emu](https://user-images.githubusercontent.com/43874809/87227395-f326af00-c39a-11ea-845b-90fecfc4dc15.jpg)

In this case, the keys are grouped and moved automatically.

In my version of Android, I don't have the setting to hide the keys but to disable them for the different applications.

For me it is an excellent solution, even if I don't use it. (I use full screen swipes, first screen)

If you have the chance, try the settings of the Android build you mount.

**Comment by Deivmsr** [comment]
There is still a problem. On my Galaxy Note 9, the navigation bar is not automatically retracted after exiting the in-game menu.
