### ISSUE TITLE
Pokemon Glitch

### ISSUE THREAD

**Issue by Azoh99** [weihuoya/citra#125]

**Comment by Azoh99** [comment]
Game glitches when going through tunnels. Once I enter a tunnel, the game turns white and it becomes difficult to navigate your way through it. Can you fix that issue ASAP plz.

**Comment by Bobonicles** [comment]
I think that is in Pokemon Omega Ruby? Try changing the shader type to separate shader because that worked for me.

**Comment by Azoh99** [comment]
> Thank you very much, I couldn't have done it without you as I am able to progress with my gameplay.

**Comment by shabbirmahmud** [comment]
If ur prblm solved close the issue
