### ISSUE TITLE
Pokemon cheat 60fps bug?

### ISSUE THREAD

**Issue by gastonfer123** [weihuoya/citra#128]
When I use the cheat of having 60 FPS in any pokemon game it works very well, but the image stays frozen showing 0 FPS, in the game I can move, the music is heard and the rest but with the image frozen, when I release the button everything is fixed but returns to 15 FPS.
Any solution for this?

**Comment by aecarvalho** [comment]
Release which button?
60 FPS works for me but I don't like using it because speed increases unnecessarily.
