### ISSUE TITLE
Sorry I know this is based on Citra MMJ but I need help with official Citra emulator as I enter the app and start playing the video game, at first it works perfectly but the moment it gets to the game, it completely freezes and force stop itself. Can plz someone tell me how to make it work as I really want to play with official Citra enulator.

### ISSUE THREAD

**Issue by Azoh99** [weihuoya/citra#132]

**Comment by Lemoncak3** [comment]
Have you check if your phone specs can run citra emulator since it's need a strong processor and also decent ram and android version too. On low phone it will be too heavy...

**Comment by Azoh99** [comment]
The specs of the smartphone meets almost all the requirements of the emulator, one it has Android 8, two it needs a bear minimum of 3GB of ram which it does have and but I heard you need Snapdragon 835 processor for it to run totally smooth. But I have seen phones with Snapdragon 625, and even phones with Snapdragon 660 which has near identical processor power be able to play the gameplay properly. So I had a conclusion that the processor isn't optimised enough to run the game.

**Comment by GENROGAMER** [comment]
and complicated to help without knowing your device, right, friend, don't
give me a device from the cave

Em dom, 19 de jul de 2020 10:20, Azoh99 <notifications@github.com> escreveu:

**Comment by Azoh99** [comment]
Okay the name of the device that I am using is the Sony Xperia XZ with 3GB of ram and a Snapdragon 820 processor

**Comment by GENROGAMER** [comment]
2020 and you still with a snapdragon 820 buy an 835 at least there friend

Em sex, 24 de jul de 2020 02:46, Azoh99 <notifications@github.com> escreveu:

**Comment by Azoh99** [comment]
I see friend, so my phone isn't powerful enough for Citra. I knew it was that way and that's why after hearing this I am saving to get myself a Snapdragon 730G, 765G, 855 + or even a Kirin 990 or a MediaTek Dimesionsity 1020 + for official Citra as those processor are more then powerful enough to handle gameplay.

**Comment by Lemoncak3** [comment]
But with that device it should run the game even though without full speed. Maybe it wasn't compatible?

**Comment by Azoh99** [comment]
It might be possible but as Mr gernogamer said, I think it's time I brought myself a newer and more powerful phone in order to play Citra games

**Comment by aecarvalho** [comment]
Would be great to have the issue closed if you feel it's resolved, there may be other issues more specific to the Zhang Wei build which might get overlooked by the developer because of closed issues which are still kept open.
