### ISSUE TITLE
Here's another project for you

### ISSUE THREAD

**Issue by Destroyer5150** [weihuoya/citra#133]
You may like to try porting this 
https://github.com/dhewm/dhewm3
Since Doom 3 ROE is not available for Android

**Comment by stizzo1** [comment]
I think it is not necessary:

https://github.com/glKarin/com.n0n3m4.diii4a

**Comment by Destroyer5150** [comment]
diii4a was cancelled and never supported mods or RoE

**Comment by GENROGAMER** [comment]
Add API vulkan on citra sabe stage

Em sex, 24 de jul de 2020 02:34, Destroyer5150 <notifications@github.com>
escreveu:
