### ISSUE TITLE
Error:12 Problem On Redmi Note 5 Plus

### ISSUE THREAD

**Issue by shabbirmahmud** [weihuoya/citra#137]
![Screenshot_2020-07-29-22-26-05-390_org citra emu](https://user-images.githubusercontent.com/47573399/88827090-5150f000-d1eb-11ea-8d34-ae3df6da32ac.jpg)
#75 
                                       Code:
`*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'xiaomi/vince/vince:8.1.0/OPM1.171019.019/V11.0.2.0.OEGMIXM:user/release-keys'
Revision: '0'
ABI: 'arm64'
pid: 13005, tid: 13005, name: org.citra.emu  >>> org.citra.emu <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xb0
Cause: null pointer dereference
    x0   0000000000000000  x1   0000007fec31ae84  x2   0000000000000000  x3   0000000000000000
    x4   00000000198ace9c  x5   00000077847ccd50  x6   0000000000000013  x7   0000000000000000
    x8   0000007771758000  x9   039d7750b5a6789f  x10  0000000000430000  x11  0000000000000000
    x12  0000007fec31a938  x13  0000000000000000  x14  002ac86297c1c0f4  x15  000059db2214c21d
    x16  0000007fec31ae70  x17  000000781525c658  x18  0000000000000008  x19  0000007794414c00
    x20  0000007770f8c8f8  x21  0000000012d41468  x22  0000000019887d08  x23  000000007479f588
    x24  00000ac23642e4c4  x25  0000000070b7f9a8  x26  00000000198ace48  x27  0000000070cc0da8
    x28  0000000070d5a408  x29  0000007fec31ae60  x30  0000007779f170b4
    sp   0000007fec31ae50  pc   0000007770f89670  pstate 0000000060000000

backtrace:
    #00 pc 0000000000130670  /data/app/org.citra.emu-QsGmw995-O8WCvh0xdbHEw==/base.apk (offset 0x89000)
    #01 pc 00000000000080b0  /data/app/org.citra.emu-QsGmw995-O8WCvh0xdbHEw==/oat/arm64/base.odex (offset 0x8000)
`

**Comment by Wiizzyy25** [comment]
Are your 3ds roms decrypted??

**Comment by shabbirmahmud** [comment]
> Are your 3ds roms decrypted??

Yes

**Comment by stizzo1** [comment]
Enable; Use Virtual SD

**Comment by shabbirmahmud** [comment]
> Enable; Use Virtual SD
Enabled,But didn't work

**Comment by shabbirmahmud** [comment]
> Enable; Use Virtual SD

Enabled,But didn't work

**Comment by shabbirmahmud** [comment]
Problem Solved
