### ISSUE TITLE
Huawei P20 pro

### ISSUE THREAD

**Issue by Abbassyyy** [weihuoya/citra#16]
I'm having trouble using the emulator on this phone. It's super laggy, even a game like super Mario maker. 

Is there any way of speeding this up so I can get 60 FPS.

**Comment by ygyuuffut** [comment]
Similar issue here, some of the 3D game cant even reach 30 fps on Snapdragon 855

**Comment by Lixi-ON** [comment]
There are some cheats if you search in Internet.
I've tried these cheats in my phone,also a Huawei P20 Pro and I dont know why the cheats dont work in my phone
I have tried another the same cheats in another rom of the same game and I cant make the cheats work
