### ISSUE TITLE
Yo-kai watch lens

### ISSUE THREAD

**Issue by ansh122619** [weihuoya/citra#160]
Guys the citra 89204de4b have a new problem. Yokai watch lens are have error at ×2 so I can't see the YoKai while in Citra mmj the problem continues. It is solving by changing to ×1 resolution. It has some issues in ×2.

**Comment by Ansh-citra** [comment]
Guys in citra , this problem started too so lowering the resolution helps. Resolution ×2 caused issue in both citra and citra mmj . Also there are graphical issue in yokai's which can be corrected by lowering the resolution. 

But I request to update citra mmj so it works on ×2 resolution or someone wants third app version of citra. I am ready to be a part of it . 

Please if you have any doubt or trouble which I can solve , I would be happy to help.

Thanks.

**Comment by Ansh-citra** [comment]
I am closing it but have any issue which I can help. I am ready to reopen it.

Mail me for any help - sanjivnikki@gmail.com 
Send me #reopen#github

**Comment by Ansh-citra** [comment]
I again got problem , it started again. I am reopening the issue so please help me.
