### ISSUE TITLE
'Etrian Odyssey' series: Graphic Issues

### ISSUE THREAD

**Issue by CR573S9c6p** [weihuoya/citra#163]
There are graphic issues shown in images below.
1) Top Screen becomes difficult to see when an ally or foe gets blind. (paralysis or asleep also make little hard to see)
2) The font is blurred on the top screen depending on the scene.

These issues exist at least in  EO IV, EO Untold and EO 2 Untold.

Normal condition
![sq2rScreenshot_20201012-103622163](https://user-images.githubusercontent.com/65772953/95701786-7949de80-0c85-11eb-91aa-bbf78f5479ae.png)

Blind
![sq2rScreenshot_20201012-104052063](https://user-images.githubusercontent.com/65772953/95702069-3f2d0c80-0c86-11eb-9c73-996c895039a1.png)

Blurry font (top screen)
![sq2rScreenshot_20201012-114917493](https://user-images.githubusercontent.com/65772953/95702180-992dd200-0c86-11eb-8a65-1092f394ea5d.png)

bottom
![Screenshot_20201012-114936058](https://user-images.githubusercontent.com/65772953/95702268-cc706100-0c86-11eb-8c5f-ff9ae90ef573.png)

**Comment by CR573S9c6p** [comment]
Etrian Odyssey V is more hard to play
Canary 1323 https://youtu.be/7oHy6G4udLQ

![sq2rScreenshot_20201026-150956106](https://user-images.githubusercontent.com/65772953/97235840-1c265f00-1827-11eb-886b-0ba5f4bc081d.png)
![Screenshot_20201026-150345346](https://user-images.githubusercontent.com/65772953/97235847-1f214f80-1827-11eb-96a7-f7007dc8d147.png)
![sq2rScreenshot_20201026-151927480](https://user-images.githubusercontent.com/65772953/97236131-c69e8200-1827-11eb-9775-107cbd8b6925.png)
![Screenshot_20201026-151908588](https://user-images.githubusercontent.com/65772953/97236144-c9997280-1827-11eb-8fd1-669edb60b7a7.png)
![Screenshot_20201027-073228430](https://user-images.githubusercontent.com/65772953/97236192-e9309b00-1827-11eb-883a-4a130302de81.png)
![Screenshot_20201026-150730057](https://user-images.githubusercontent.com/65772953/97236203-efbf1280-1827-11eb-98a7-17f8dab0e409.png)

**Comment by CR573S9c6p** [comment]
The issues may have been fixed.
Thank you for your great work!

**Comment by KarlMikhael** [comment]
can i ask how it was fixed i have the same issues with EOV. after i got to 2nd stratum the grpahic suddenly got broken
![Uploading 440930541_1125850412040005_3925846180947020011_n.jpg…]()
