### ISSUE TITLE
Text bug 

### ISSUE THREAD

**Issue by strixyy** [weihuoya/citra#166]
For some strange reason I get this bug when playing only pokemon x and y 
Everything else runs fine but without text I litterly cant play the game 
![20201016_040700_rmscr](https://user-images.githubusercontent.com/72973302/96245997-9fb19780-0f6d-11eb-8c01-967c5cbaf87b.jpg)

I'm using the latest version and my android is 7.0

**Comment by Pokemetti** [comment]
Mmh, what hardware and what settings are you using?
