### ISSUE TITLE
Can you optimize Citra for kirin chipsets? I have 980 kirin and thats equivalent to snapdragon 845 but citra very lag. 

### ISSUE THREAD

**Issue by KyroKen06** [weihuoya/citra#172]

**Comment by aecarvalho** [comment]
I think it's the issue with the GPU, the CPU on Kirin maybe fantastic but Mali GPUs are no good especially for 3D graphics compared to Snapdragon ones, you can even check the equivalent speed by checking the Speed Test G video here where even Snapdragon 835 beats Kirin 980 at 3D graphics
https://youtu.be/2rhAh6MPS8s
