### ISSUE TITLE
So far  citra can't really run on any chipset besides sd chipsets i know developers already doing their best but will it optimize the another chipsets or it close end :(?

### ISSUE THREAD

**Issue by endmy74** [weihuoya/citra#177]

**Comment by Balachandarsmr** [comment]
According to developer **Mediatek, Exynos and Kirin chips are affected because of the Mali GPUs used in them, Mali GPUs are not good at handling 3D graphics, you can check the relative speeds to Snapdragon by watching Speed Test G videos which very accurately show the large performance gap especially in the GPU performance area.
The Mali gpu is problem;

Shading Units Adreno 96 | Shanding Units Mali 32
-- | -- | --
Adreno 273 Gigaflops | Mali 54.6 Gigaflops

Its impossible to optimize for Mali gpu.**

**Comment by proganime1200** [comment]
Mali gpus are weaker than adreno so mediatek is the problem

**Comment by Rozkiwia11** [comment]
> According to developer **Mediatek, Exynos and Kirin chips are affected because of the Mali GPUs used in them, Mali GPUs are not good at handling 3D graphics, you can check the relative speeds to Snapdragon by watching Speed Test G videos which very accurately show the large performance gap especially in the GPU performance area.
> The Mali gpu is problem;
> 
> Shading Units Adreno 96 | Shanding Units Mali 32
> -- | -- | --
> Adreno 273 Gigaflops | Mali 54.6 Gigaflops
> 
> Its impossible to optimize for Mali gpu.**

But Dolphin Emulator Can Work Well in mediatek.
Hope Developer Can Make Citra Emulator Work In Mediatek Devices

**Comment by proganime1200** [comment]
> > According to developer **Mediatek, Exynos and Kirin chips are affected because of the Mali GPUs used in them, Mali GPUs are not good at handling 3D graphics, you can check the relative speeds to Snapdragon by watching Speed Test G videos which very accurately show the large performance gap especially in the GPU performance area.
> > The Mali gpu is problem;
> > Shading Units Adreno 96 | Shanding Units Mali 32
> > -- | -- | --
> > Adreno 273 Gigaflops | Mali 54.6 Gigaflops
> > Its impossible to optimize for Mali gpu.**
> 
> But Dolphin Emulator Can Work Well in mediatek.
> Hope Developer Can Make Citra Emulator Work In Mediatek Devices

Dont compare this any emulator as citra is different from dolphin even low sd can run dolphin emulator base on my experience

**Comment by Balachandarsmr** [comment]
This Citra run Pokemon ultra moon @ 27 to 30 fps on my Snapdragon 660. Other Pokemon games at 30 fps. But playstore version of citra didn't even run Pokemon X.

**Comment by Rozkiwia11** [comment]
> > According to developer **Mediatek, Exynos and Kirin chips are affected because of the Mali GPUs used in them, Mali GPUs are not good at handling 3D graphics, you can check the relative speeds to Snapdragon by watching Speed Test G videos which very accurately show the large performance gap especially in the GPU performance area.
> > The Mali gpu is problem;
> > Shading Units Adreno 96 | Shanding Units Mali 32
> > -- | -- | --
> > Adreno 273 Gigaflops | Mali 54.6 Gigaflops
> > Its impossible to optimize for Mali gpu.**
> 
> But Dolphin Emulator Can Work Well in mediatek.
> Hope Developer Can Make Citra Emulator Work In Mediatek Devices



> Mali gpus are weaker than adreno so mediatek is the problem

But Is there any hope Citra Can Work With Mediatek Devices?.

**Comment by aecarvalho** [comment]
> > > According to developer **Mediatek, Exynos and Kirin chips are affected because of the Mali GPUs used in them, Mali GPUs are not good at handling 3D graphics, you can check the relative speeds to Snapdragon by watching Speed Test G videos which very accurately show the large performance gap especially in the GPU performance area.
> > > The Mali gpu is problem;
> > > Shading Units Adreno 96 | Shanding Units Mali 32
> > > -- | -- | --
> > > Adreno 273 Gigaflops | Mali 54.6 Gigaflops
> > > Its impossible to optimize for Mali gpu.**
> > 
> > 
> > But Dolphin Emulator Can Work Well in mediatek.
> > Hope Developer Can Make Citra Emulator Work In Mediatek Devices
> 
> > Mali gpus are weaker than adreno so mediatek is the problem
> 
> But Is there any hope Citra Can Work With Mediatek Devices?.
> I Know Developer Work Hard For This Emulator But, Is There Any Chance.
> Poor People With Cheap Devices Use Mediatek, So Poor People Like Me Also Want Happy.

I think you're not getting the point here, the developer can only code the app, not code miracles that will suddenly make your phone work faster.
Consider it this way, a regular car can only go 150-200 km/h while a sports car can go 300+ km/h. You simply cannot tweak or modify the systems in the regular car to get that amount of speed, the engine matters.

**Comment by Rozkiwia11** [comment]
No, I Mean Is It Possible Someday Citra will be Optimize For Mediatek Devices

**Comment by Rozkiwia11** [comment]
> > > > According to developer **Mediatek, Exynos and Kirin chips are affected because of the Mali GPUs used in them, Mali GPUs are not good at handling 3D graphics, you can check the relative speeds to Snapdragon by watching Speed Test G videos which very accurately show the large performance gap especially in the GPU performance area.
> > > > The Mali gpu is problem;
> > > > Shading Units Adreno 96 | Shanding Units Mali 32
> > > > -- | -- | --
> > > > Adreno 273 Gigaflops | Mali 54.6 Gigaflops
> > > > Its impossible to optimize for Mali gpu.**
> > > 
> > > 
> > > But Dolphin Emulator Can Work Well in mediatek.
> > > Hope Developer Can Make Citra Emulator Work In Mediatek Devices
> > 
> > 
> > > Mali gpus are weaker than adreno so mediatek is the problem
> > 
> > 
> > But Is there any hope Citra Can Work With Mediatek Devices?.
> > I Know Developer Work Hard For This Emulator But, Is There Any Chance.
> > Poor People With Cheap Devices Use Mediatek, So Poor People Like Me Also Want Happy.
> 
> I think you're not getting the point here, the developer can only code the app, not code miracles that will suddenly make your phone work faster.
> Consider it this way, a regular car can only go 150-200 km/h while a sports car can go 300+ km/h. You simply cannot tweak or modify the systems in the regular car to get that amount of speed, the engine matters.

No, I Mean Is It Possible Someday Citra will be Optimize For Mediatek Devices.

**Comment by aecarvalho** [comment]
It can be optimised to an extent but it won't give you more than 15-20 FPS for anything less than Mali G70 series. 
Also **It is very important to note that this Citra is only available for ARMV8 64-bit devices, check AIDA64 app because it was not supported on my Snapdragon 439 phone which is only ARMV7v**
![Screenshot_2020-12-06-16-31-27-795_com finalwire aida64](https://user-images.githubusercontent.com/60945000/101278353-bd1e1780-37e0-11eb-8720-e349d8a386c1.jpg)

Best to buy Snapdragon variants like Vivo U10

**Comment by faroukabd000** [comment]
Citra mmj is already slow in sd 665
But faster in official citra
Am a don't know why! !!!
Sd 4xx is weak to play on it

**Comment by aecarvalho** [comment]
> Citra mmj is already slow in sd 665
> But faster in official citra
> Am a don't know why! !!!
> Sd 4xx is weak to play on it

Yes but more importantly, both Citra don't work with ARMv7, only ARMv8
