### ISSUE TITLE
Front End Support

### ISSUE THREAD

**Issue by kyutzienickz** [weihuoya/citra#183]
Citra MMJ.

For some reason I can't get Citra to launch a game directly from DIG even if I use the right Activity used to launch a game. 
Using the "org.citra.emu.ui.MainActivity" launches the app but not the selected rom so I tried to use the emulation activity "org.citra.emu.ui.EmulationActivity" but it gives an error when I do so. Hopefully there's a workaround with this or if it's not supported at the time being I hope you'll add this feature. Thank You!

**Comment by Pokemetti** [comment]
I don't know much about android activities, but wouldn't you have to somehow tell the activity which game to load/which path the game you want to play is at?

**Comment by Pokemetti** [comment]
Duplicate of #167
