### ISSUE TITLE
How is this any different from citra-emu/citra-android?

### ISSUE THREAD

**Issue by rekshflake** [weihuoya/citra#186]
How is this any different from [citra-emu/citra-android](https://github.com/citra-emu/citra-android/releases)?

I see that this repo is about 300 commits behind, yet it has releases newer than citra-emu/citra-android?

**Comment by proganime1200** [comment]
Citra android is official release app but the developer rarely focused while the citra mmj are unofficial port with many tweaks added that are not seen on official

**Comment by aecarvalho** [comment]
> How is this any different from [citra-emu/citra-android](https://github.com/citra-emu/citra-android/releases)?
> 
> I see that this repo is about 300 commits behind, yet it has releases newer than citra-emu/citra-android?

Why is this issue still open even after it has been replied to?
The developer won't be taking everything from that commit because the parent tree from which this build is forked, if you haven't noticed is actually built for the PC and this is the ARM build sourced from it.

**Comment by stizzo1** [comment]
@rekshflake,

My point of view is as follows:

I don't give a shit about commits, I don't give a shit about how many people are behind it, I don't give a shit about differences.

What I do care about, is the result.

The developer of this Fork is a Lone Wolf, a rare Beast in these times, where everybody copies everybody, where everybody thinks to be a developer as soon as they get out of bed in the morning, where everybody thinks to be "efficient" only by being in a group.

And I love Lone Wolves, because I am one too.

Honor to those who believe in themselves, Honor to those who move forward, Honor to those who share their experiences for the good of all.

This is the Spirit of a Samurai and a Warrior.

And now, you can close this fucking "issue".

**Comment by rekshflake** [comment]
> Citra android is official release app but the developer rarely focused while the citra mmj are unofficial port with many tweaks added that are not seen on official

Can you clarify what those tweaks are?

**Comment by rekshflake** [comment]
> > How is this any different from [citra-emu/citra-android](https://github.com/citra-emu/citra-android/releases)?
> > I see that this repo is about 300 commits behind, yet it has releases newer than citra-emu/citra-android?
> 
> Why is this issue still open even after it has been replied to?
> The developer won't be taking everything from that commit because the parent tree from which this build is forked, if you haven't noticed is actually built for the PC and this is the ARM build sourced from it.

So the developer of the MMJ version is nitpicking what is suitable for ARM only from the upstream commits and adding on them?

**Comment by rekshflake** [comment]
> @rekshflake ,
> 
> My point of view is as follows:
> 
> I don't give a shit about commits, I don't give a shit about how many people are behind it, I don't give a shit about differences.
> 
> What I do care about, is the result.
> 
> The developer of this Fork is a Lone Wolf, a rare Beast in these times, where everybody copies everybody, where everybody thinks to be a developer as soon as they get out of bed in the morning, where everybody thinks to be "efficient" only by being in a group.
> 
> And I love Lone Wolves, because I am one too.
> 
> Honor to those who believe in themselves, Honor to those who move forward, Honor to those who share their experiences for the good of all.
> 
> This is the Spirit of a Samurai and a Warrior.
> 
> And now, you can close this fucking "issue".

Chill out Mr. Triggered Lone Wolf...

I didn't close this issue because I still didn't get the answer I wanted to hear.

Users expect to know what this version brings over the official version, and why there are two versions in the first place. That's some "how to treat your users with respect 101" for you...

**Comment by Pokemetti** [comment]
One thing that Citra MMJ offers is netplay. Official version is also kinda dead? They haven't updated anything in quite some time.

**Comment by aecarvalho** [comment]
> > > How is this any different from [citra-emu/citra-android](https://github.com/citra-emu/citra-android/releases)?
> > > I see that this repo is about 300 commits behind, yet it has releases newer than citra-emu/citra-android?
> > 
> > 
> > Why is this issue still open even after it has been replied to?
> > The developer won't be taking everything from that commit because the parent tree from which this build is forked, if you haven't noticed is actually built for the PC and this is the ARM build sourced from it.
> 
> So the developer of the MMJ version is nitpicking what is suitable for ARM only from the upstream commits and adding on them?

Yes exactly, stop asking what all the changes are if you're just someone gaming because as @stizzo1 said, the end result is all that counts for you.
Alternatively if you're a developer, you can always read up each of the differences maintained here:
https://github.com/citra-emu/citra/compare/master...weihuoya:master

Nobody is entitled to answers if you raise them as an FAQ for emulator specific issue duh, I personally respect every good issue raised here but this isn't an issue, this is just your being lazy and skipping the aforementioned comparison list.

**Comment by rekshflake** [comment]
> > > > How is this any different from [citra-emu/citra-android](https://github.com/citra-emu/citra-android/releases)?
> > > > I see that this repo is about 300 commits behind, yet it has releases newer than citra-emu/citra-android?
> > > 
> > > 
> > > Why is this issue still open even after it has been replied to?
> > > The developer won't be taking everything from that commit because the parent tree from which this build is forked, if you haven't noticed is actually built for the PC and this is the ARM build sourced from it.
> > 
> > 
> > So the developer of the MMJ version is nitpicking what is suitable for ARM only from the upstream commits and adding on them?
> 
> Yes exactly, stop asking what all the changes are if you're just someone gaming because as @stizzo1 said, the end result is all that counts for you.
> Alternatively if you're a developer, you can always read up each of the differences maintained here:
> [citra-emu/citra@master...weihuoya:master](https://github.com/citra-emu/citra/compare/master...weihuoya:master)
> 
> Nobody is entitled to answers if you raise them as an FAQ for emulator specific issue duh, I personally respect every good issue raised here but this isn't an issue, this is just your being lazy and skipping the aforementioned comparison list.

Who are you to tell me what I do Mr. I know everything?

Talk about lazy when you're the ones who can't even modify the `README.md` file and list the comparisons in a line or two (if any).

I'm closing this because I'm done talking to idiots who think they're big shots.

**Comment by aecarvalho** [comment]
> Who are you to tell me what I do Mr. I know everything?
> 

I'm only pointing out what you shouldn't be doing, that's raising questions as issues for one.

> Talk about lazy when you're the ones who can't even modify the `README.md` file and list the comparisons in a line or two (if any).
> 

If you've read the comparison of branches [here](https://github.com/citra-emu/citra/compare/master...weihuoya:master) then you already know it's not a one liner or two liner difference. Also I already replied to it saying this is an ARMv8 version modified from the x86 version. I hope that one line comparison is adequate for you, Mr. Lazy and Entitled guy.

**Comment by rekshflake** [comment]
Reopening this until you lazy asses know how to publish a comparisons section let alone a proper one.

**Comment by stizzo1** [comment]
> Reopening this until you lazy asses know how to publish a comparisons section let alone a proper one.

We're not lazy asses like you, Mr. Know-Nothing.

We at least have the decency to read from a fucking source.

The Read.me you stupidly mentioned, is nothing else than what you read on every github channel that proposes the emulator.

And it's a sign of respect to the Official Team.

The rest, you can find in the source.

If the idiocy has not taken over your logic.

This is the last time I will answer to an arrogant asshole.

Now you can safely close it and fuck off.
