### ISSUE TITLE
Pokemon Ultra Sun Cia file not working on snapdragon 665

### ISSUE THREAD

**Issue by shabbirmahmud** [weihuoya/citra#191]
https://user-images.githubusercontent.com/47573399/103155341-2930e180-47c9-11eb-833c-2b795d7341fe.mp4

**Comment by tukashi** [comment]
Qual a versão do seu citra?

**Comment by shabbirmahmud** [comment]
> Qual a versão do seu citra?

The latest realease of citra mmj

**Comment by aecarvalho** [comment]
>  Record_2020-12-26-22-22-00_53c01e3b6443161a8deff0f1f7f140ba.mp4

It's possible that the CIA file might be corrupt or still encrypted, I hope you followed the proper instructions to dump the CIA file to your device, follow the instructions below:
https://citra-emu.org/wiki/dumping-updates-and-dlcs/

**Comment by shabbirmahmud** [comment]
> > Record_2020-12-26-22-22-00_53c01e3b6443161a8deff0f1f7f140ba.mp4
> 
> It's possible that the CIA file might be corrupt or still encrypted, I hope you followed the proper instructions to dump the CIA file to your device, follow the instructions below:
> https://citra-emu.org/wiki/dumping-updates-and-dlcs/

Sorry I am noob dumping cia file whatever.I downloaded the rom and cia from this website-
https://www.pokemoner.com/2017/11/pokemon-ultra-sun-for-citra.html
I don't know the cia is encrypted or decrypted..

**Comment by aecarvalho** [comment]
> Sorry I am noob dumping cia file whatever.I downloaded the rom and cia from this website-
> https://www.pokemoner.com/2017/11/pokemon-ultra-sun-for-citra.html
> I don't know the cia is encrypted or decrypted..

Well, that's illegal... 🤦🏻‍♂️😂
Use the decrypted CIA and test it, definitely not a valid issue because you're not supposed to pirate games 😅
Also, I'm on v1.2 for Ultra Sun and v1.4 for Omega Ruby so I can guarantee it's either a corrupt or encrypted CIA.

**Comment by shabbirmahmud** [comment]
> > Sorry I am noob dumping cia file whatever.I downloaded the rom and cia from this website-
> > https://www.pokemoner.com/2017/11/pokemon-ultra-sun-for-citra.html
> > I don't know the cia is encrypted or decrypted..
> 
> Well, that's illegal... 🤦🏻‍♂️😂
> Use the decrypted CIA and test it, definitely not a valid issue because you're not supposed to pirate games 😅
> Also, I'm on v1.2 for Ultra Sun and v1.4 for Omega Ruby so I can guarantee it's either a corrupt or encrypted CIA.
Who cares about pirate or not😁😁.I almost searched the whole internet.What cia file i get all has the same problem.Btw pokemon ultra moon,pokemon x y,pokemon omega ruby alpha sapphire,sun ,moon all game cia file works.Only ultra sun cia file not working.But when i install any cia file i see a major fps drop.Why is that??And can u please give me ultra sun cia file link of yours plz pretty plz🥺🥺🥺

**Comment by shabbirmahmud** [comment]
> > Sorry I am noob dumping cia file whatever.I downloaded the rom and cia from this website-
> > https://www.pokemoner.com/2017/11/pokemon-ultra-sun-for-citra.html
> > I don't know the cia is encrypted or decrypted..
> 
> Well, that's illegal... 🤦🏻‍♂️😂
> Use the decrypted CIA and test it, definitely not a valid issue because you're not supposed to pirate games 😅
> Also, I'm on v1.2 for Ultra Sun and v1.4 for Omega Ruby so I can guarantee it's either a corrupt or encrypted CIA.

Bro when i install pokemon sun and ultra moon cia file i barely get 10-12 fps.Without cia i get 45-50 fps.Why this that.Is it a issu of emulator or my cia files are bad??

**Comment by shabbirmahmud** [comment]
> > > Sorry I am noob dumping cia file whatever.I downloaded the rom and cia from this website-
> > > https://www.pokemoner.com/2017/11/pokemon-ultra-sun-for-citra.html
> > > I don't know the cia is encrypted or decrypted..
> > 
> > 
> > Well, that's illegal... 🤦🏻‍♂️😂
> > Use the decrypted CIA and test it, definitely not a valid issue because you're not supposed to pirate games 😅
> > Also, I'm on v1.2 for Ultra Sun and v1.4 for Omega Ruby so I can guarantee it's either a corrupt or encrypted CIA.
> 
> Who cares about pirated or not😁😁.I almost searched the whole internet.What cia file i get all has the same problem.
Btw pokemon ultra moon,pokemon x y,pokemon omega ruby alpha sapphire,sun ,moon all game cia file works.Only ultra sun cia file not working.But when i install any cia file i see a major fps drop.Why is that??
And can u please give me yours ultra sun cia file link?? plz pretty plz🥺🥺🥺

**Comment by aecarvalho** [comment]
> Who cares about pirated or not😁😁.I almost searched the whole internet.What cia file i get all has the same problem.

I care about piracy, there's a good chance that Nintendo can sue pirate copies being published, just like there are DMCA policies for pirated movies or music

> And can u please give me yours ultra sun cia file link?? plz pretty plz🥺🥺🥺

I guess I already answered that...

> Bro when i install pokemon sun and ultra moon cia file i barely get 10-12 fps.Without cia i get 45-50 fps.Why this that.Is it a issu of emulator or my cia files are bad??

CIA files fix bugs and add features absent in the original (v1.0) of the games, so since there's more compilation of code to process after each update, games do get slower, it's not emulator specific

**Comment by shabbirmahmud** [comment]
Cia files fix bugs and add features are absent in original rom u say.Isn't nintendo implemented it in every game??Or some games are missing this feature.

**Comment by shabbirmahmud** [comment]
> CIA files fix bugs and add features absent in the original (v1.0) of the games, so since there's more compilation of code to process after each update, games do get slower, it's not emulator specific

Cia files fix bugs and add features are absent in original rom u say.Isn't nintendo implemented it in every game??Or some games are missing this feature.

**Comment by faroukabd000** [comment]
The installation work normally it you phone problem not mmj

**Comment by Tappy-tech** [comment]
> Bro when i install pokemon sun and ultra moon cia file i barely get 10-12 fps.Without cia i get 45-50 fps.Why this that.Is it a issu of emulator or my cia files are bad??
It's because you're using no outline patch. No outline patch supports v1.0.

**Comment by shabbirmahmud** [comment]
> > It's because you're using no outline patch. No outline patch supports v1.0

So i have to use outline patch to solve this issu??

**Comment by shabbirmahmud** [comment]
> The installation work normally it you phone problem not mmj

Now the cia file is working great but fps droped.I don't know.Looks like miracle.🙄🙄

**Comment by Tappy-tech** [comment]
> > Who cares about pirated or not😁😁.I almost searched the whole internet.What cia file i get all has the same problem.
> 
> I care about piracy, there's a good chance that Nintendo can sue pirate copies being published, just like there are DMCA policies for pirated movies or music
> 
> > And can u please give me yours ultra sun cia file link?? plz pretty plz🥺🥺🥺
> 
> I guess I already answered that...
> 
> > Bro when i install pokemon sun and ultra moon cia file i barely get 10-12 fps.Without cia i get 45-50 fps.Why this that.Is it a issu of emulator or my cia files are bad??
> 
> CIA files fix bugs and add features absent in the original (v1.0) of the games, so since there's more compilation of code to process after each update, games do get slower, it's not emulator specific

It's because have installed no outlines patch. No outlines patch supports v1.0. If no outline patch supported v1.2, there would be no issue like that. It's at the same time not and it's emulator issue (Performance and No outline patch version support)
