### ISSUE TITLE
Cancella tutte le impostazione salvate nell'apertura di citra con Android 11 

### ISSUE THREAD

**Issue by Lorenzoc97** [weihuoya/citra#194]
Ogni volta che entro si cancella tutto ,aggiornato alla versione Android 11 snapdragon 855

**Comment by stizzo1** [comment]
> Ogni volta che entro si cancella tutto ,aggiornato alla versione Android 11 snapdragon 855

Ciao Lorenzoc97,

cosa vuoi dire con le impostazioni che non si salvano?

Se intendi le impostazioni dei giochi, no, non esistono file.ini in cui poter salvare le diverse impostazioni e per i diversi giochi.

Per ogni gioco, devi impostare manulamente gli Shaders e la risoluzione, insieme ai vari altri hack.

Gli Shaders li devi obbligatoriamente impostare prima di ogni inizio di partita.

Per quanto riguarda gli altri settaggi, puoi agire anche in game.

**Comment by Lorenzoc97** [comment]
Non hai capito appena entro in citra faccio i settaggi poi esco da citra poi rientro e non vedo i giochi e i settaggi che ho fatto sembra che mi cancella i dati di continuo e me lo fa con Android 11

**Comment by stizzo1** [comment]
> Non hai capito appena entro in citra faccio i settaggi poi esco da citra poi rientro e non vedo i giochi e i settaggi che ho fatto sembra che mi cancella i dati di continuo e me lo fa con Android 11

Questo tipo di evento, in genere lo si ha quando nella fase di primo avvio dell' applicativo, il sistema Android richiede i permessi della app specifica.

Mi pare di capire, che è come se fosse che la tua specifica versione di Android "dimentica" i permessi dati all' applicazione, causando così il problema.

Il permesso specifico è quello della scrittura su usb esterna, che poi è anche la root del tuo sistema.

Se hai eventiali antivirus, prova a disabilitarli momentaneamente (oppure introducendo l' eccezione all' applicativo specifico), se hai il GooglePlay Protect attivo, prova disabilitando momentaneamente anche lui.

Se hai qualche altro applicativo di sistema che logga e protegge la root (file e cartelle, etc.), fai la stessa cosa.

Dal mio canto, ho Android 10 e il problema non lo ho.

**Comment by Lorenzoc97** [comment]
Quando avevo Android 10 qualche giorno fa non avevo questo problema solo appena aggiornato ad Android 11 fa cosi forse c'è qualche incompatibilità

**Comment by stizzo1** [comment]
È sempre consigliabile un HardReset alle impostazioni di fabbrica, ogni qualvolta si effettua un upgrade del sistema operative.

Se non lo hai ancora fatto, te lo consiglio (fai backup dei file e dei dati dei programmi e giochi che hai sulla root, prima).

La casa dovrebbe avere tutti i tool ufficiali. (o al massimo, fai backup solo dei file della sola root/obb/musica e video)

Oppure ancora, se hai backup su server cloud google, non dovrebbero esserci particolari problemi.

Fammi sapere.

**Comment by Lorenzoc97** [comment]
Ho fatto stamattina dati di fabbrica e infatti mi ha risolto il problema e tutto apposto ora grazie per la disponibilità
