### ISSUE TITLE
Save states

### ISSUE THREAD

**Issue by SiddhantShukla02** [weihuoya/citra#199]
Is the save state option not available or am i missing something. Also , while the limiter is set to 100% , the game still beats it and goes to 110 or so on. Like fast forwarding.

This build is running better than the official citra one. Tested Fire Emblem Awakening , and while on official citra the battle animations were crappy , in this they are pretty smooth.

**Comment by aecarvalho** [comment]
Copy of issue #188

**Comment by SiddhantShukla02** [comment]
Oh yeah thanks. And the limiter thing?

**Comment by aecarvalho** [comment]
> Oh yeah thanks. And the limiter thing?

Yep that's a valid issue though with the latest build, speed doesn't go beyond 102% if speed limit percent has been kept at 100% for me.

But for that you need to close this issue and reference speed limit problem as title in a new one as your title here reflects the copy of issue #188

**Comment by SiddhantShukla02** [comment]
Thanks a lot for the heads up.
