### ISSUE TITLE
New resolution option (Enhancement)

### ISSUE THREAD

**Issue by Luwaee** [weihuoya/citra#201]
Is it possible to implement 0.5x resolution? Probably it would decrease the usage and boost the performance in some devices, more snapdragon compatibility (+Maybe even performance boost on mali gpus like it did on 20210107, in fact on Helio G90t it hits 30 fps now unlike other builds.)

**Comment by Pokemetti** [comment]
Interesting idea, but it would really look terrible as the reaolution of the 3ds already is way too low in my opinion. But, nevertheless, probably worth implementing.

**Comment by GlitzHere** [comment]
Prob like a slider for like 0.9 res and 1.1 etc.

**Comment by Andrew-afk** [comment]
I think that can be possible via scaling, but as post-processing.
Decreasing the resolution of emulation will break a lot of games

**Comment by Adityabyahut** [comment]
> Interesting idea, but it would really look terrible as the reaolution of the 3ds already is way too low in my opinion. But, nevertheless, probably worth implementing.

I love gaming (pokemon games) at 300% - 500% speed even at 10fps and bad graphics, hope it is possible on 3ds like ds and gba
