### ISSUE TITLE
Pokemon X on Latest Version of Citra MMJ

### ISSUE THREAD

**Issue by DennyJod** [weihuoya/citra#209]
![Screenshot_2021-01-29-21-14-41-08_53c01e3b6443161a8deff0f1f7f140ba](https://user-images.githubusercontent.com/78195251/106296031-28331a00-6277-11eb-8711-aac3960377d0.jpg)
![Screenshot_2021-01-29-21-15-00-67_53c01e3b6443161a8deff0f1f7f140ba](https://user-images.githubusercontent.com/78195251/106296037-29fcdd80-6277-11eb-9e4b-b4703bf6d89b.jpg)
![Screenshot_2021-01-29-21-15-10-61_53c01e3b6443161a8deff0f1f7f140ba](https://user-images.githubusercontent.com/78195251/106296039-2a957400-6277-11eb-91d3-de92f88f2236.jpg)

![Screenshot_2021-01-29-21-10-40-67_53c01e3b6443161a8deff0f1f7f140ba](https://user-images.githubusercontent.com/78195251/106295684-c377bf80-6276-11eb-9117-030ece2ad95e.jpg)

**Comment by DennyJod** [comment]
This is regarding new update of citra mmj:-
Any Snapdragon users? Did fps drop for u guys?
Earlier with accurate multiplication on I got 15 and accurate information off I got 30. After updating I get 20 fps regardless accurate multiplication on or off...funny thing is if I switch back to old build I still get 20 fps in both cases of accurate multiplication. Did adreno downgrade to upgrade Mali? I use Snapdragon 720g adreno 618 and play Pokemon X

**Comment by DennyJod** [comment]
Average fps remains 20 regardless of accurate multiplication on or off, earlier I got 30 when accurate multiplication was off, but after latest Mali GPU update it remains 20 in any case. But if I switch back to second last build I still get 20 fps in both cases, I don't know what changed post updating?

**Comment by ajay9634** [comment]
In mali ,g70 , now pockemon x running 30fps

**Comment by DennyJod** [comment]
> In mali ,g70 , now pockemon x running 30fps

Ikr I have seen lot of screenshots, for some reason Mali>Adreno now, I wanted to know if all Snapdragon users facing this problem or not?

**Comment by shabbirmahmud** [comment]
> > In mali ,g70 , now pockemon x running 30fps
> 
> Ikr I have seen lot of screenshots, for some reason Mali>Adreno now, I wanted to know if all Snapdragon users facing this problem or not?

I am using snapdragon 665.I get average 20 fps on pokemon x in latest update and the previous updates also with Accurate multiplication off.It was always running the same fps.I don't see in any major changes.

**Comment by ajay9634** [comment]
This is update for mali ,maybe not for Snapdragon.

Doveloper should make two different app for mali and Snapdragon.

**Comment by DennyJod** [comment]
Yes right now I feel like of I wanna get as good fps as Mali I need sd 845 xD, coz now 720g has been nerfed.

**Comment by Pokemetti** [comment]
Qualcomm can update GPU drivers via Play Store, so probably an update on their side if the app version doesn't affect it. Also, I don't think there should be two separate apps for Mali and Adreno, the latest update just FIXED a thing with Mali and didn't make Adreno worse.

**Comment by DennyJod** [comment]
Latest update either made my Pokemon X worse or maybe it just became more buggy. When will mid end Snapdragon processors be optimised if it performs well for Mali. I have adreno 618 and sd 720g
