### ISSUE TITLE
Please Fix Bug Display Graphic That Several Part Being Cut on Tales of The Abyss

### ISSUE THREAD

**Issue by mzaldiadithya** [weihuoya/citra#216]
![Screenshot_20210202-152919421](https://user-images.githubusercontent.com/35521275/106575206-ba674680-6533-11eb-9015-8fbb95fc6be5.jpg)
![Screenshot_20210202-152913007](https://user-images.githubusercontent.com/35521275/106575216-bc310a00-6533-11eb-9ac7-b7a22dc31864.jpg)

Hello Kind Mr/Mrs/Team Weihuoya, i want to report and ask, that can you please fix Display Graphic Issue / Bug that appear on Tales of The Abyss which is some part of the screen / display being cut, Actually it has been long time since this Issue/Bug happend, but i just recently tried to play this game again and thought that the bug has been fixed, but it's not, so please to fix it for any update in the future 🙏

Thank you very much Kind Mr/Mrs/Team Weihuoya.

Latest Build Used :
#Citra_MMJ_20210202

#TalesOfTheAbyss_Bug_Issues

**Comment by bobathor** [comment]
The latest build cuts some of the screen off for some reason; here are images of DQM. Notice the touch screen is only partially displaying for some reason.
