### ISSUE TITLE
Worse performance than before snapdragon 665,for example: before smash run excelent,but with lastest updates,the performance is lousy.

### ISSUE THREAD

**Issue by ELID1825** [weihuoya/citra#217]

**Comment by Neil-24** [comment]
I don't know what's with Snapdragon but Mediatek got huge boost. So I'm grateful for that

**Comment by bobathor** [comment]
I'm getting better performance

**Comment by DennyJod** [comment]
My thoughts exactly, Snapdragon became worse or atleast no change from what I can see... Pls boost lower end Snapdragon too I have 720g

**Comment by DennyJod** [comment]
See #209
