### ISSUE TITLE
Error 12.

### ISSUE THREAD

**Issue by Leomar625** [weihuoya/citra#218]
I have an issue with Super Smash Bros. In previous version, the game was going very well, but now it does not open directly and emu crash..
Here is the log:

https://del.dog/gygrapamab

I hope Citra team look that issue and work in it!!

**Comment by DennyJod** [comment]
Which processor?

**Comment by Leomar625** [comment]
> Which processor?
SnapDragon 636, previously the game run on 45-50fps, not too bad... but now I have "error12", and other games like New Super Mario Bros 2 run worse than before removing "texture load hack".

**Comment by shabbirmahmud** [comment]
> > SnapDragon 636, previously the game run on 45-50fps, not too bad... but now I have "error12", and other games like New Super Mario Bros 2 run worse than before removing "texture load hack".

Something is wrong with your rom.
