### ISSUE TITLE
Attack on Titan Humanity on Chains graphical error

### ISSUE THREAD

**Issue by GenoCyde07** [weihuoya/citra#22]
Game Link: https://www.ziperto.com/attack-on-titan-humanity-in-chains-decrypted/?amp&__cf_chl_jschl_tk__=d168979a71136a504502235e77ad3315ed8e1dc9-1586473736-0-AUcFkjAICjtoh4wqpdFA0VUz4d-Bb4vkp9i-Hcp9cQWRFD64pko_cCee7b8yFz7Ao31ZFCz2ZoOTHmT4srXfs6Ofv3lO4atADebk9BVTkIyEYmvTPzFcjRXmdiZ3H2OscBJp5I_z5CY5ao5dS2lJKchcHXmQJkCNRO5D76SMB_VgYtJvo-eFf6W4zLo-AgNuJKn6UVySfcr1t71O_gvwFaGavD1CNxx9WhFxlmmh9v9HP_cbIDwktm3K4DEv7jKBFj5ysTo0867TX1z7SJekeFFaUmxFn7OeCsFhJ173rAcxTgXne19rY7tGCSj1KKk60jrEksiTl92zwkvAiwXN3rw

**Comment by SFZeroEXE** [comment]
Same problem here
