### ISSUE TITLE
Bad performance Snapdragon 720g Adreno 618 

### ISSUE THREAD

**Issue by DennyJod** [weihuoya/citra#220]
![Screenshot_2021-02-04-19-39-37-18_53c01e3b6443161a8deff0f1f7f140ba](https://user-images.githubusercontent.com/78195251/106904967-cca6d780-6721-11eb-86f1-f5cd1fa2098b.jpg)
 Getting Bad FPS in Citra mmj, when citra mmj is working 30fps in Pokemon X for almost all mid to high end Mali GPU and Helio G70 or higher processors but getting 15-20 on sd 720g adreno 618. If it can be so optimised for Mali pls optimise it for adreno too. I get 30+ fps on official so I know it is possible. Please optimise for Sd720g adreno 618.
![Screenshot_2021-02-04-19-43-15-11_d4f2be808e8ee95dffc2e61a2b7efef4](https://user-images.githubusercontent.com/78195251/106904973-ce709b00-6721-11eb-9a52-27349805b855.jpg)

These Files Show my performance in Mmj and official respectively, at same settings no config.

**Comment by DennyJod** [comment]
Literally 2018 phones with Kirin 710 and a Mali GPU are running 30+ fps but the Snapdragon chipset getting 15 :/

**Comment by DennyJod** [comment]
[citra_log.txt](https://github.com/weihuoya/citra/files/5930729/citra_log.txt)
Log File

**Comment by shabbirmahmud** [comment]
I am using snapdragon 665 realme 5i.I get average 20-25 fps on pokemon x in latest update.It was always running the same fps.I didn't see any major changes.But with this fps the game is not palyable and too laggy in grassy places.And the game diagonals not working properly.The water type pokemon is not showing their real color.They are all white.Above all pokemon x,y is not playable in this soc right now.I hope the devoloper will fix pokemon x related issu.

**Comment by DennyJod** [comment]
> I am using snapdragon 665 realme 5i.I get average 20-25 fps on pokemon x in latest update.It was always running the same fps.I didn't see any major changes.But with this fps the game is not palyable and too laggy in grassy places.And the game diagonals not working properly.The water type pokemon is not showing their real color.They are all white.Above all pokemon x,y is not playable in this soc right now.I hope the devoloper will fix pokemon x related issu.

Use accurate multiplication at accurate settings, white Pokemon glitch fixed. Btw I am now playing on pc build because android build has too many problems.

**Comment by shabbirmahmud** [comment]
>Btw I am now playing on pc build because android build has too many problems.

Yes i think pokemon x is still not playable in midrange snapdragon socs.

**Comment by DennyJod** [comment]
> > Btw I am now playing on pc build because android build has too many problems.
> 
> Yes i think pokemon x is still not playable in midrange snapdragon socs.

Yes unplayable still.

**Comment by Tappy-tech** [comment]
You can actually run this game at full speed with resolution hack. Link:https://youtu.be/VJC4PhFovwI

**Comment by DennyJod** [comment]
> You can actually run this game at full speed with resolution hack. Link:https://youtu.be/VJC4PhFovwI

Unfortunately I have tried this before and just right now, doesn't work on latest build. Do you have the link of the build you are using? Idk why it works for a lot of others for me neither the black screen comes nor it is at 4x reso, when I open it stays at what it was!!

**Comment by shabbirmahmud** [comment]
> You can actually run this game at full speed with resolution hack. Link:https://youtu.be/VJC4PhFovwI

I tried it just now the game is running same fps as before.No changes.Bt the resulation became more clear and set to 2x.

**Comment by DennyJod** [comment]
> You can actually run this game at full speed with resolution hack. Link:https://youtu.be/VJC4PhFovwI

Just tell me which no. Build of citra mmj u using

**Comment by Tappy-tech** [comment]
Have you all followed everything in tutorial?

**Comment by shabbirmahmud** [comment]
> Have you all followed everything in tutorial?
> Edit: I'm using the latest build.

Yes i followed the tutorial.But no changes for me in pokemon x.

**Comment by DennyJod** [comment]
> Have you all followed everything in tutorial?
> Edit: I'm using the latest build.

This thing works for some doesn't for others, idk the cause
