### ISSUE TITLE
Por favor arreglen en Pokemon X e Y tengo que picarle muchas veces a la A para interactuar con las cosas 

### ISSUE THREAD

**Issue by ManoloGM** [weihuoya/citra#227]
Por favor arreglen en Pokemon X e Y tengo que picarle muchas veces a la A para interactuar

**Comment by ajay9634** [comment]
It is also my problem, but I fixed this by clear storage at least 20gb free, so problem fixed for these games.
I have realme 4/64  and 128 gb external. So I put these rom to sd card. By increasing free space ,my problem have been fixed for these games.

**Comment by ManoloGM** [comment]
No me sirvió ya tengo 23 GB de almacenamiento libres y no sigue teniendo el
problema es 4/64

**Comment by DennyJod** [comment]
> It is also my problem, but I fixed this by clear storage at least 20gb free, so problem fixed for these games.
> I have realme 4/64 and 128 gb external. So I put these rom to sd card. By increasing free space ,my problem have been fixed for these games.

What was the problem exactly? And what happened when you moved rom to sd card?

**Comment by DennyJod** [comment]
I can't understand this language, I don't even know which is it to use Google translate.

**Comment by ajay9634** [comment]
I faced problem-  press a button responding lately. In my phone Pokemon sun outline facing this problem. So when I pressed many time a button, then it worked. So I clear my phone storage by moving all 3ds rom to sd card and also I keep 20gb free space in phone and sd card. So problem fixed. Now a button fixed. I don't know root of problem. But I fixed this way.

**Comment by DennyJod** [comment]
> I faced problem- press a button responding lately. In my phone Pokemon sun outline facing this problem. So when I pressed many time a button, then it worked. So I clear my phone storage by moving all 3ds rom to sd card and also I keep 20gb free space in phone and sd card. So problem fixed. Now a button fixed. I don't know root of problem. But I fixed this way.
> My phone is realme C3 , 4/64. Helio g70

Even I had this problem when using 30fps cheat let's see

**Comment by ManoloGM** [comment]
O pero a mí no me funcionó sigo con el problema

**Comment by ajay9634** [comment]
Clear app cache and reinstall app

**Comment by ManoloGM** [comment]
Lo acabo de intentar y no me funcionó :'(

**Comment by ajay9634** [comment]
Wait for update

**Comment by ManoloGM** [comment]
Si, muchas gracias por intentar ayudarme te lo agradezco
