### ISSUE TITLE
Lag and heating issue in SD 660 and 665 soc

### ISSUE THREAD

**Issue by Shah992** [weihuoya/citra#230]
Hey dear developer thanks for developing this amazing emulator app but your emulator does not work with many Soc's like mine realme5 sd 665, I know for the proper development you need time but I highly request to you that please optimize this app for SD 665 and other mid range Qualcomm Soc's. thank you

**Comment by shabbirmahmud** [comment]
I am using snapdragon 665 realme 5i.I get average 20-25 fps on pokemon x in latest update.It was always running the same fps.I didn't see any major changes.But with this fps the game is not palyable and too laggy in grassy places.And the game diagonals not working properly.The water type pokemon is not showing their real color.They are all white.Above all pokemon x,y is not playable in this soc right now.I hope the devoloper will fix pokemon x related issu.

**Comment by DennyJod** [comment]
Yes same issue, using sd720g getting odd 20 fps and quite some lag. The mmj port has yet to optimise for mid end Snapdragon. Mali has seen unbelievable improvement in past few builds so I am sure Snapdragon can handle it too with adreno GPU and open source gles drivers.
See #209 my issue.

**Comment by DennyJod** [comment]
> I am using snapdragon 665 realme 5i.I get average 20-25 fps on pokemon x in latest update.It was always running the same fps.I didn't see any major changes.But with this fps the game is not palyable and too laggy in grassy places.And the game diagonals not working properly.The water type pokemon is not showing their real color.They are all white.Above all pokemon x,y is not playable in this soc right now.I hope the devoloper will fix pokemon x related issu.

Enable accurate multiplication at accurate option. White Pokemon glitch fixed.

**Comment by shabbirmahmud** [comment]
> Enable accurate multiplication at accurate option. White Pokemon glitch fixed.

Turning on accurate multiplication at accurate the fps drops a little.It becomes more unplayable in pokemon x than before but white glitch fixes.

**Comment by shabbirmahmud** [comment]
Somone facing diagonal issu in pokemon x like using circle pad the character running is not smooth like other pokemon games omrb alsap us um??

**Comment by DennyJod** [comment]
> Somone facing diagonal issu in pokemon x??Like using circle pad the character running is not smooth.Bt other pokemon games omrb alsap us um is very smooth.

Bro idk how u getting 20-25 I m getting 15 fps in mmj with accurate multiplication on. Official works better but mmj has water type glitch fixed.

My problems are:-
In official
•) Water type glitch

In mmj
•) Low fps & bad performance
•) When tap x menu screen becomes red for some time. When enter a house screen becomes blue. 

I m playing Pokemon X, I wish these issues are fixed soon.

**Comment by DennyJod** [comment]
I am unable to take screenshots at exact time when it becomes red and blue but it happens and seriously not as much a big issue as improving performance, but still I want it to be fixed soon. Waiting here.

**Comment by shabbirmahmud** [comment]
> Bro idk how u getting 20-25 I m getting 15 fps in mmj with accurate multiplication on

I turned on performance mode.Withouut performance mode i get fps like ur's.

![Screenshot_2021-02-21-05-28-20-38](https://user-images.githubusercontent.com/47573399/108633803-7dda9b00-74a0-11eb-9378-92edac9f9d6e.jpg)

**Comment by DennyJod** [comment]
> > Bro idk how u getting 20-25 I m getting 15 fps in mmj with accurate multiplication on
> 
> I turned on performance mode.Withouut performance mode i get fps like ur's.
> 
> ![Screenshot_2021-02-21-05-28-20-38](https://user-images.githubusercontent.com/47573399/108633803-7dda9b00-74a0-11eb-9378-92edac9f9d6e.jpg)

Umhmm

**Comment by DennyJod** [comment]
> > Bro idk how u getting 20-25 I m getting 15 fps in mmj with accurate multiplication on
> 
> I turned on performance mode.Withouut performance mode i get fps like ur's.
> 
> ![Screenshot_2021-02-21-05-28-20-38](https://user-images.githubusercontent.com/47573399/108633803-7dda9b00-74a0-11eb-9378-92edac9f9d6e.jpg)

Bro I got it.
I am getting full fps no frame drops in citra mmj Pokemon x 2x resolution. By using 100 resolution factor trick. Just don't use in built WPS office editor, delete it. Download Astro file editor then open citra mmj config in it, then edit resolution factor to 100 then open app. U will get black screen, but hear audio, press a twice to get in game but u can't see it yet due to black screen, now make resolution 2x , enable fmv hack, skip slow draw and skip cpu access, leave linear filtering untouched, and u will get full fps!!!

**Comment by shabbirmahmud** [comment]
> Bro I got it.
> I am getting full fps no frame drops in citra mmj Pokemon x 2x resolution. By using 100 resolution factor trick. Just don't use in built WPS office editor, delete it. Download Astro file editor then open citra mmj config in it, then edit resolution factor to 100 then open app. U will get black screen, but hear audio, press a twice to get in game but u can't see it yet due to black screen, now make resolution 2x , enable fmv hack, skip slow draw and skip cpu access, leave linear filtering untouched, and u will get full fps!!!

Wow bro.Man its like miracle.I am geting 35-39 fps in pokemon x now on citra mmj.Idk what made difference changing the editor.But it really works.Thank u so much bro.
How much fps ur getting??
![Screenshot_2021-02-24-19-36-25-09_53c01e3b6443161a8deff0f1f7f140ba](https://user-images.githubusercontent.com/47573399/109008996-2e7eaf80-76d8-11eb-8247-60132db30e3c.jpg)
![Screenshot_2021-02-24-19-36-11-26_53c01e3b6443161a8deff0f1f7f140ba](https://user-images.githubusercontent.com/47573399/109009017-33dbfa00-76d8-11eb-9135-0e2ae0dd37b0.jpg)

**Comment by DennyJod** [comment]
> > Bro I got it.
> > I am getting full fps no frame drops in citra mmj Pokemon x 2x resolution. By using 100 resolution factor trick. Just don't use in built WPS office editor, delete it. Download Astro file editor then open citra mmj config in it, then edit resolution factor to 100 then open app. U will get black screen, but hear audio, press a twice to get in game but u can't see it yet due to black screen, now make resolution 2x , enable fmv hack, skip slow draw and skip cpu access, leave linear filtering untouched, and u will get full fps!!!
> 
> Wow bro.Man its like miracle.I am geting 35-39 fps in pokemon x now on citra mmj.Idk what made difference changing the editor.But it really works.It became smooth than the official.Thank u so much bro.
> 
> How much fps ur getting??
> 
> ![Screenshot_2021-02-24-19-36-25-09_53c01e3b6443161a8deff0f1f7f140ba](https://user-images.githubusercontent.com/47573399/109008996-2e7eaf80-76d8-11eb-8247-60132db30e3c.jpg)
> ![Screenshot_2021-02-24-19-36-18-79_53c01e3b6443161a8deff0f1f7f140ba](https://user-images.githubusercontent.com/47573399/109009123-5cfc8a80-76d8-11eb-84c6-bb7c34275315.jpg)

Same bro, I am getting 35-40 fps in outside world at 2x resolution. Btw do you know a way to fix the glitch when we enter or exit a building the screen becomes blue, and sometimes when press X menu I get red screen.
![IMG_20210224_220127_045](https://user-images.githubusercontent.com/78195251/109032763-fd0fdf00-76eb-11eb-843f-ab50bc66d6f9.jpg)

**Comment by DennyJod** [comment]
![Screenshot_2021-02-24-22-03-09-48_53c01e3b6443161a8deff0f1f7f140ba](https://user-images.githubusercontent.com/78195251/109032900-20d32500-76ec-11eb-8c90-151ba1a25d6b.jpg)
![Screenshot_2021-02-24-22-03-17-88_53c01e3b6443161a8deff0f1f7f140ba](https://user-images.githubusercontent.com/78195251/109032906-22045200-76ec-11eb-85df-fd1681ef6e8a.jpg) 
This is my performance it is op.

**Comment by DennyJod** [comment]
But there is one issue, in battle move animations are missing when using this trick. So I guess I will stick with pc build.

**Comment by shabbirmahmud** [comment]
>Btw do you know a way to fix the glitch when we enter or exit a building the screen becomes blue, and sometimes when press X menu I get red screen.

Sry i dont know the fix of this and i am not getting blue screen when i enter or exit any building.But i get red screen when pressing x menu though.Bt it is for a very short time maybe 1 miliseceond.So it is not much a problem for me.Performance is a matter for me.Bt if i know anything about it in future I will surely let u know.

>But there is one issue, in battle move animations are missing when using this trick. So I guess I will stick with pc build

Yeah this is a major issu.Move animations are very important for pokemon.I am thinking when i will do any important battle like league I will change the resolution factor to 1 again.I think it is very reliable in playing games in android than pc.

**Comment by DennyJod** [comment]
> > Btw do you know a way to fix the glitch when we enter or exit a building the screen becomes blue, and sometimes when press X menu I get red screen.
> 
> Sry i dont know the fix of this and i am not getting blue screen when i enter or exit any building.But i get red screen when pressing x menu though.Bt it is for a very short time maybe 1 miliseceond.So it is not much a problem for me.Performance is a matter for me.Bt if i know anything about it in future I will surely let u know.
> 
> ![Screenshot_2021-02-25-00-05-04-65_53c01e3b6443161a8deff0f1f7f140ba](https://user-images.githubusercontent.com/47573399/109045116-651af100-76fd-11eb-8e72-1e584f696caf.jpg)
> 
> > But there is one issue, in battle move animations are missing when using this trick. So I guess I will stick with pc build
> 
> Yeah this is a major issu.Move animations are very important for pokemon.I am thinking when i will do any important battle like league I will change the resolution factor to 1 again.I think it is very reliable in playing games in android than pc.

Ok thanks.

And battle animations are very important for me, but if they are missing I will play on my laptop then. My game is almost done I m on 7th gym.

**Comment by shabbirmahmud** [comment]
@DennyJod bro can u told me is citra mmj is going to get support for local multiplayer locked room?We can't join private room in android bt we can in pc.We can't chat with other players in android who is connected in room/server.But we can pc? Is this two feature will get on android version? If it comes the game will be more fun playing with others.Maybe i should create a issu about this.

**Comment by DennyJod** [comment]
> @DennyJod bro can u told me is citra mmj is going to get support for local multiplayer locked room?We can't join private room in android bt we can in pc.We can't chat with other players in android who is connected in room/server.But we can pc? Is this two feature will get on android version? If it comes the game will be more fun playing with others.Maybe i should create a issu about this.

Bro abhi local multiplayer add hogya whi badi baat hai for android. I don't think abhi infrared options add honge. First they will improve performance then work on multiplayer. That's how it worked for pc builds.

**Comment by shabbirmahmud** [comment]
> Bro abhi local multiplayer add hogya whi badi baat hai for android. I don't think abhi infrared options add honge. First they will improve performance then work on multiplayer. That's how it worked for pc builds.

Bt citra mmj already implemented the local multiplayer support on android.Only remaining is that two feature to be implemented.It would be more nice if they can give online multiplayer support.

**Comment by shabbirmahmud** [comment]
Did u know citra mmj can locally battle and trade now?

**Comment by DennyJod** [comment]
> > Bro abhi local multiplayer add hogya whi badi baat hai for android. I don't think abhi infrared options add honge. First they will improve performance then work on multiplayer. That's how it worked for pc builds.
> 
> Bt citra mmj already implemented the local multiplayer support on android.Only remaining is that two feature to be implemented.It would be more nice if they can give online multiplayer support.
> ![Screenshot_20210301-035745_Citra](https://user-images.githubusercontent.com/47573399/109435037-79832480-7a42-11eb-8995-75e5798cb7b6.png)

Bro read my msg, I said local multiplayer has been added, that in itself is a big deal. Online multiplayer will be a while, bcoz if the official team doesn't bring the port to the emulator then it's hard for unofficial builds to release them sooner.

**Comment by shabbirmahmud** [comment]
>Bro read my msg, I said local multiplayer has been added, that in itself is a big deal.

Google translate sucks

>Online multiplayer will be a while, bcoz if the official team doesn't bring the port to the emulator then it's hard for unofficial builds to release them sooner.

Is online multiplayer available on pc version of citra?Bro I said like I can battle or trade with u right now on android using citra mmj local multiplayer.Its local bt seems like online multiplayer.Real Nintendo multiplayer maybe not available on pc nor android official citra.Only I need is implement two support in local multiplayer.That is if I battle with u I want to chat with u like pc bt in android I can't.And some server/room is locked 🔒 that's why I can't join that room in mmj.It's need password 🔑.Bt citra mmj has no password input box.This 2 feature i was talking about.

**Comment by DennyJod** [comment]
> > Bro read my msg, I said local multiplayer has been added, that in itself is a big deal.
> 
> Google translate sucks
> 
> > Online multiplayer will be a while, bcoz if the official team doesn't bring the port to the emulator then it's hard for unofficial builds to release them sooner.
> 
> Is online multiplayer available on pc version of citra?Bro I said like I can battle or trade with u right now on android using citra mmj local multiplayer.Its local bt seems like online multiplayer.Real Nintendo multiplayer maybe not available on pc nor android official citra.Only I need is implement two support in local multiplayer.That is if I battle with u I want to chat with u like pc bt in android I can't.And some server/room is locked 🔒 that's why I can't join that room in mmj.It's need password 🔑.Bt citra mmj has no password input box.This 2 feature i was talking about.

Bro u know what u should do?
Create a new issue for that, and explain in detail what you want there.

**Comment by DennyJod** [comment]
Bcoz such said features are not added in official port it's hard to bring it in mmj, but weihouya added local multiplayer when no one expected it, who knows maybe in some days we get online multiplayer.

**Comment by shabbirmahmud** [comment]
> Bcoz such said features are not added in official port it's hard to bring it in mmj, but weihouya added local multiplayer when no one expected it.

If weihluya can add local multiplayer without the official port.Then it should be easy to implement, shouldn't it?

**Comment by DennyJod** [comment]
> > Bcoz such said features are not added in official port it's hard to bring it in mmj, but weihouya added local multiplayer when no one expected it.
> 
> If weihluya can add local multiplayer without the official port.Then it should be easy to implement, shouldn't it?

If a service requires infrared connection then it is not so much, but what you demanded can be built. Details idk I m not a developer, only someone working on any version of citra will know how easy or hard it is. You should ask in citra android support android on official discord of citra.

**Comment by shabbirmahmud** [comment]
>Bro u know what u should do?
Create a new issue for that, and explain in detail what you want there.

Ok I will create a new issue.

**Comment by shabbirmahmud** [comment]
Maybe we should delete these conversations.We are just bugging this issue.

**Comment by Shah992** [comment]
😂😂 you guys using this thread as personal chatting, but don't delete this conversation cause weihbuya have to know what problems does we facing

**Comment by shabbirmahmud** [comment]
> 😂😂 you guys using this thread as personal chatting, but don't delete this conversation cause weihbuya have to know what problems does we facing

I will create a new issue about my prblm.This issue is different that's why I deleted this..

**Comment by DennyJod** [comment]
It's not exactly personal chatting more like citra based discussion, but create new thread do that there, this is the wrong thread imo.

**Comment by aecarvalho** [comment]
99% issues here are mainly for the dev to optimise budget phones with bad processors, and the dev is really trying to achieve it in case you have missed the latest commits. But I personally think the best "benchmark" for you would be to check out Speed Test G videos on YouTube, I keep reiterating the same but I really need to emphasize that the mid range phones are no good at GPU processing though it works better at CPU processing. You can see that even the quad core Snapdragon 821 from 2016 beats the octacore Snapdragon 660 from 2018. I would recommend you to buy an older beast phone instead of a new budget phone which would be around a similar price tag.

Secondly if the official Citra works for you then definitely go for it, the unofficial one is being handled by one single Dev, while the official has 4 Devs at least. The only difference for me was that there were no cheats in the official version, for which I used to enter cheats on the unofficial version and it used to get activated on the official one too, don't know if it still works as nowadays for my phone the official works extremely well and I'm using it full time. That being said, any issues PERTAINING TO THE EMULATOR ITSELF is definitely being addressed by the dev of this emulator as far as I can see in the new code additions and deletions.

**Comment by DennyJod** [comment]
> 99% issues here are mainly for the dev to optimise budget phones with bad processors, and the dev is really trying to achieve it in case you have missed the latest commits. But I personally think the best "benchmark" for you would be to check out Speed Test G videos on YouTube, I keep reiterating the same but I really need to emphasize that the mid range phones are no good at GPU processing though it works better at CPU processing. You can see that even the quad core Snapdragon 821 from 2016 beats the octacore Snapdragon 660 from 2018. I would recommend you to buy an older beast phone instead of a new budget phone which would be around a similar price tag.
> 
> Secondly if the official Citra works for you then definitely go for it, the unofficial one is being handled by one single Dev, while the official has 4 Devs at least. The only difference for me was that there were no cheats in the official version, for which I used to enter cheats on the unofficial version and it used to get activated on the official one too, don't know if it still works as nowadays for my phone the unofficial works extremely well and I'm using it full time. That being said, any issues PERTAINING TO THE EMULATOR ITSELF is definitely being addressed by the dev of this emulator as far as I can see in the new code additions and deletions.

I have boosted my fps using resolution factor trick, the only issue I have is #236 if I find a fix for it I won't have any problems, and I do have a tab s7+, on it I can get full fps using 2x resolution in gen 6 Pokemon games but the #236 issue still happens on it too as well as my own handheld device which runs a 720g Snapdragon.

**Comment by aecarvalho** [comment]
Try custom ROM, see if that works, again I've already posted this earlier too but my choice would be close to stock, such as Pixel Experience, Lineage OS, Havoc OS, etc.
