### ISSUE TITLE
Tegra devices

### ISSUE THREAD

**Issue by masies-hack** [weihuoya/citra#233]
These days has been released an “official” version of android 10 for Nintendo switch.
Well your citra version, it’s only version works fine on android.
But I have a feeling about your emulator on Nintendo switch. The GPU may not work fine.
Only work at 100% CPU, Nintendo switch has NVIDIA Tegra like Nvidia shield.
It would be interesting add an option on settings, enable or disable Tegra GPU usage & specific clear “(Tegra devices only)”
It’ just a suggestion, really don’t know clear how really emulator works on android.
Thanks & good work

**Comment by aecarvalho** [comment]
Why play 3ds games on switch which is specifically suited for switch games? Better luck with an android phone because Switch has basically just a quad core processor so it cannot handle having to emulate a 3DS environment within an Android environment within a Switch system

**Comment by masies-hack** [comment]
Well on android it’s the only way can play PSP Games with best performance, it’s the only way can play dolphin emulator, it’s the only way can play DS games. Yes with Andortid OS.
Only CITRA works & don’t crash & don’t “error has occurred” & close program; is this version.
But the problem I see, (maybe I’m wrong) only use CPU.
Nintendo Swirch Like nVidia SHILD use tegra GPU & your citra don’t take advantage.
nVidia SHILD its thing it for android & use Android. Not’s an invention like can be Andorid for Nintendo switch.
I just suggest you for made citra more generic for use it in more devices.
Because who knows if in a future will make more devices with tegra technology.
Say it that, if you do a citra with tegra compatibility & I try it on my switch & it works & can play a lot of games for now I can’t. better for community use android on switch.
If no, no problem. It’s generic software.
