### ISSUE TITLE
Bad performance at snapdragon 439 for all game , only some game can run smooth

### ISSUE THREAD

**Issue by Shironeko7** [weihuoya/citra#234]
Please update citra for snapdragon 625 or lower and fix some bug in game. i will wait it soon. Thank you

!](https://user-images.githubusercontent.com/79598316/109043739-3b18fd00-7704-11eb-9f1b-e2e2b5819923.jpg)

**Comment by SakiNawak** [comment]
Buy a new phone

**Comment by DennyJod** [comment]
Bcoz it's low end processor that's why, even mid end isn't fully playable yet.

**Comment by aecarvalho** [comment]
> Please update citra for snapdragon 625 or lower and fix some bug in game. i will wait it soon. Thank you
> 
> !](https://user-images.githubusercontent.com/79598316/109043739-3b18fd00-7704-11eb-9f1b-e2e2b5819923.jpg)

Can you play PUBG or Asphalt 9 or Call of Duty without lags? If so then you're at 75% of what Citra can offer because it's emulating another system altogether.

**Comment by Adityabyahut** [comment]
Is there a way to compromise with the resolution (0.5x) to increase speed and frames till the citra become enough powerful to run on these devices....

**Comment by Gamemulatorer** [comment]
Wake up!
