### ISSUE TITLE
How to fix this glitch?

### ISSUE THREAD

**Issue by DennyJod** [weihuoya/citra#236]
Anyone knows how to fix this glitch where the screen becomes blue when I enter or exit a house or a battle starts or a wild encounter in citra mmj? Not talking about flickering while recording, when I enter or exit a building I get blue screen, when battle begins I get a blue screen, it is really annoying...
I have test Pokemon X and Pokemon Omega Ruby, both have this issue.

https://user-images.githubusercontent.com/78195251/109518466-47200880-7ad0-11eb-80ca-82d7e0561e4d.mp4

**Comment by aecarvalho** [comment]
Try to use Accurate setting in Accurate Multiplication in Settings menu

**Comment by DennyJod** [comment]
> Try to use Accurate setting in Accurate Multiplication in Settings menu

I already do that, for correct greninja

**Comment by RangerKevin2** [comment]
Hello, i have the same problem, this method worked for me: go to settings and try to disable "preload textures" , "use custom textures". Then, go to in-game settings and disable "skip CPU access" and "skip slow draw". If it doesn't work, the default settings of citra are working fine, so just reset citra and use the default settings without modify anything

**Comment by aecarvalho** [comment]
Absolutely, and preferably don't mess around texture hacks, they cause a lot of glitches.

**Comment by DennyJod** [comment]
> Hello, i have the same problem, this method worked for me: go to settings and try to disable "preload textures" , "use custom textures". Then, go to in-game settings and disable "skip CPU access" and "skip slow draw". If it doesn't work, the default settings of citra are working fine, so just reset citra and use the default settings without modify anything

None of them were on in the first place, and still the glitch was happening

**Comment by DennyJod** [comment]
> Absolutely, and preferably don't mess around texture hacks, they cause a lot of glitches.

Only thing I used was resolution factor trick but even before using it the glitch was happening, it happens on a lot of devices, it's not something any config caused or anything.

**Comment by aecarvalho** [comment]
Device specific issue then

**Comment by DennyJod** [comment]
I also have tab s7+ I never used any trick, config or out of default settings on it, still the glitch was happening so there.

**Comment by DennyJod** [comment]
I have also seen a lot of YouTube videos where there gameplay also has same issues, so I guess certain devices this isn't happening but in a quite a few it is happening.
