### ISSUE TITLE
Citra MMJ_20200409 Bug

### ISSUE THREAD

**Issue by adiiiis** [weihuoya/citra#24]
Pokemon X : When I press play in pokemon Amie,the emulator opens file explorer app and when I close it and go to citra it opens it again, while in pokemon aime. This happens until it crashes. Is anyone else facing this 
issue

**Comment by Kanjiro123** [comment]
Does anyone know how to fix this?
![Screenshot_2020-04-11-19-49-37-28_53c01e3b6443161a8deff0f1f7f140ba](https://user-images.githubusercontent.com/63500565/79044488-fee9c480-7c37-11ea-8188-c3d572fec91e.png)

**Comment by takeshineale128** [comment]
MMJ builds are not supported because they are unofficial builds

**Comment by Kanjiro123** [comment]
So that means it can't be fixed and there's no platform for android? That
sucks

**Comment by Andy1091** [comment]
settings - activate Accurate multiplication ;)

**Comment by 3SSAMSSF2** [comment]
> Pokemon X : When I press play in pokemon Amie,the emulator opens file explorer app and when I close it and go to citra it opens it again, while in pokemon aime. This happens until it crashes. Is anyone else facing this
> issue

someone fix the smash bros 3ds fps thing pls
