### ISSUE TITLE
(Android) Dead or Alive Dimesnions shows black screen

### ISSUE THREAD

**Issue by RaduNastase** [weihuoya/citra#240]
The game shows black screen, but i can hear menu sounds when i press buttons, though it crashes after that.

Tried different settings, all the same behaviour.

**Comment by RaduNastase** [comment]
Scratch that, it works. But it "needs" to be started in default dual screen mode, as you need to check some boxes before actually starting the game.

**Comment by stizzo1** [comment]
Try clearing the shaders cache.

I don't have this issue on Android 10 and SD855. (latest build)

**Comment by stizzo1** [comment]
This is an example of Dead Or Alive Dimensions gameplay with the latest build (20210305), with 4x resolution (1600x960) and with FXAA Shader and Linear Filter enabled:

https://streamable.com/1gfhqw

Now you can safely close both this thread and the other thread.

The build has no problems.

SnapDragon 855, Android 10.

**Comment by RaduNastase** [comment]
Yes, this game works very well.

Thanks so much for the feedback!
