### ISSUE TITLE
Compile instruction for android?

### ISSUE THREAD

**Issue by Muzika** [weihuoya/citra#243]
Hi guys. Anyone can guide me on how to compile citra from source for Android? Looking at the readme there's.only Windows Linux & Mac for compile instructions. I would appreciate it if somebody can guide me on how to do this specially using Android Studio if possible.

**Comment by aecarvalho** [comment]
Shouldn't you be asking this at the official Citra page?
https://github.com/citra-emu/citra-android/issues

**Comment by Muzika** [comment]
I can compile the official version just fine. This one however  doesn't. I'm stuck with opengl_rasterizer_cache undefined error.
