### ISSUE TITLE
Is the Single Screen layout option, actually both screens...? 

### ISSUE THREAD

**Issue by RaduNastase** [weihuoya/citra#244]
...with the 2nd screen invisible on top of the main one!? (But with working commands/inputs)

In Super Street Fighter 4, there are BIG invisible buttons in the main screen, corresponding to the 2nd screen layout.

**Comment by stizzo1** [comment]
Because the two screens work in sync. (as in real 3DS hardware).

Even on Desktop, you get the same results with the mouse.

You can always change the appearance and size of the window through the custom config screen.

**Comment by RaduNastase** [comment]
Oh, so it's how it should be then. I thought there was something messed up on my part. 
It's actually neat and useful to have the 2nd screen overlayed (and zoomed in) over the first, at 0% opacity.
