### ISSUE TITLE
Can official citra and mmj coexist ?

### ISSUE THREAD

**Issue by RaduNastase** [weihuoya/citra#247]
Can they both be installed in the same phone at the same time? Do they use different folders?

**Comment by Lixi-ON** [comment]
Yes,you can have both installed,but the progress on every game will be the same

**Comment by RaduNastase** [comment]
Thanks, but, what do you mean by "progress"?

**Comment by Lixi-ON** [comment]
I mean everything you do in one emulator will be done at the other
If you change the settings,at the other emulator they will be the same

**Comment by RaduNastase** [comment]
Oh, interesting. Thanks!
