### ISSUE TITLE
"C" stick no works on smash

### ISSUE THREAD

**Issue by Chit1n** [weihuoya/citra#248]
Issue

**Comment by stizzo1** [comment]
![Screenshot_2021-03-18-05-54-16-668_org citra emu](https://user-images.githubusercontent.com/43874809/111575298-54b2df00-87ae-11eb-85c0-8cda4da4ef79.jpg)

**Comment by Chit1n** [comment]
> ![IMG_20210318_060514](https://user-images.githubusercontent.com/43874809/111575847-8ed0b080-87af-11eb-8802-49aac0c23cf7.jpg)
> 
> Edit: Alternatively, try the penultimate build. (if you use the last build)

In all versions is the same problem, the C stick appear in screen but in game no have reactions, its no good.

**Comment by stizzo1** [comment]
![IMG_20210318_074301](https://user-images.githubusercontent.com/43874809/111583740-2092ea80-87bd-11eb-881d-1dc50f6531e3.jpg)

The game in question, does not support the sliding pad, therefore, does not support the C-Stick.

This is not a problem with the build.

The Resident Evil Revelations game, for example, supports the C-Stick.

**Comment by heyRyzen** [comment]
> ![IMG_20210318_074301](https://user-images.githubusercontent.com/43874809/111583740-2092ea80-87bd-11eb-881d-1dc50f6531e3.jpg)
> 
> The game in question, does not support the sliding pad, therefore, does not support the C-Stick.
> 
> This is not a problem with the build.
> 
> The Resident Evil Revelations game, for example, supports the C-Stick.

yeah cuz Resident Evil Revelations support circle pad pro

**Comment by Chit1n** [comment]
> ![IMG_20210318_074301](https://user-images.githubusercontent.com/43874809/111583740-2092ea80-87bd-11eb-881d-1dc50f6531e3.jpg)
> 
> The game in question, does not support the sliding pad, therefore, does not support the C-Stick.
> 
> This is not a problem with the build.
> 
> The Resident Evil Revelations game, for example, supports the C-Stick.

In the play store ver. the C stick is activated and works In smash bros, but in this build no. I see in resident evil works but in smash no.

**Comment by stizzo1** [comment]
The other version of the emulator uses specific hacks.

This version of the emulator uses its own specific hacks. (and as close as you can get to the real hardware of a DS3).

I repeat and I firmly believe that this is a non-problem, non-issue.

But only vanity.
