### ISSUE TITLE
Shader cache uses too much RAM. (Add RAM usage limit option)

### ISSUE THREAD

**Issue by Tappy-tech** [weihuoya/citra#249]
While playing the game, you can see in Menu RAM usage. And "RAM usage" can get too much high. For example:
![Screenshot_2021-03-18-14-20-04-08_53c01e3b6443161a8deff0f1f7f140ba](https://user-images.githubusercontent.com/72254437/111618811-de39cf80-87f5-11eb-8332-ce72ff42f5b8.jpg)
It is shown here that the RAM usage is 1GB. And phones with less than mine 8GB RAM, can experience issues. With RAM usage limit, the RAM won't use higher, than 1GB for example.

**Comment by stizzo1** [comment]
6 Gigabyte memory here and no problem.

If the games are smoother and without the 2x3 fussing over texture loading stuttering, you can only thank the increased cache.

But if that bothers you, there is always the other version of the emulator.

Don't ruin a good thing.

**Comment by andrewdev738** [comment]
3 Gigabyte memory here and no problem
Doesn't matter how much RAM the game uses, but rather the amount of stuff that's going on to process for the performance to drop.
If they add a RAM limit option then a lot of stuff won't load

**Comment by Luwaee** [comment]
Not really a problem since you are emulating a game, I think it is understandable that if you're emulating, ram usage would increase. Adding a limit to ram consumption would probably just bottleneck the emulator.

**Comment by stizzo1** [comment]
> Not really a problem since you are emulating a game, I think it is understandable that if you're emulating, ram usage would increase. Adding a limit to ram consumption would probably just bottleneck the emulator.

Are we going to stop spewing random crap?

Memory management is not a build issue.

Memory management is a problem of each manufacturer's Rom specs.

You can have 16GB of memory on your super shiny last generation smartphone, but if it has a shitty memory management, the problem is of the manufacturer.

You don't even know what a cache is and how it works, let alone the mapping of the memory.
