### ISSUE TITLE
MHXX Crash 

### ISSUE THREAD

**Issue by EmanonnonamE** [weihuoya/citra#255]
When using the latest version of mmj 20210406 crashes when launching MHXX(Monster Hunter Double Cross). My phone uses SD720G and Android 10.
[citra_log.txt](https://github.com/weihuoya/citra/files/6262367/citra_log.txt)

**Comment by venomop10** [comment]
Yes mine too crashing

**Comment by EmanonnonamE** [comment]
Downloaded the latest version with the fix its working now keep up the great work
