### ISSUE TITLE
How about 60 fps,3ds firmware and wifi

### ISSUE THREAD

**Issue by felixkaung** [weihuoya/citra#258]

**Comment by venomop10** [comment]
3ds firmware would be cool

**Comment by shabbirmahmud** [comment]
> 3ds firmware would be cool

Yeah if we could load the game like real console.

**Comment by Tappy-tech** [comment]
WiFi? Do you mean Online multiplayer? It is possible now.

**Comment by aecarvalho** [comment]
> _No description provided._

Why though? Isn't the app doing exactly what it's supposed to do? It's called "Citra Emulator", not "Nintendo 3DS Emulator" even though it serves that purpose for playing games, if you want a Nintendo system then buy that, as you know the actual Nintendo 3DS firmware is proprietary, hence copying that or using it directly would be a copyright infringement.

**Comment by felixkaung** [comment]
In melonds emulator we can load ds firmware and dai firmware but citra can't load 3ds load firmware

**Comment by aecarvalho** [comment]
> In melonds emulator we can load ds firmware and dsi firmware but citra can't load 3ds load firmware

MelonDS is on PC obviously...

By 'load", you mean legally right? By dumping firmware from your own 3DS? If not then good luck 😅
P. S. Requesting to "load" 3DS firmware is an issue for Citra official issues page; https://github.com/citra-emu/citra/issues as this is the unofficial Android port, same hasn't even been implemented in the official Android version yet

**Comment by andrewdev738** [comment]
> > In melonds emulator we can load ds firmware and dsi firmware but citra can't load 3ds load firmware
> 
> MelonDS is on PC obviously...
> 
> By 'load", you mean legally right? By dumping firmware from your own 3DS? If not then good luck 😅
> P. S. Requesting to "load" 3DS firmware is an issue for Citra official issues page; https://github.com/citra-emu/citra/issues as this is the unofficial Android port, same hasn't even been implemented in the official Android version yet

MelonDS has a build on Android and yes, importing a ds/dsi firmware is needed

**Comment by shabbirmahmud** [comment]
>MelonDS has a build on Android and yes, importing a ds/dsi firmware is needed

Bios and firmware is not mandatory though. But we can enjoy some extra features like download play, some DSi system app etc. It also helps to save Ninetendo WFC settings permanently for online multiplayer. Overall it will be a nice feature if citra add 3ds firmware like it. We can just feel like we are using actual console.

**Comment by shabbirmahmud** [comment]
> WiFi? Do you mean Online multiplayer? It is possible now.

That's not online multiplayer that's local multiplayer. But we can use it as online. I am not sure is it possible online multiplayer for citra? Coz we can't connect to the ninetendo server on games like 'Pokemon Bank.'  If it would support online multiplayer then we could connect to the ninetendo server.
