### ISSUE TITLE
Resolution not changing

### ISSUE THREAD

**Issue by ajay9634** [weihuoya/citra#260]
Default resolution is 2x, but different resolution not working,when I press
1x,2x,3x,4x,.  Then same result 2x.  In  Citra_MMJ_20210407.apk

My phone is realme c3 ,Helio g70

**Comment by Lorenzo8888** [comment]
same problem to me too( snapdragon 855)

**Comment by shabbirmahmud** [comment]
Same here sd 665

**Comment by ajay9634** [comment]
Now this is fixed
