### ISSUE TITLE
Low fps in resident evil revelation in mali gpu

### ISSUE THREAD

**Issue by ajay9634** [weihuoya/citra#271]
Low fps used in resident evil revelation, 
My device is realme c3 ,4/64

**Comment by stizzo1** [comment]
Your SOC is slow.

But for slightly better texture loading (experience on my SOC 855), you can try mmj version 20210305

**Comment by andrewdev738** [comment]
+RAM ≠ +SPEED
Your device uses the Helio G70, way below the minimum requirement for Citra (SD 730)

**Comment by ajay9634** [comment]
Now 750mb ram used, performance improved, but still slow

**Comment by aecarvalho** [comment]
RAM has nothing to do with game performance directly (unless the game **demands that amount from your phone** .) Your phone allocates RAM for the game, and the title has to demand that amount of RAM from the system, at best you can ask Resident Evil developers to do something about it.

Also FYI, the original Nintendo 3DS console only has 256 MB RAM, how much do you think the game would require?
