### ISSUE TITLE
Low fps in ultra sun double and multi battles

### ISSUE THREAD

**Issue by venomop10** [weihuoya/citra#273]
I get 30 fps in double and multi battles in January version of citra mmj. In latest update ultra sun is laggy.In double and multi  pokemon battles i get 24 fps and 65 speed, i enabled fmv and skip slow draw but still it's laggy.my soc sd 845

**Comment by Tappy-tech** [comment]
Try Resolution Hack.

**Comment by venomop10** [comment]
Still laggy ,only in latest build
