### ISSUE TITLE
no 32 bit version

### ISSUE THREAD

**Issue by kena006** [weihuoya/citra#276]
im using a 32 bit chromebook and it wont install because its a 64 bit apk.
please make a 32 bit version so i can use it.

**Comment by GENROGAMER** [comment]
do you think the guy will break his head wasting time trying to make an
emulator for a weak old 32bit architecture and thing of the past wakes up

Em dom, 18 de abr de 2021 22:18, kena006 ***@***.***>
escreveu:

**Comment by Tappy-tech** [comment]
Even if Weihuyoa will make Citra 32 Bit edition, it cab take long + the speed won't be good.

**Comment by ZeldoPiranha** [comment]
> im using a 32 bit chromebook and it wont install because its a 64 bit apk.
> please make a 32 bit version so i can use it.


> im using a 32 bit chromebook and it wont install because its a 64 bit apk.
> please make a 32 bit version so i can use it.

Wake up

**Comment by ZeldoPiranha** [comment]
Wake up

**Comment by enb77777** [comment]
32bit???!! Just buy a new phone.

**Comment by Pokemetti** [comment]
64 bit is a necessity for good emulation speed, and official Citra would need to support it first, afaik it doesn't support it. So if you want a detailed description why it probably wouldn't work very well ask in the official Citra repo.

**Comment by Gamemulatorer** [comment]
Wake Up(3)
