### ISSUE TITLE
Pokémon armi goes horrible 

### ISSUE THREAD

**Issue by SoyXam** [weihuoya/citra#284]
When I start the pokémon armie in Pokémon Omega Ruby the fps fall to 4 fps and like 3%speed, in normal game goes in 30fps and 100% speed
![Screenshot_20210430_190720_org citra emu](https://user-images.githubusercontent.com/78095831/116764845-14b75c80-a9e8-11eb-8708-5febf8bffd39.jpg)
![Screenshot_20210430_190746_org citra emu](https://user-images.githubusercontent.com/78095831/116764854-1a14a700-a9e8-11eb-85be-e5fee479dab1.jpg)

**Comment by Jidogwan** [comment]
Can you touch a Pokemon, too?
X Y Ruby Sapphire There is an error.

**Comment by SoyXam** [comment]
In the past update the speed was like 50% and 10fps, but in that update I couldn't caress the Pokémon, only give them food and play mini games

**Comment by Jidogwan** [comment]
The latest version of April 29 also looks the same.
