### ISSUE TITLE
How to save state? 

### ISSUE THREAD

**Issue by Hidlsh** [weihuoya/citra#286]
I got so far in Pokemon Ultra Moon then realized there was no option to save state. How can I do this??

**Comment by Tappy-tech** [comment]
Save state feature is only for Citra Official. If there were save states, performance would only worsen.

**Comment by sidevesh** [comment]
Can save state option be provided optionally though ? SO those whose need it can enable it (with perf penalty) else it remains off by default,
this would be similar to I think how dolphin has it as well as official Citra.

**Comment by aecarvalho** [comment]
Save state isn't as stable as in game saving. Just use in game saving option!
