### ISSUE TITLE
Performance down in media tek device

### ISSUE THREAD

**Issue by ajay9634** [weihuoya/citra#290]

**Comment by ajay9634** [comment]
In latest citra mmj  20210508
, Performance down in media tek device, legend of Zelda link between world cutscene become slow. Resident evil on 1x become slow . But Digimon World redigitize glitch fixed. Please improve performance for media tek device

**Comment by Giowi** [comment]
Same problem on Samsung device with Exynos 9810.

**Comment by ajay9634** [comment]
Now performance improved, keep up bro
