### ISSUE TITLE
Delay controls for pokemon sun

### ISSUE THREAD

**Issue by playerbano** [weihuoya/citra#292]

**Comment by playerbano** [comment]
Delay controls for pokemon sun and moon. And it always stutter. Mediatek G70

**Comment by FsGabo** [comment]
Disable Fps 30 or fps 60 (v1.0) (v1.2)cheats in the cheat code. I was having this issue in pokemon moon and ultra moon but this is the solution that fix the input lags on my citra. Im using Snapdragon 865 .
