### ISSUE TITLE
Redmi 5 snapdragon 450 Pokemon xy only getting 10-15 fps please fix

### ISSUE THREAD

**Issue by Varun102040** [weihuoya/citra#298]
Resolution trick not working

**Comment by Tappy-tech** [comment]
You should have better device. There's no other fix for low end SD 450.

**Comment by Lemoncak3** [comment]
It's hard to getting decent fps on that device, while citra still in development to increase it's stability and compatibility so maybe the only way is to get a better device.

**Comment by aecarvalho** [comment]
This is the device's own issue, even getting 10-15 FPS is a blessing for a Snapdragon 4xx series. Try a custom ROM like Pixel Experience or Lineage OS if possible, might help improve the performance but don't expect 60 FPS.
Do close the issue as there is no fix for a low end processor.
