### ISSUE TITLE
Add swap screen hotkeys and stretch screen 

### ISSUE THREAD

**Issue by Dimashardian** [weihuoya/citra#304]
Please add swap screen hotkeys and stretched version of single screen just like drastic emulator. Thank you

**Comment by BeF1990** [comment]
Yes, definitely we need swap screen like in DraStic. In my opinion the lack of swap screen button is the biggest con of Citra emulator.

I wish to play on full screen mode for most of the time, but without a swap screen button it’s very frustrating. Every time I have to stop playing and open the options menu.

It would be great if I could map some key on my gamepad to swap screen.

Is any chance for this feature?
