### ISSUE TITLE
Pokemon y stuck

### ISSUE THREAD

**Issue by Lorenzo8888** [weihuoya/citra#306]
<!suddenly it froze and stayed that way (poco X3 pro MIUI 12.5 stable android 11) 
![Screenshot_2021-06-04-07-55-27-673_org citra emu](https://user-images.githubusercontent.com/56827114/120754730-61bdaf80-c50d-11eb-8e7c-ffdd22748008.jpg)
--

Please read the FAQ:
https://citra-emu.org/wiki/faq/

THIS IS NOT A SUPPORT FORUM, FOR SUPPORT GO TO:
https://community.citra-emu.org/

If the FAQ does not answer your question, please go to:
https://community.citra-emu.org/

====================================================

When submitting an issue, please check the following:

- You have read the above.
- You have provided the version (commit hash) of Citra you are using.
- You have provided sufficient detail for the issue to be reproduced.
- You have provided system specs (if relevant).
- Please also provide:
  - For any issues, a log file
  - For crashes, a backtrace.
  - For graphical issues, comparison screenshots with real hardware.
  - For emulation inaccuracies, a test-case (if able).

--->

**Comment by Lemoncak3** [comment]
Mine was worst, it crashes whenever i tried to open the game. While the may version is fine. Maybe for time being you can use the previous version.
