### ISSUE TITLE
Some games crash or stuck at game

### ISSUE THREAD

**Issue by Lemoncak3** [weihuoya/citra#312]
Hi, just want to inform thar after the latest update some of my game have weird behavior such as crashes at pokemon y which didn't happen in 8/5 update. And when play fire emblem awakening at attack scene it will crash as well. Some of other game have some lag as well. So i decided to revert my citra to 8/5 and hoping the future release didn't have this problem since 8/5 update was fine. Thanks a lot weihuoya.

**Comment by TheOG00** [comment]
Yeah
Every departure or in loading screen
