### ISSUE TITLE
There is slowdown in the initial cinematic of Monster Hunter 4 Ultimate and worse performance in the last 2 updates, my device is a POCO X3 Pro

### ISSUE THREAD

**Issue by MrAki-98** [weihuoya/citra#315]

**Comment by Lorenzo8888** [comment]
happens to me on pokemon y small lag animation( poco x3 pro )

**Comment by Ryuksaki** [comment]
Not only in mh4u , this happens in every game now from last three build. The june build broke cpu usage limit coz by enabling it the cutscene use to run at full speed but now cutscene runs horrible.
