### ISSUE TITLE
0 fps games Pokémon y 

### ISSUE THREAD

**Issue by Lorenzo8888** [weihuoya/citra#316]
0  fps pokemon y after half an hour :(  (poco x3 pro
@weihuoya 
Please read the FAQ:
https://citra-emu.org/wiki/faq/

THIS IS NOT A SUPPORT FORUM, FOR SUPPORT GO TO:
https://community.citra-emu.org/

If the FAQ does not answer your question, please go to:
https://community.citra-emu.org/

====================================================

When submitting an issue, please check the following:

- You have read the above.
- You have provided the version (commit hash) of Citra you are using.
- You have provided sufficient detail for the issue to be reproduced.
- You have provided system specs (if relevant).
- Please also provide:
  - For any issues, a log file
  - For crashes, a backtrace.
  - For graphical issues, comparison screenshots with real hardware.
  - For emulation inaccuracies, a test-case (if able).

--->

**Comment by weihuoya** [comment]
how about this version?
[Citra_Test.zip](https://github.com/weihuoya/citra/files/6635835/Citra_Test.zip)

**Comment by Lorenzo8888** [comment]
I'll try Thanks for your hard work!! @weihuoya

**Comment by Lemoncak3** [comment]
I have same issue and using your test build, it works @weihuoya

**Comment by TheOG00** [comment]
Ammm  liugui mansion 2 doesn't work too

**Comment by Lemoncak3** [comment]
With the test version it works but i think it's slower and stutter a lot than may update. Maybe you can take a look @weihuoya? Thanks a lot :)
