### ISSUE TITLE
Games are crashing, losing hope

### ISSUE THREAD

**Issue by AbegailPrinplup** [weihuoya/citra#318]
Every time I try to play a game/try to install CIA it immediately crashes. Help me

**Comment by joyful-cambion** [comment]
Happened to me, just uninstall the emulator, go to your file browser app then find and delete "citra-emu" folder. Now install the emulator again and try again this time it should work fine.

**Comment by TheOG00** [comment]
@AbegailPrinplup phone model?

**Comment by TheOG00** [comment]
@joyful-cambion yur gmail please

**Comment by joyful-cambion** [comment]
What for?

**Comment by TheOG00** [comment]
C mmj Discord

**Comment by joyful-cambion** [comment]
@TheOG00 Ok send to 

jugurta.xd@gmail.com
