### ISSUE TITLE
FMV hack

### ISSUE THREAD

**Issue by Retroism** [weihuoya/citra#321]
Please add FMV hack in the setting so it runs on default without ticking the check button everytime in the in game setting.

**Comment by Tappy-tech** [comment]
Let's suggest all in-game only options being in settings them.

**Comment by TheOG00** [comment]
Settings doesn't saved cuz when i launch the game every time  i must config the game again

**Comment by weihuoya** [comment]
Game will random stuck with FMV hack enbaled. Turn it on if you need.
