### ISSUE TITLE
The game crashes at certain moment when launching from shortcut, but not when launching from Citra.

### ISSUE THREAD

**Issue by Tappy-tech** [weihuoya/citra#329]
This happens after certain action. 
For example...
In Super Smash Bros. For Nintendo 3DS, game crashes when you have to enter something using the keyboard.
In Pokémon Ultra Moon, game crashes after getting through title screen.
These issues could be because of how shortcut works for Citra, although I can't do much about it.

Device: Realme XT
Processor: SD 712
RAM: 8 GB
ROM: 128 GB

Version: Build 20210622

**Comment by weihuoya** [comment]
https://github.com/weihuoya/citra/releases/download/20210622/Citra_MMJ_20210622_FIX.apk
