### ISSUE TITLE
Pokemon omega crash 

### ISSUE THREAD

**Issue by Lorenzo8888** [weihuoya/citra#331]
<a few points while I go out I enter a new place the game makes me go out (poco X3 pro )@weihuoya 

Please read the FAQ:
https://citra-emu.org/wiki/faq/

THIS IS NOT A SUPPORT FORUM, FOR SUPPORT GO TO:
https://community.citra-emu.org/

If the FAQ does not answer your question, please go to:
https://community.citra-emu.org/

====================================================

When submitting an issue, please check the following:

- You have read the above.
- You have provided the version (commit hash) of Citra you are using.
- You have provided sufficient detail for the issue to be reproduced.
- You have provided system specs (if relevant).
- Please also provide:
  - For any issues, a log file
  - For crashes, a backtrace.
  - For graphical issues, comparison screenshots with real hardware.
  - For emulation inaccuracies, a test-case (if able).

--->

**Comment by weihuoya** [comment]
https://github.com/weihuoya/citra/releases/download/20210622/Citra_MMJ_20210622_FIX.apk
