### ISSUE TITLE
dynarmic 子模块的代码404

### ISSUE THREAD

**Issue by android-1995** [weihuoya/citra#332]
[dynarmic @ b6be02e](https://github.com/MerryMage/dynarmic/tree/b6be02ea7fae63aa661ad00763ebd295d1348591)
请MMJ大佬更新一下

**Comment by weihuoya** [comment]
https://github.com/citra-emu/dynarmic-android

**Comment by android-1995** [comment]
https://github.com/MerryMage/dynarmic/tree/b6be02ea7fae63aa661ad00763ebd295d1348591
好像项目里的这个版本是找不到了的 git clone 完整项目的时候会报错
