### ISSUE TITLE
citra mmj not installing

### ISSUE THREAD

**Issue by mjsgN** [weihuoya/citra#340]
Hello team, 
I have a red mi note 9 
Ram 4gb 
Mtk Helio g35 processer 
PowerVR  Rogue ge8320 gpu 
I can't installing the mmj version 
Citra Android is installing but crashing on launching games please help me 🙏😭

**Comment by weihuoya** [comment]
https://github.com/weihuoya/citra/releases/download/20210630/Citra_MMJ_20210630.apk

**Comment by mjsgN** [comment]
Still not working dude 😔😔
