### ISSUE TITLE
Android 11

### ISSUE THREAD

**Issue by GDE0001** [weihuoya/citra#341]

**Comment by RangerKevin2** [comment]
What's your issue ?

**Comment by Gamemulatorer** [comment]
Maybe he can't access his game on sdcard due to android 11 scoped storage restrictions
https://github.com/citra-emu/citra-android/issues/213

**Comment by Luckypatch** [comment]
Very lag after i update to android 11

**Comment by TheOG00** [comment]
@Luckypatch android 11 is slow already with emulators
