### ISSUE TITLE
Easy way to delete CIA's from Citra MMJ

### ISSUE THREAD

**Issue by ghost** [weihuoya/citra#348]
Currently you have to dig through folders and manually delete an CIA installed application

A delete CIA button would be helpful

**Comment by shabbirmahmud** [comment]
You can delete CIA from cheats section.

**Comment by TheOG00** [comment]
Yes an option to delete the .app file and his updates

**Comment by TheOG00** [comment]
@weihuoya deleting archive directory will delete the save files
Why?
