### ISSUE TITLE
Please upload the full git.

### ISSUE THREAD

**Issue by Gamer64ytb** [weihuoya/citra#350]
when I go to download the submodules from the git tool I get this:

fatal: remote error: upload-pack: not our ref b6be02ea7fae63aa661ad00763ebd295d1348591
Fetched in submodule path 'externals/dynarmic', but it did not contain b6be02ea7fae63aa661ad00763ebd295d1348591. Direct fetching of that commit failed.

It fails from the dynarmic download, this is because the git is not complete, please fix this so that we modders can use your code.

**Comment by weihuoya** [comment]
https://github.com/citra-emu/dynarmic-android

**Comment by Gamer64ytb** [comment]
oh, thank you very much weihuoya, by the way I take the opportunity to tell you that your project is fantastic, in fact I will see if I can modify some things in the backend to increase performance and share it with you, good job ❤️.
