### ISSUE TITLE
[Feature Request] Auto-savestate on app close

### ISSUE THREAD

**Issue by SixDigitCode** [weihuoya/citra#352]
One of my favorite features in DraStic is how it automatically creates a savestate when you leave the app. When you open DraStic again, you can pick up right where you left off because of the auto-savestate feature. It makes the game much easier to play in short bursts on a phone, whereas re-loading an ingame save and catching to to where you were is often time-consuming.

I understand that this would likely be very complicated to implement from scratch. If an existing savestate system is implemented in the future, a savestate-on-exit feature would be awesome!

Thanks!

**Comment by Ahmedmksd** [comment]
I'm pretty sure that it's too hard to include,but maybe

**Comment by TheOG00** [comment]
@SixDigitCode he need to implement the save state feature before doing yours
