### ISSUE TITLE
Citra mmj on Android 11

### ISSUE THREAD

**Issue by Luckypatch** [weihuoya/citra#353]
Very lag after i upgrade to Android 11
Please solve the problem 😭
I use mi 9t pro

**Comment by weihuoya** [comment]
reset settings, delete shader cache

**Comment by Luckypatch** [comment]
I've tried but it still doesn't work

**Comment by TheOG00** [comment]
@Luckypatch and11 is known as the poorest hardware on emulators especially citra mmj and dolphin mmj
