### ISSUE TITLE
Bad performance in latest update

### ISSUE THREAD

**Issue by some1onLSD** [weihuoya/citra#355]
Hello weihuoya,
after the latest update of 06/07/2021 the app performance just worsened in every game there is, the only thing that changed now is the emulator doesn't have no more FPS drops.
I am grateful for your work, keep it up.

**Comment by TheOG00** [comment]
@weihuoya 
Tested
-One piece ultimated cruise 1 & 2
-Inazuma eleven go 2 and go 3 galaxy
-Youkai watch 1
-Shin megami tensei 4 Apocalypse 
-Dragon ball fusion
They run smoothly 

But other games like
-Pokémon ruby and moon
-Loz link btw words
-Attack on titanz 1&2
-Dragon ball ultimate mission x
- super mario 3d land
ect......are getting slower 
idk why!!
Luigi mansion 2 doesn't run at all😂

**Comment by joyful-cambion** [comment]
Oh, I see now I've only tested the pokemon games because that's what I'm only interested with, thanks that was helpful I'll try playing those

**Comment by CyberBlueCodes** [comment]
@joyful-cambion @TheOG00 I have tried playing:
Pokemon X 
Pokemon Y
Animal crossing New leaf
And Minecraft for 3ds
And it all went as smooth as ice(not totally had some 1 second stucking in high performance animation)

Actually....I had I pretty good processer 

But at first I had installed the official build from play store(I am on android 11) it was not at all smooth, then I saw something that Citra mmj had multiplayer so I downloaded it, with multiplayer I got free performance, it's pretty fast then the official build.

Thankyou @weihouya and the Citra Mmj team(I am not sure that, that exists) keep up the good work.

**Comment by CyberBlueCodes** [comment]
And can anyone answer #359 for me

**Comment by Chetanbaba** [comment]
Mine in black screen on pokmeon x and omega ruby . Ultra sun is opening but it is lagging toooo much . My all games used to run at 100% speed but now it dosent open it just happened randomly 3 days ago

**Comment by TheOG00** [comment]
@CyberBlueCodes mmj is for medium range cpu so yur phone doesn't count😂

**Comment by CyberBlueCodes** [comment]
@TheOG00 I know but I am just telling that this si better than the official build

**Comment by CyberBlueCodes** [comment]
And I wish @weihuoya makes a ds emu with multiplayer for Android (I know there's a melon ds android port but multiplayer doesn't quite work)

**Comment by CyberBlueCodes** [comment]
@TheOG00 so can u suggest me a not very expensive phone compatible with citra like with gles3.2+ or something, like under ₹15,000 inr (i.e 201.54 usd)
