### ISSUE TITLE
errors with the CPP files.

### ISSUE THREAD

**Issue by Gamer64ytb** [weihuoya/citra#356]
hi, i'm having these problems compiling the source code:

C:\Users\user\Downloads\Citra\citra\src\video_core\renderer_opengl\gl_rasterizer.cpp:453:19: error: no member named 'CleanUp' in 'OpenGL::RasterizerCacheOpenGL'

I could fix this error by removing the line, but i get this error later:

C:\Users\user\Downloads\Citra\citra\src\core\cache_file.cpp:3:10: fatal error: 'minilzo.h' file not found

I also tried eliminating that line, but it gave me more errors still, and it was not useful eliminate the indicated cpp either.

**Comment by TheOG00** [comment]
@Gamer64ytb yu think elimination will fix the build

**Comment by CyberBlueCodes** [comment]
I guess it won't work by just removing that line u can try reinstalling Citra and make sure ur on the latest stable release.

**Comment by weihuoya** [comment]
https://github.com/weihuoya/citra/blob/master/externals/minilzo/minilzo.h

**Comment by Gamer64ytb** [comment]
now I get this error:

ld: error: duplicate symbol: cubeb_jni_get_context_instance()
