### ISSUE TITLE
[Feature Request]Double users

### ISSUE THREAD

**Issue by CyberBlueCodes** [weihuoya/citra#358]
Note this request is for Citra android

So i was thinking that u guys could introduce a feature in which u can change users and if that isn't possible can u tell me in which files did u set that the save directory should be " /storage/emulated/0/citra-emu" I will change that and recompile if it is ok.

**Comment by TheOG00** [comment]
@CyberBlueCodes 
Save directory
![Screenshot_20210713-221442~3](https://user-images.githubusercontent.com/84327903/125525978-0082224a-8088-4982-8af8-740f98bc17fd.png)
Your question is not an issue brother

**Comment by CyberBlueCodes** [comment]
No you don't understand I just want to know where did u declare the save directory?in which file?

**Comment by CyberBlueCodes** [comment]
I just want to change that from citra-emu to citra-emu-clone

**Comment by TheOG00** [comment]
Searching for that in the source code is not easy😳

**Comment by CyberBlueCodes** [comment]
Never mind found it it's in src/commons/common_paths.h

**Comment by CyberBlueCodes** [comment]
Then shall I close this issue? And also can u answer #359
