### ISSUE TITLE
How do I complie this for Android?

### ISSUE THREAD

**Issue by CyberBlueCodes** [weihuoya/citra#359]
As the question says how do I compile this for Android. I don't want to use the apk directly but want to tweak some stuff and recompile how do I do that?

**Comment by CyberBlueCodes** [comment]
Could anybody compile this for me

**Comment by Muzika** [comment]
You can't. Code is incomplete.

**Comment by CyberBlueCodes** [comment]
Which part?

**Comment by CyberBlueCodes** [comment]
Then how does @weihuoya does it

**Comment by Muzika** [comment]
His copy is different than the one in github. Some files are outdated, unchanged and even the sub modules are incomplete.

My guess is that he hasn't committed some older commits.

**Comment by weihuoya** [comment]
any complie error log?

**Comment by CyberBlueCodes** [comment]
I couldn't compile it @weihuoya

**Comment by CyberBlueCodes** [comment]
Too many errors even before compiling(with AIDE)

**Comment by CyberBlueCodes** [comment]
Can I compile for Android using cmake?

**Comment by weihuoya** [comment]
If you're not familiar with the Android Studio, search for tutorials.

**Comment by CyberBlueCodes** [comment]
Ok I'll try after I go home
