### ISSUE TITLE
Black screen and excessive lag

### ISSUE THREAD

**Issue by Chetanbaba** [weihuoya/citra#361]
I have realme 7 with mediatek g95 and 6gb ram . Whenever i open citra mmj black screen comes . I have three games pokemkmx , ultra sun and omega ruby , pokemon omega ruby and x are facing black screen . But when i open ultra sun it open but it speed goes to 2% and 1fps i dont know why . All the games were running at 100% speed and 30 fps 1 day ago but today morning Nothin is working please helppppp. Its in the latest version and i also downloaded older version they are also not working

@weihuoya please helppp

**Comment by Chetanbaba** [comment]
Please helpppp

**Comment by weihuoya** [comment]
Reset settings, turn off cheat codes, clear shader cache

**Comment by Chetanbaba** [comment]
Oh god 😊😊😊😊😊 thanks it worked . thank you so much
