### ISSUE TITLE
Add Skip Slow Draw by Default option

### ISSUE THREAD

**Issue by wmarquesbr** [weihuoya/citra#362]
Everytime i play Pokemon Sun and Moon or Ultra Sun and Moon, the game there's a lot of lags when i use z-move or when i battle to totem Pokemon and it has the "fire" particles, or even when i have a double battle it happens too, i genuinely enable this function to fix the lags, after close emulator this function disable automatically, i want to suggest a small implementation on this which doesn't need to enabling this function every time i join a game.

**Comment by weihuoya** [comment]
skip slow draw isn't recommend for normal plays.
