### ISSUE TITLE
Opening lines of communication (Dolphin MMJ - MMJR)

### ISSUE THREAD

**Issue by Bankaimaster999** [weihuoya/citra#363]
您好，我正在尝试与您建立联系。

再次感谢您为 Dolphin MMJ 的开发所做的一切，我希望您能回答有关 Dolphin MMJ 存储库的一些开发问题。

有人在 Discord 上以你的名义联系了我，所以我在这里确认确实是你，而不是冒充你的巨魔。

----------------------------------------

Hello, I am trying to establish contact with you.

Thank you again for all you have done for the development of Dolphin MMJ, and I hope you can answer some development questions about the Dolphin MMJ repository.

Someone contacted me in your name on Discord, so I am here to confirm that it is indeed you, not a troll impersonating you.

**Comment by SmileFacey** [comment]
... 
![IMG_20210719_190631.jpg](https://user-images.githubusercontent.com/83503937/126199386-f1c5b8eb-0f61-4ded-8d95-bc5d4558752b.jpg)

**Comment by cyemac1995** [comment]
Hello there sir, can I request a new feature for the emulator? Can you make classic controller's right joystick mode as drag to be emulated on touchscreen on android device? Like you did on IR pointer mode > drag.

**Comment by cyemac1995** [comment]
Adding this feature on your revamp build would be great for Call of Duty gamers. Thank you.

**Comment by SmileFacey** [comment]
> Hello there sir, can I request a new feature for the emulator? Can you make classic controller's right joystick mode as drag to be emulated on touchscreen on android device? Like you did on IR pointer mode > drag. 

Just enable Joystick emulation and select IR

**Comment by weihuoya** [comment]
NOT ME, BE CAREFUL!
