### ISSUE TITLE
Tales of the abyss not working anymore

### ISSUE THREAD

**Issue by Resurrekt** [weihuoya/citra#366]
Tales of the abyss is not working anymore for the latest build. the last build that tales of the abyss works is 20201201 or december 1 2020 build. pls make tales of the abyss work again for the latest build. Thank you

**Comment by weihuoya** [comment]
Reset settings if it's not working.
https://github.com/weihuoya/citra/releases/download/20210706/Citra_MMJ_20210706.apk

**Comment by Resurrekt** [comment]
already tried resetting many time but still have no luck..

**Comment by weihuoya** [comment]
backup `citra-emu` directory and delete it, and try again.

**Comment by Resurrekt** [comment]
thank you for the instructions but still it doesnt work :(

**Comment by weihuoya** [comment]
don't known why, it works on my phone, Citra_MMJ_20210706

**Comment by Resurrekt** [comment]
my two friends have different mobile and the build later than dec 1 2020 is
not working with tales of abyss :( but working in dec 1 2020 build :( btw
thanks for the response.
