### ISSUE TITLE
BUG With Game Homescreen shortcuts
===========

### ISSUE THREAD

**Issue by AnSmileyFace** [weihuoya/citra#368]
I found a bug with the homescreen shortcuts
----------------------------------------------------------------
If Citra MMJ Is on Memory everything will work fine 
------------------------------------------------------------
But if Citra MMJ isn't on memory the touchscreen buttons layout will be set to default positions
And the Citra MMJ theme too will be set to default
--------------------------------------------------------------
If you don't understand what I'm saying here's a video showcasing the bug 
https://user-images.githubusercontent.com/83503937/126700934-c6e32065-71b0-454b-8f42-87a8b6b1c565.mp4

**Comment by weihuoya** [comment]
https://github.com/weihuoya/citra/releases/download/20210723/Citra_MMJ_20210723.apk
