### ISSUE TITLE
Mediatek performance has been worst in some games,citra 20210723

### ISSUE THREAD

**Issue by ajay9634** [weihuoya/citra#369]

**Comment by ajay9634** [comment]
Tested game on 1x and 2x-

Legend of Zelda a link between the world , fantasy life,Shante and pirates curse


Result- performance down than citra mmj previous version ,even on 1x

**Comment by weihuoya** [comment]
reset settings

**Comment by ajay9634** [comment]
Nothing changed,
Before ,fantasy life was running 1x 30 fps ,but now 21-23 fps.


Before, fantasy life was running 2x 21-23 fps ,now it's same 21-23

I think, fps drop in 1x resolution,not in 2x
