### ISSUE TITLE
Feat: SaveStates

### ISSUE THREAD

**Issue by michaelphagen** [weihuoya/citra#37]
Would it be possible to implement savestates into the mmj releases? I know they've been in the main project for a while but there doesn't seem to be a menu option for it in the mmj version.

**Comment by AndresNorm** [comment]
Because currently the official Citra 4 android are at closed door development...
You should wait for it to release..
So that weihouya can implement it to his mmj

Currently the savestate on Citra 4 Android are being worked upon and they're ready to release it after that.

**Comment by michaelphagen** [comment]
I thought this fork was based on the current version or a pretty recent version of Citra, since it has New 3DS Support. I was curious if it was mainly a UI issue, since it looks like the most recent pull of the public citra code is from March 26th, and that source should have savestate support. 

Admittedly I'm not that familiar with making android apps or Java, and I'm sure it's much more difficult than I made it sound, just curious if it's possible.

**Comment by AndresNorm** [comment]
Well yes, based on latest Version but (based on PC build)
As you can see Citra for Android have been done from the scratch...

But dont worry though savestate will come after the official release of it 😊
