### ISSUE TITLE
Keeps crashing after selecting language in PokemonY/Omega Ruby, assumably SM/USUM as well

### ISSUE THREAD

**Issue by Deltanium** [weihuoya/citra#371]
So, i know this is a issue w/ the newer version because it doesn't crash on the 20210316

But, It loads into the game, I select the language option (i've tried all languages, same results) and then the message saying "Citra has closed", But when I try it on the 20210316 version, I notice it works fine, Obviously lots of lag and everything, but the newer version just doesn't load

My assumption is compatibility broke along the way in the updates somehow 

Edit: Messed w/ settings, noticed it happened with the hardware shader, disabling that gives me less than optimal performance, but allows me to load into the game

Specs:
Device: Moqi i7s
Android 8.1 Oreo
6GB ram
Snapdragon 710 Octa-core 1024MHz CPU
SDM710 CPU type
Qualcomm Adreno 616 6.50 MHz Single core GPU

**Comment by weihuoya** [comment]
reset settings

**Comment by Deltanium** [comment]
> 
> 
> reset settings

Tried it, also tried reinstalling, Is there any folders that are created that i might have to delete that have settings that i can't delete through the app?

**Comment by weihuoya** [comment]
delete 'citra-emu'

**Comment by Deltanium** [comment]
> 
> 
> delete 'citra-emu'

Still same issue, I just notice when i disable hardware shader it works, just reallyt slow emulation.

**Comment by Tappy-tech** [comment]
> > delete 'citra-emu'
> 
> Still same issue, I just notice when i disable hardware shader it works, just reallyt slow emulation.

So why won't just try with Hardware Shader being off, then reset the game with newer settings after saving?

**Comment by Deltanium** [comment]
> 
> 
> > > delete 'citra-emu'
> > 
> > 
> > Still same issue, I just notice when i disable hardware shader it works, just reallyt slow emulation.
> 
> So why won't just try with Hardware Shader being off, then reset the game with newer settings after saving?

Also tried that.

**Comment by Tappy-tech** [comment]
> 
> Also tried that.

I could try creating a save file for you, but you have to answer the questionary first.

1. Which Pokémon Games?
2. Are you a boy or a girl?
3. Which skin colour? (That you can choose in X/Y and S/M/US/UM)
4. Which hair colour? (That you can choose in X/Y and S/M/US/UM
5. Which name shall I enter for you?
