### ISSUE TITLE
Pokemon-Amie (Attach video)

### ISSUE THREAD

**Issue by Jidogwan** [weihuoya/citra#377]
MMJ Citra Mobile cannot touch the Pokemon during the Pokemon-Amie.
Please modify the touch relatedly.
[Pokemon X
Pokemon Y
Pokemon Omega Ruby
Pokemon Alpha Sapphire]

![1623579459991](https://user-images.githubusercontent.com/83328842/122900554-c2f7d680-d387-11eb-9083-012142312757.jpg)

![1623579464251](https://user-images.githubusercontent.com/83328842/122900564-c4c19a00-d387-11eb-83d2-a0e9c1cf91f8.jpg)

can't touch pokemon

The Pokemon Ultra version works fine, but the Pokemon Alpha Sapphire version doesn't.

video link:
https://linksharing.samsungcloud.com/jRTEsjo0SdPs

**Comment by Gamemulatorer** [comment]
You already reported this many many times wtf 😒 https://github.com/weihuoya/citra/issues/336

**Comment by Jidogwan** [comment]
> 이미 여러 번 신고하셨습니다. 😒 #336

Sorry..🥺

**Comment by ajay9634** [comment]
Use cheat code, then no need care of Pokemon

**Comment by CyberBlueCodes** [comment]
Bro that's not the emulators fault(I guess) cause the game is taking the input that your touching the screen but the Pokemon isn't reacting don't no why

**Comment by Jidogwan** [comment]
> 형 그건 에뮬레이터의 잘못이 아닙니다(내 생각에는) 게임이 화면을 만지고 있지만 포켓몬이 반응하지 않는다는 입력을 받고 있기 때문입니다.

I'd like to think so, but... Ultra Sun Moon works well.

**Comment by Jidogwan** [comment]
> Bro that's not the emulator's fault(I guess) cause the game is taking the input that your touching the screen but the Pokemon isn't reacting don't no why

I'd like to think so, but... Ultra Sun Moon works well.
