### ISSUE TITLE
Tales of abyss crash upon opening

### ISSUE THREAD

**Issue by Patrickz22** [weihuoya/citra#378]
I remembered playing tales of abyss last year but now i downloaded the lastest version and try to play it again but it always crash.. anything to do on settings? Or it is not playable on the latest version?

**Comment by Manamaster** [comment]
In my case the games works just fine, the only exception is a black vertical line on the upper screen. 
![Screenshot_2021-08-02-00-45-53-654_org citra emu](https://user-images.githubusercontent.com/28676625/127810199-68811638-fe6d-4939-b61a-37739cb5580c.jpg)
On the official Citra the game will not work, both screens are black, while the sound effects and music play in the background.

**Comment by Patrickz22** [comment]
Yeah i remembered that lines too and it cuts the screen a little but thats not a big problem anyway, but how did you manage to make it work? Are you using citra mmj latest version?

**Comment by weihuoya** [comment]
https://github.com/weihuoya/citra/releases/download/20210806/Citra_MMJ_20210806.apk

**Comment by Manamaster** [comment]
![Screenshot_2021-08-08-23-29-33-357_org citra emu](https://user-images.githubusercontent.com/28676625/128660874-4e52eefe-c046-41ee-8611-d4f064e1311e.jpg)
Not only does the game run beautifully, but the gameplay is smooth.
There are minor visual glitches in menus, but everything else is wonderful. 
You are awesome.
