### ISSUE TITLE
Poor And Unstable 9-15 FPS with Mediatek Helio G35

### ISSUE THREAD

**Issue by XENOS-GO** [weihuoya/citra#394]

**Comment by TheOG00** [comment]
Ammmm still slow yes i admit that
In Snapdragon 6xx too

**Comment by Gamemulatorer** [comment]
Upgrade your phone is the best solution

**Comment by Pokemetti** [comment]
You shouldn't expect much more from that processor. Helio G60 and upwards should be kinda playable though.
