### ISSUE TITLE
0421/0423 build, fps drops problem

### ISSUE THREAD

**Issue by mrkytzn** [weihuoya/citra#40]
Hello thank you for your hard work in this project. There has been some fps drops on a certain game on the 0421 and 0423 update. Playing pokemon ultra moon, whilst fps on open world adventure is okay, fps drops when you start a pokemon battle. While there are no said issues on the 0415 build.

**Comment by Andy1091** [comment]
Same Problem Bad Performance 0415 is good 

0421 and 23 suckz
