### ISSUE TITLE
Update The Emulator God Damn It

### ISSUE THREAD

**Issue by RonzelIGuess** [weihuoya/citra#401]

**Comment by Tappy-tech** [comment]
Everything takes time. Nothing can happen in one second. Like a message being sent or food being cooked.

**Comment by ajay9634** [comment]
Maybe weihuoya has gone to vacation

**Comment by RonzelIGuess** [comment]
> Everything takes time. Nothing can happen in one second. Like a message being sent or food being cooked. You know, you should also never judge someone, until you get to know them. If you think making emulators is easy, then try making one.

But u something should happen in a month for frick sake my pocket money is always given to then every month lol

**Comment by Lxoric** [comment]
> > Everything takes time. Nothing can happen in one second. Like a message being sent or food being cooked. You know, you should also never judge someone, until you get to know them. If you think making emulators is easy, then try making one.
> 
> But something should happen in a month for frick sake my pocket money is always given to them every month lol
Lmao. You're donating to official citra if that's the case not to weihouya. Lol.

**Comment by RonzelIGuess** [comment]
Ohh so the patrion he links to every update isn't his? Ohh ok still maybe my 10$ will help idk lol but seriously dont take my comments seriously XD

**Comment by theOG1** [comment]
@RonzelIGuess yeah yu are paying the wrong dev lol

**Comment by ajay9634** [comment]
Close this
