### ISSUE TITLE
Bravely default 3ds randomly freezes

### ISSUE THREAD

**Issue by JaegerSupreem** [weihuoya/citra#407]
Bravely default randomly freezes and stops working, with fps stuck at 0, vps varying, spd also varying(can be seen in the below screenshot)
So far I'm 5 hours 24 minutes into the game and it has frozen 4 times(all recently as of twice yesterday and twice today). First the sound stops all of a sudden, game continues to run for 1-2 second and then fully freezes, sometimes when entering a placeor exiting it goes black screen, sometimes in combat it freezes as if a still image and sometimes freezes when exploring (attached 2 screenshots).

Device being used:
Samsung Galaxy M51 
Running android 11
Has Snapdragon 730g and 6GB of RAM
Edit(adding more details): running at 2x resolution with linear filtering on.

No active programs running apart from citra mmj, citra mmj of tag  20210820(latest version at the moment) is being used. Didn't used to have any problem in the past and this has started very recently, maybe one of the latest version could have some bug making this issue.
![Screenshot_20211014-135139](https://user-images.githubusercontent.com/49075363/137302884-c6f4ab7a-4865-4593-ab3c-993cbced72f4.jpg)
![Screenshot_20211014-160219](https://user-images.githubusercontent.com/49075363/137302904-82128df0-00ea-4d50-b65a-bdd542b647de.jpg)

**Comment by akasha593** [comment]
in my experience playing persona q and q2 these random freeze easily fix by disabling the "new 3ds mode" in setting.

**Comment by JaegerSupreem** [comment]
> 

Thanks! It seems to have worked, 45mins no crash
