### ISSUE TITLE
Pokemon X crash!

### ISSUE THREAD

**Issue by Abhijit0010** [weihuoya/citra#410]
Pokemon X crashes when is try to load it in Citra mmj latest built. I've attached a video to show my problem. My device is Vivo Y95. But Pokemon Moon works flawlessly. Please help.

https://user-images.githubusercontent.com/93502023/139619681-9c6b4918-1a38-41bc-a053-e36847b4355c.mp4

**Comment by Balachandarsmr** [comment]
I am using Citra_MMJ_20210204.apk it's working without any issues. After that versions it had problems like crashing, slow gameplay

**Comment by Abhijit0010** [comment]
Thanks for the info.

**Comment by Abhijit0010** [comment]
Any other suggestions?
