### ISSUE TITLE
Add to fdroid

### ISSUE THREAD

**Issue by dennis90a** [weihuoya/citra#420]
https://f-droid.org/ is a FOSS only app repository for android devices.
Adding this app there would be really nice.

**Comment by dennis90a** [comment]
Fastlane needa to be implemented to put this app on f-droid

**Comment by aecarvalho** [comment]
It's a suggestion, not an issue, probably do it as a comment on the appropriate code related to builds

**Comment by IzzySoft** [comment]
It's more than just a suggestion – it's a strong recommendation. Without Fastlane, there won't be any screenshots – and each change to the app's description would require opening another merge request at fdroiddata to get it into the listings. With fastlane, the author has full control on how the app is presented.

@weihuoya you didn't say why you closed this issue, so may I kindly ask? Are you opposed to have your app listed with F-Droid, or was the closure rather an incident?
