### ISSUE TITLE
Please Explain Why No Update

### ISSUE THREAD

**Issue by RonzelIGuess** [weihuoya/citra#423]
Hi. This has been a mystery for my head for quite sometime now. What happened that you stopped updating the emulator. Is it a mental issue? Are you tired? Or your working on it just not as fast. Please respond.

**Comment by aecarvalho** [comment]
Psychological, not mental you dummy XD

It's a free project, let the developer do it as he finds it convenient. If you have something which is broken, post that as an issue.

**Comment by RonzelIGuess** [comment]
> Psychological, not mental you dummy XD
> 
> It's a free project, let the developer do it as he finds it convenient. If you have something which is broken, post that as an issue.

Chill u fuckhead

**Comment by aecarvalho** [comment]
> > Psychological, not mental you dummy XD
> > It's a free project, let the developer do it as he finds it convenient. If you have something which is broken, post that as an issue.
> 
> Chill u fuckhead

Fuck off nutjob

**Comment by RonzelIGuess** [comment]
He is back babyyy
