### ISSUE TITLE
FMV Hack on New 3DS

### ISSUE THREAD

**Issue by some1onLSD** [weihuoya/citra#425]
Hello, been playing Inazuma Eleven Go shadow on this wonderful emulator and it is working kinda decent "Off better than Inazuma Eleven 3 team ogre" but it has the same issue as the last one which is CRAZY Audio Stuttering but fortunately on this one it can be fixed when enabling "FMV Hack" but this gets you to around 15FPS, on the other hand when changing to New 3Ds mode and activating "FMV Hack" the FPS gets better to around 30FPS but the audio stuttering doesn't get much better, now this is weird because whenever I enable "FMV Hack" on new 3ds option on any game audio stuttering will always be present. 
Anyway the conclusion is I think there is an issue with this combination FMV Hack + New 3DS.

**Comment by JoaquimSilva123** [comment]
Pb
