### ISSUE TITLE
Pokemon game's are slow in Snapdragon

### ISSUE THREAD

**Issue by ajay9634** [weihuoya/citra#431]
Pokemon game's (pokemon x, y) are running full speed in citra official, so please fix this. 

I am using poco m2 pro (720g)

**Comment by Tappy-tech** [comment]
Just use resolution hack.

**Comment by ajay9634** [comment]
This is not a permanent fix

> Just use resolution hack.

**Comment by Tappy-tech** [comment]
> This is not a permanent fix
> 
> > Just use resolution hack.

It's either that you will have more speed or run at low speed. In gen 7 games, you can use no outlines cheat to fix the slowdown.
