### ISSUE TITLE
Inazuma Eleven Go black screen

### ISSUE THREAD

**Issue by some1onLSD** [weihuoya/citra#453]
After last update 11/02/2022 the Top screen displays nothing in "Inazuma Eleven Go" but when using the old 27/01/2022 version it works fine.
--- 

![Screenshot_20220211-122921_Citra](https://user-images.githubusercontent.com/74503778/153584346-fff92e32-f489-47c2-8cc5-65d717289346.png)

**Comment by Perritys** [comment]
It also happens with go 2 and go galaxy
