### ISSUE TITLE
Screen Flickering

### ISSUE THREAD

**Issue by Sastran0** [weihuoya/citra#454]
Screen flickering in Zelda Ocarina of Time 3D & Zelda Majora's Mask 3D.

Device: Galaxy Fold 3
CPU: SD 888
GPU: Adreno 660
RAM: 12 GB
Citra Build: 20220210 & 20220211

**Comment by Skidaddlerow** [comment]
Same problem but in smash 3ds :(

**Comment by Perritys** [comment]
Try raising the resolution and then lowering it back to the resolution you had set, it solved that for me.
