### ISSUE TITLE
Flickering screen in smash 3ds

### ISSUE THREAD

**Issue by Skidaddlerow** [weihuoya/citra#455]
https://user-images.githubusercontent.com/89689239/153590654-65f63fe0-d7e4-4619-9ccf-f90f895cb8d2.mp4

**Comment by Skidaddlerow** [comment]
Flickering screen on Xiaomi Mi 9T

**Comment by Tappy-tech** [comment]
I have it too, but it is fixed by upscaling resolution, and it is in another format:

Uploading Record_2022-02-11-22-04-45_53c01e3b6443161a8deff0f1f7f140ba.mp4…
