### ISSUE TITLE
In app dark mode theme.

### ISSUE THREAD

**Issue by DavidAriyan** [weihuoya/citra#456]
The app does support dark mode and even make the on screen controller become black.
But it need force dark mode from the phone developer option. Will be nice if it available in the app itself. Since there is none available in the theme. Also the "select" button doesn't have outline like all other button. It need fix. Talk about perfection.

**Comment by jakedowns** [comment]
i might be able to look into this

**Comment by DavidAriyan** [comment]
> i might be able to look into this

Please do.
