### ISSUE TITLE
Graphic issue on pokemon sun and moon

### ISSUE THREAD

**Issue by Mehmuhmai** [weihuoya/citra#46]
Citra_MMJ_20200428
Asus zenfone max m1 pro
SDM636
14nm Qualcomm® Snapdragon™
636 Mobile Platform
1.54X
CPU performance improvement
over SDM6253
2.71X
CPU performance improvement
over ZenFone 4 Max Pro1
The characters on pokemon moon and sun keeps flickering but after selecting separate shader the flickering stop but a new issue have occured all the road have become black and if enter inside a cave the walls of the cave have becom invisible
![Screenshot_20200429-011842](https://user-images.githubusercontent.com/64305746/80532158-54083300-89b9-11ea-9ead-9a728f8432ff.png)
![Screenshot_20200429-011921](https://user-images.githubusercontent.com/64305746/80532182-5f5b5e80-89b9-11ea-8276-218241409709.png)
![Screenshot_20200429-012125](https://user-images.githubusercontent.com/64305746/80532197-67b39980-89b9-11ea-9c5f-977abd9ece4b.png)

**Comment by OdinDxD** [comment]
The only way to get the full Pokémon sun moon experience is by turning on the Accurate Multiplication and Seperable shader, and turning off the Texture load hack, custom texture and preload custom texture.

**Comment by Mehmuhmai** [comment]
I did all of what u said it still didnt work

**Comment by adiiiis** [comment]
Hey I was having the same issue, u can put this cheat 
[60FPS v1.0]
*citra_enabled
D3000000 30000000
23F67FE9 00000000
D2000000 00000000
And use the sperate shader options. Btw turning off hardware shadeer options makes it slow, like unplayable slow.

**Comment by adiiiis** [comment]
*Hardware shader

**Comment by OdinDxD** [comment]
I didn't said about turning off hardware shader
