### ISSUE TITLE
Please add a Toggle for touch screen buttons

### ISSUE THREAD

**Issue by NeedALife0451** [weihuoya/citra#460]
Would you add a button toggle. Not all buttons are needed for all games and such a lot of screen is taken up. Also a way to individually increase the size of some buttons and decrease others would help a lot dealing with multiple games and how they handle the screens

DraStic is a DS emulator with an interesting approach to DS ui and dealing with all the DS features on the fly by adding a button on screen that opens up a quick menu to things like screen swapping and disabling the touch screen

**Comment by Tappy-tech** [comment]
There's already an option to resize buttons.

**Comment by NeedALife0451** [comment]
Resize individually not all buttons in unison is what I meant.

**Comment by NeedALife0451** [comment]
Thank you man, just saw the newest update, appreciate you

**Comment by TheOG00** [comment]
added
just click on the button and it will turn red ,it means the button will not showing up
@weihuoya solved by the latest build

**Comment by COca-CO-la** [comment]
> There's already an option to resize buttons. A similiar thing about "Button toggle" also exists. It is Combo Key.

Sorry for bothering, where's the option for resizing buttons? I just can't find it.
And do you have any idea about how to make themes for this emu?
