### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by Perritys** [weihuoya/citra#464]
Hi, does anyone know how I can transfer my Citra mmj games to the Storage Access version?

**Comment by Perritys** [comment]
Thanks for the help,the issue is this,I didn't have the version with storage access and I installed it and it won't let me copy the smdc folder to the org.citra-emu folder inside the Android folder on Android 11.

**Comment by jsiwjddkoqa** [comment]
use ZArchiever mate,download it on playstore to access android folder

**Comment by Perritys** [comment]
It's already solved, in the end I copied and pasted them with the pc, but thanks for the help.

**Comment by ajay9634** [comment]
Now close this
