### ISSUE TITLE
Mhxx cheat code list crashes on MMJ 20220214 version

### ISSUE THREAD

**Issue by AquillaAzure** [weihuoya/citra#466]
I am using citra mmj the non-storage access on Note 20 ultra with Citra running on cpu graphics

when I updated to the newest version the game suddenly crashes when I try to view the cheat codes but the cheats does still work I just cannot view it to enable and disable in app only in text editor.

When I deleted the cheat to try and refresh it and copy past, I could not save the new text file and it also restarts the emulator if I try to edit the cheats in the cheat editor

I downgraded to 20220211 version which worked fine for me

**Comment by jsiwjddkoqa** [comment]
mine works fine,try using storage acces ver if un on android 11 and up

**Comment by AquillaAzure** [comment]
The new mmj 20220216 actually just fixed the problem. But also thank you.
