### ISSUE TITLE
Graphical glitch with Fennekin face textures in Pokémon XY

### ISSUE THREAD

**Issue by Tappy-tech** [weihuoya/citra#469]
![Screenshot_2022-02-19-01-11-16-67_f9ee0578fe1cc94de7482bd41accb329](https://user-images.githubusercontent.com/72254437/154768289-b395c78a-f6a9-4aef-904d-ec1e8b566197.jpg)
Original
![Screenshot_2022-02-19-01-08-08-11_53c01e3b6443161a8deff0f1f7f140ba](https://user-images.githubusercontent.com/72254437/154768291-5e8d2971-e06e-4cfd-bd73-7a2198eb8ea3.jpg)
With resolution hack or without no outlines cheat
![Screenshot_2022-02-19-01-05-18-90_53c01e3b6443161a8deff0f1f7f140ba](https://user-images.githubusercontent.com/72254437/154768293-b9230b40-1c34-40d2-9d72-f1343ec62ce1.jpg)
Without resolution hack

This happens only after sending out your own Pokémon.

**Comment by weihuoya** [comment]
is latest version fixed it?

**Comment by Tappy-tech** [comment]
> is latest version fixed it?

No.
