### ISSUE TITLE
Game crashes after enabling Hide Input Buttons (Happens with every game)

### ISSUE THREAD

**Issue by Tappy-tech** [weihuoya/citra#470]
https://user-images.githubusercontent.com/72254437/154790621-183b3111-6745-406c-8151-c510eb6d82d2.mp4

**Comment by jsiwjddkoqa** [comment]
how do you didnt get flickering when recording pokemon games btw?

**Comment by Tappy-tech** [comment]
> how do you didnt get flickering when recording pokemon games btw?

I'm using my own device's record, I guess. Even when I got hands on Citra MMJ year ago, I didn't had flickering issues.

**Comment by jsiwjddkoqa** [comment]
i see

**Comment by weihuoya** [comment]
mali gpu doesn't get flickering when recording.
