### ISSUE TITLE
How is it possible to save cheats with latest build?

### ISSUE THREAD

**Issue by Tappy-tech** [weihuoya/citra#471]
https://user-images.githubusercontent.com/72254437/154790703-74a3346e-22f9-46ec-9d01-30420987d0a7.mp4

**Comment by weihuoya** [comment]
it will be auto saved. there maybe some error, attach cheat file please, let me check it out

**Comment by Tappy-tech** [comment]
I'm not sure how attaching cheat files can help, but here:
[cheats.zip](https://github.com/weihuoya/citra/files/8102292/cheats.zip)

**Comment by weihuoya** [comment]
you click cancel button, and it's why doesn't save cheat.

**Comment by Tappy-tech** [comment]
And how can I save cheats, if there is no save button???

**Comment by jsiwjddkoqa** [comment]
just select/tap what cheats u wants then press back not cancel
