### ISSUE TITLE
[suggestion] Amiibo

### ISSUE THREAD

**Issue by mrdratik** [weihuoya/citra#473]
Why is it not possible to use amiibo in MMJ? At the same time, in the emulator directory on the memory card there is even a folder called amiibo... But there is no function in the menu. Please add the ability to use amiibo files :(

**Comment by Tappy-tech** [comment]
There is already amiibo support implemented, but you can't remove amiibo.

**Comment by mrdratik** [comment]
> There is already amiibo support implemented, but you can't remove amiibo.

How to use it? Just put the file in the amiibo folder?

**Comment by Tappy-tech** [comment]
> > There is already amiibo support implemented, but you can't remove amiibo.
> 
> How to use it? Just put the file in the amiibo folder?

Yes. When you will have to use, choose the needed file.

**Comment by mrdratik** [comment]
> > > There is already amiibo support implemented, but you can't remove amiibo.
> > 
> > 
> > How to use it? Just put the file in the amiibo folder?
> 
> Yes. When you will have to use, choose the needed file.

thx, but the interface still needs to be improved.
