### ISSUE TITLE
ZL ZR missing on 20220219??

### ISSUE THREAD

**Issue by AquillaAzure** [weihuoya/citra#474]
On mmj 20220219 I just installed the buttons looks great but the ZL and ZR buttons are not showing, I don't know where or how to put it back so I just reinstalled the earlier one. Is there a settings hidden for that??

**Comment by weihuoya** [comment]
Edit Buttons

**Comment by AquillaAzure** [comment]
I realized how, I just need to double tap, and realized the sensitivity was so strong that it moves whenever I touch, maybe add enable buttons instead??

But thank you
