### ISSUE TITLE
Problem with Storage Access on MIUI

### ISSUE THREAD

**Issue by occhep** [weihuoya/citra#478]
I've just installed the latest releases (20220221), but both of them couldn't let me select roms on sd card. The Storage Access version let me select files on sd card, but doesn't let me select folders, only files (when I selected them the app crashed). The other version on the other hand couldn't access sd card. I'm guessing this has something to do with MIUI's default file app. Is there a workaround for this or do I have to wait for a fix?

**Comment by alberto2098kl** [comment]
😂😂

**Comment by TheOG00** [comment]
@occhep 
rename another folder
mine work fine on miui 12.5.2

**Comment by occhep** [comment]
@TheOG00 
Which version do you use?

**Comment by Jaylee-novice** [comment]
Hi, all, the latest version of CITRA MMJ (25th Feb) was installled and I still have an issue. MIUI version is GLOBAL 12.5.9.
Please share your approach for the successful folder selection. I am utilzing MIUI file manager.

**Comment by occhep** [comment]
MIUI fixes confirmed. I can select SD Card folders now.
For the normal version, use the button to the right of the file path to navigate to SD Card (some file manager shows SD Card path).
For storage access version, select SD Card from left bar, then navigate to your game folder, and choose use this folder.
