### ISSUE TITLE
Citra 20200428 Caida Fps, lento zeldas.

### ISSUE THREAD

**Issue by CarlosF360** [weihuoya/citra#48]
Problemas.
Caída de Fps 
Va muy lento.
No se puede cambiar el lenguaje a español.

Samsung galaxy note 10 plus
Exynos 9825
Ram 12Gb

![20200428_171422](https://user-images.githubusercontent.com/64503182/80543049-c5bd8e00-8973-11ea-8d4b-12b36d54f10c.jpg)

**Comment by Genesiya** [comment]
En youtube busca... Hay un archivo q se llamaa nand q t pone directamente al español :)
