### ISSUE TITLE
Custom Textures issue

### ISSUE THREAD

**Issue by Deka710** [weihuoya/citra#483]
for some reason custom textures didn't work/loaded and glitched,
here are some screenshot :
without texture 
![Screenshot_2022-02-28-19-07-05-484_org citra emu](https://user-images.githubusercontent.com/97207704/155981504-1ba7ca99-c9c8-4c73-86ab-75d267b1795d.jpg)

with texture
![Screenshot_2022-02-28-19-05-19-122_org citra emu](https://user-images.githubusercontent.com/97207704/155981672-49d37f60-5d0d-4141-a5bb-2306f839d219.jpg)

as we can see the image above theres black glitch texture in the armor,this texture pack has been tested on citra pc and works fine.
(this is happen on Monster Hunter XX and Monster Hunter 4U)

**Comment by jsiwjddkoqa** [comment]
thanks for the hard work!!! its fixed now😆

**Comment by jsiwjddkoqa** [comment]
after testing the textures,most of them are works,but theres some textures turned into black color
![Screenshot_2022-06-10-20-18-10-664_org citra emu](https://user-images.githubusercontent.com/97207704/173075243-934a2c85-d4c3-43f5-b0f6-6c0c580ea1e3.jpg)
