### ISSUE TITLE
S22 Ultra (Exynos 2200) 

### ISSUE THREAD

**Issue by misiek685250** [weihuoya/citra#496]
On my S22 Ultra (Exynos version) it's unusable on my device. The problem is with lack of visibility (only black screen, with graphical glitches), and working sound in the background. Please add compatibility for that chipset

https://user-images.githubusercontent.com/70110823/159740957-0dba1478-50ed-44d1-b22b-6ec23fa22bdd.mp4

**Comment by Tappy-tech** [comment]
To fix this, Weihuoya needs to add vulcan video compile support, which you already know.
