### ISSUE TITLE
[FEATURE REQUEST] Ability to modify system user information 

### ISSUE THREAD

**Issue by omaralsharif** [weihuoya/citra#497]
Some games use system information to change specific game elements. It would be wonderful if we could modify the user information the system provides, such as the user name and birthday, as some games use that information aspects on specific game aspects. 

It would also be nice to modify the current set system date and time, but that's another feature altogether.

**Comment by Tappy-tech** [comment]
https://youtu.be/alDyeonsRXk
You need to use only System Settings to change user information.

**Comment by omaralsharif** [comment]
> https://youtu.be/alDyeonsRXk You need to use only System Settings to change user information.

Oh that's actually perfect! I didn't see that when I googled it lol

I'll close this issue
