### ISSUE TITLE
杂乱的软件名称

### ISSUE THREAD

**Issue by AngelofMe** [weihuoya/citra#504]
https://github.com/lemon32767/ccleste/releases/tag/v1.4.0
ccleste.3dsx
显示名：primary%3AGames%2FCitra%2Fccleste
正常应该是Classic Celeste这种形式才对吗？我使用Enhanced和Google Play版都没出现这种情况，不过比官方版好的一点就是文件里的wav音频正常加载了，而官方默认设置却不能开启音频

**Comment by weihuoya** [comment]
https://github.com/weihuoya/citra/releases/download/20220419/Citra_MMJ_20220419_StorageAccess.apk
