### ISSUE TITLE
Citra Mmj for Mediatek Helio G90T please Optimize

### ISSUE THREAD

**Issue by FahadZzz** [weihuoya/citra#51]
When citra emulator will be optimized for Mediatek processors?? 
My device is powerful Redmi note 8 pro but all i get is 8 to 9 FPS in Pokemon Games.
Nothing is working perfectly. It's too much lag in games. 
Please developer help us.

**Comment by Danielc117** [comment]
Super low fps and super laggy performance playing Pokemon X on my Redmi Note 8 PRO, in comparison the game is playable in Redmi Note 7 with SD 660. 

Please optimize it for mediatek processors, specifically for Helio G90T, pretty please! It is a powerfull processor. 

I'm dying for playing Pokemon Games with this emulator. 

Thank you

**Comment by jolomoto** [comment]
im using redmi note 5 pro with sd 636, updating pokemon x to ver. 1.5 may cause lag and fps drop idk why.

im playing it on official citra on v 1.0 its fine but the fps is below 25
