### ISSUE TITLE
Crash to menu on latest build

### ISSUE THREAD

**Issue by jsiwjddkoqa** [weihuoya/citra#511]
its happen when hide the input buttons then swipe down the screen,also cause random crashes on Monster Hunter XX
here the video :

https://user-images.githubusercontent.com/97207704/163913011-8437c21e-c253-4968-b211-b0f437f2ba70.mp4

**Comment by weihuoya** [comment]
thanks,
re-released,
https://github.com/weihuoya/citra/releases/download/20220419/Citra_MMJ_20220419.apk
