### ISSUE TITLE
Danball Senki Baku Boost and LBX (English version of Danball Senki Baku Boost) crash

### ISSUE THREAD

**Issue by SFZeroEXE** [weihuoya/citra#513]
The game crashes right after beating Destroyer during the cutscene and returns to the games menu

**Comment by SFZeroEXE** [comment]
[Screenrecorder-2022-04-19-18-14-13-144.zip](https://github.com/weihuoya/citra/files/8514747/Screenrecorder-2022-04-19-18-14-13-144.zip)

**Comment by weihuoya** [comment]
can ypu upload game save data?

**Comment by SFZeroEXE** [comment]
[00147100.zip](https://github.com/weihuoya/citra/files/12715772/00147100.zip)


> can you upload game save data? in `citra-emu/sdmc` directory


Sorry I just noticed you're reply anyway the issue is still present even on the newest versions

**Comment by weihuoya** [comment]
https://github.com/weihuoya/citra/releases/tag/20230926

**Comment by SFZeroEXE** [comment]
Thx it's working now

**Comment by SFZeroEXE** [comment]
@weihuoya 
[00147100 (1).zip](https://github.com/weihuoya/citra/files/12840419/00147100.1.zip)

Another crash during special attack cutscene here
