### ISSUE TITLE
Few questions about 2 latest updates.

### ISSUE THREAD

**Issue by Tappy-tech** [weihuoya/citra#515]
1. In weibo, Weihuoya wrote about multiplayer issues fix. If it's about joining multiplayer rooms, then I didn't had the issue (No storage access version). What does it mean?
2. There are hidden options since 20220419. Can someone explain what do they mean? (Y2r perform hack, Y2r event delay, disable clip coef, stream buffer hack, display transfer hack)
3. In 20220420 version, there was a change with fixing Pokémon display problems. However, when I checked Pokémon refresh in USUM again, I still have the flickering issue.

**Comment by weihuoya** [comment]
Y2r perform hack, Y2r event delay, disable clip coef, stream buffer hack, display transfer hack
just a few patch to make game playable

**Comment by weihuoya** [comment]
have a try
https://github.com/weihuoya/citra/releases/download/20220422/Citra_MMJ_20220422.apk

**Comment by Tappy-tech** [comment]
What about first one???

**Comment by Tappy-tech** [comment]
Anyways, the flickering issue wasn't fixed: 

https://user-images.githubusercontent.com/72254437/164707558-6ec7c963-5a66-4ee9-ac6a-9c31166a2bbf.mp4
