### ISSUE TITLE
black screen when encountered a pokemon

### ISSUE THREAD

**Issue by jsiwjddkoqa** [weihuoya/citra#516]
pokemon y,latest build :

https://user-images.githubusercontent.com/97207704/164478039-ebbb2eb6-e7db-4ea9-91d3-0c6c170c1db5.mp4
update : also force close issue on omega ruby when encountering a pokemon :
![Screenshot_2022-04-22-06-07-15-923_org citra emu](https://user-images.githubusercontent.com/97207704/164565556-29ba9790-a67a-45d1-a92e-f47c93388b8c.jpg)

**Comment by Tonildo23** [comment]
Same problem with Culdcept, i put Accurate mul on Fast and it worked.

**Comment by weihuoya** [comment]
have a try
https://github.com/weihuoya/citra/releases/download/20220422/Citra_MMJ_20220422.apk

**Comment by jsiwjddkoqa** [comment]
still black screen/freeze😭

Uploading Screenrecorder-2022-04-22-13-25-15-70 1.mp4…

**Comment by jsiwjddkoqa** [comment]
https://user-images.githubusercontent.com/97207704/164618056-ab54b547-366d-4517-93d4-7784dff81406.mp4

**Comment by weihuoya** [comment]
have a try, it must fix it
[app-release.zip](https://github.com/weihuoya/citra/files/8537784/app-release.zip)

**Comment by weihuoya** [comment]
re-released, have a try
https://github.com/weihuoya/citra/releases/download/20220422/Citra_MMJ_20220422.apk

**Comment by jsiwjddkoqa** [comment]
great!!!!,its fixed
