### ISSUE TITLE
Pokemon x issues

### ISSUE THREAD

**Issue by Nilo16** [weihuoya/citra#517]
Hello :D
I've been experiencing various dead freezes during loadings. When entering a house or a Pokemon Center, closing menus or getting into battles may freeze you locked on the transitioning loading screen. The only way to get around this, is closing the game an losing unsaved progress. I'm using a Poco X3 pro.

**Comment by weihuoya** [comment]
https://github.com/weihuoya/citra/releases/download/20220422/Citra_MMJ_20220422.apk
