### ISSUE TITLE
The savestates are missing!!

### ISSUE THREAD

**Issue by Frenky81** [weihuoya/citra#534]
Hi everyone !would anyone be able to explain to me why the developers have not yet implemented the savestates? playing without the ability to save progress is absurd! someone can explain to me if it is possible and how it is possible to save the game progress? thanks!

**Comment by Tappy-tech** [comment]
You don't even know how to save in-game, without save states? It's not an NES after all...

**Comment by Frenky81** [comment]
I don't know how to save without savestates and in any case it is absurd to make an emulator without saves
