### ISSUE TITLE
Build 28042020 Pokemon ruby omega: crash after algatia arena

### ISSUE THREAD

**Issue by Ellian** [weihuoya/citra#54]
Hello

I am playing Pokemon ruby omega on Huawei mediapad m5.
I have already spent 16 hours in the game.
I am at the algatia arena.
I have beaten the champion.
When I go outside everything is shaking but instead of viewing some light the screen goes black and nothing is happening.
Do you have the same problem?
Is there a way to skip this video?

**Comment by AndresNorm** [comment]
Turn off cheat codes.
Then on again after

**Comment by Ellian** [comment]
Thanks a lot your are my savior.
