### ISSUE TITLE
Black Screen Issues On Update 20220517

### ISSUE THREAD

**Issue by RonzelIGuess** [weihuoya/citra#549]
Yeah it just turns black screen when exiting while in game then going back in and when going on split screen it results in a black screen. So basically screen goes black when some interruption happens and yes i did deleted the CEC directory but this issue still remains

**Comment by Tappy-tech** [comment]
Deleting CEC directory only cleans StreetPass files. This is to disable StreetPass for some titles. You can also disable them with 3DS system settings.

**Comment by jsiwjddkoqa** [comment]
re-instal the apk
