### ISSUE TITLE
Wierd issue 

### ISSUE THREAD

**Issue by shaodwmax** [weihuoya/citra#55]
When the game loaded up for the first time every since then the color blue is very very light and there are some wierd leftover animation lines showing up on the screen and some of the pokemon's spites won't load 
Version tag : 20200428
The device details
Processor - snapdragon 665
Opengl- 3.2
Ram - 4gb
Found on both x and y 
Reason - unknown
![IMG-20200505-WA0023](https://user-images.githubusercontent.com/64846788/81070116-71c92100-8f00-11ea-9747-5a9347b49bb5.jpg)
![IMG_20200505_184053](https://user-images.githubusercontent.com/64846788/81070124-7392e480-8f00-11ea-9cfa-64ee37cd6193.jpg)
![IMG-20200505-WA0024](https://user-images.githubusercontent.com/64846788/81070127-74c41180-8f00-11ea-83c5-3b2dbf2f2723.jpg)

**Comment by Ellian** [comment]
Have a look at the load texture hack setting.
I had the same issue on Pokemon ruby omega.

**Comment by OdinDxD** [comment]
Turn on :

Use Virtual SD
Enable CPU Jit
Enable Hardware shader
Accurate multiplication
Use seperable shader*
Turn off :

New 3DS mode
Texture Load hack
Customer texture
Preload custom texture
*Seperable shader can be found under preload custom texture option and choose the mentioned shader, this is for the latest citra.

ps : this setting depends on your device if it can handle the game, this is the only way to make the graphic fixed.

**Comment by aecarvalho** [comment]
This issue has been addressed, disabling texture hacks and enabling accurate multiplication will solve the colour and ghosting issues.
