### ISSUE TITLE
Arrow button doesn't work properly

### ISSUE THREAD

**Issue by cool6996** [weihuoya/citra#550]
Whenever i press the down button one time of the control pad, the arrow get down twice in Pokemon Y (i haven't played any other game). Please tell me how to fix this. I have CitraMMJ.

**Comment by cool6996** [comment]
> Did you use 60 FPS cheat? Did you increase speed limit above 100%?

Yes

**Comment by cool6996** [comment]
Can someone help me know how to fix this problem?

**Comment by Tappy-tech** [comment]
> > Did you use 60 FPS cheat? Did you increase speed limit above 100%?
> 
> Yes. Should i have not done it?

Yes, you shouldn't have. Fast forward doesn't affect it, but 60 FPS cheat does. Why people even use it?
