### ISSUE TITLE
Pokemon I catch are from UK even though I'm located in US

### ISSUE THREAD

**Issue by ExBreadstick** [weihuoya/citra#552]
Pkhex save editor says that the pokemon I'm catching in Ultra Sun are from the UK even though the 3ds region is North America causing a legality issue. The reason I'm confident it's a mmj issue is because pokemon that I catch in the same save on official desktop citra are completely normal, but all the ones I caught on mmj are still from the UK. I've been trouble shooting for 2 days and haven't found a solution yet.

**Comment by Tappy-tech** [comment]
Try changing region in system settings (3DS, not Citra).

**Comment by ExBreadstick** [comment]
Finally fixed it! I had to copy my config file from official desktop citra and replace the mmj config file with it. Now my pokemon aren't bri' ish anymore, lol.
