### ISSUE TITLE
Exynos2200 shader issues

### ISSUE THREAD

**Issue by xgk31** [weihuoya/citra#555]
Hello, on the Samsung s22 line (exynos) majority of 3D games have shader issues. No setting changes work as a workaround. Please look into this. Thank you.

Examples:

https://user-images.githubusercontent.com/106036876/169718666-b9c90e3d-0c9a-486b-91cf-5f3e233ac9ab.mp4

https://user-images.githubusercontent.com/106036876/169718673-5931721b-89eb-4daa-83bd-e219eaa33fc1.mp4

**Comment by RedRudra2696** [comment]
Give me link of this citra version plz

**Comment by xgk31** [comment]
It's on the latest build. https://github.com/weihuoya/citra/releases/tag/20220517

**Comment by xgk31** [comment]
Hi I've tested thiz on the new version and it doesn't seem fixed, same issues still occurring. Is this a case of no known fix? Thank you.

**Comment by Mathiasxo** [comment]
@weihuoya thank you so much for you work, I just want to let you know that this is still an issue on Exynos 2200 with their Xclipse 920 gpu. Once again thank you for your work
