### ISSUE TITLE
Starfox 64 3d issue

### ISSUE THREAD

**Issue by ckgbr** [weihuoya/citra#56]
in the game starfox 64, the top screen only shows the image on the left, the other half is off!
I'm using the latest version: 20200428
Thanks for the awesome work!

![Screenshot_20200507-085531318](https://user-images.githubusercontent.com/46280761/81291684-a512c980-9040-11ea-9c02-94ddb6e83d44.jpg)
![Screenshot_20200507-085548993](https://user-images.githubusercontent.com/46280761/81291689-a5ab6000-9040-11ea-815a-d9569ee8a68b.jpg)
![Screenshot_20200507-085604402](https://user-images.githubusercontent.com/46280761/81291691-a643f680-9040-11ea-9104-be20df1e21ac.jpg)

Please read the FAQ:
https://citra-emu.org/wiki/faq/

THIS IS NOT A SUPPORT FORUM, FOR SUPPORT GO TO:
https://community.citra-emu.org/

If the FAQ does not answer your question, please go to:
https://community.citra-emu.org/

====================================================

When submitting an issue, please check the following:

- You have read the above.
- You have provided the version (commit hash) of Citra you are using.
- You have provided sufficient detail for the issue to be reproduced.
- You have provided system specs (if relevant).
- Please also provide:
  - For any issues, a log file
  - For crashes, a backtrace.
  - For graphical issues, comparison screenshots with real hardware.
  - For emulation inaccuracies, a test-case (if able).

--->

**Comment by aecarvalho** [comment]
Did it get solved?
