### ISSUE TITLE
config-games.ini edit

### ISSUE THREAD

**Issue by some1onLSD** [weihuoya/citra#570]
Hello,
Thanks @weihuoya for the last couple of updates the emulator works better than ever.

One feature I liked in the update is "config-games" add up, it's just great for tweaking and optimizing every game to its best settings.

Anyway I'm trying to edit "shader_type" in the config-games file for (Legend of Zelda Majora's mask) to "Separate Shader" but no luck with it tried every word combo.

Is there any way of doing this (maybe adding in-emulator settings tab in the app in the future?) because this game becomes more playable and lag free with this setting add up. Thanks 

![Screenshot_2022-06-04-15-38-33-0828258437~2](https://user-images.githubusercontent.com/74503778/172007780-8f719f9f-4242-4b11-bf5a-87b4e2ec9e3f.png)

![Screenshot_2022-06-04-15-40-39-1628518405~2](https://user-images.githubusercontent.com/74503778/172007862-f612b2be-a8e8-4389-9a13-6869aafeb922.png)

**Comment by Tappy-tech** [comment]
It can be done through config-mmj.ini file

**Comment by some1onLSD** [comment]
@Tappy-tech Yeah! how??? I am asking that question

**Comment by Tappy-tech** [comment]
> @Tappy-tech Yeah! how??? I am asking that question

1. Edit config-mmj.ini
2. Find line with "shader_type = x" (x is a shader type number. 0 - Normal Shader, 1 - Normal Shader with cache, 2 - Separate Shader; if you don't have it, you can add it to empty line in [Debug].
![Screenshot_2022-06-05-21-21-43-51_8ab4343d10cec22f9bd2ed0fcab43a45](https://user-images.githubusercontent.com/72254437/172064850-5b2936ec-c205-4531-8135-46906ce0a9be.jpg)
Place it like this, if you don't know where.

3. Add any of shader option numbers.
4. Save it.

**Comment by some1onLSD** [comment]
@Tappy-tech bro that's not what I was asking about, this that you sent I could just change it in the emulator Settings → Shader Type → Separate Shader....

I am asking about "config-games.ini" not "config-mmj.in" they are not the same thing dude. the one I'm asking for it is made for every game separately not global emulator setting. If you know

**Comment by Gelo021** [comment]
@weihuoya yes sir can u port creat game setting like Ppsspp have. So we can have different setting in every game

**Comment by some1onLSD** [comment]
@Gelo021 yeees that what I am asking about in this thread, I hope he adds it soon
