### ISSUE TITLE
Unable to move saves into save locations

### ISSUE THREAD

**Issue by LadyHaywood** [weihuoya/citra#573]
I'm using the latest release of the storage access version and I can't seem to move save files into the games's folders. I know that android 11 introduce restrictions on going into the data folder so I tried using es file explorer and files but they failed when moving the file.

I have an 22 ultra. I've tried this only pixel 3a and it didn't work either.

**Comment by Tappy-tech** [comment]
You can try using Total Commander (If root) and CX Explorer (No root)

**Comment by LadyHaywood** [comment]
Using cx explorer failed too. Rooting it might work I personally don't want to do that.

**Comment by Gelo021** [comment]
Zarchiver im using right now, non-root phone

**Comment by LadyHaywood** [comment]
Also failed to move the save over.

**Comment by AlexS2412** [comment]
use non storage access version. its so fucked that you literally cant write anything there once the app has ever done so. youd have to wipe data and put it there before it accesses first time. the non storage access that uses internal storage root still works. just use that and save yourself the trouble. fuck google.

**Comment by jsiwjddkoqa** [comment]
yeah fuck google,scoped storage sucks ballsss
