### ISSUE TITLE
Map, Fonts in TBOI

### ISSUE THREAD

**Issue by artslay** [weihuoya/citra#594]
Missing Map and items name
The Binding Of Isaac: Rebirth
![Screenshot_20220708-194839.png](https://user-images.githubusercontent.com/16070464/177995411-c349d76c-4388-4aa5-a3d9-33998962dadf.png)

**Comment by Patojpcr** [comment]
Llevo casi un día entero buscando como Descargar j***** juego en cita y la página no ayuda
