### ISSUE TITLE
ORAS - Stucked at mossdeep

### ISSUE THREAD

**Issue by setsunatendo** [weihuoya/citra#60]
![Screenshot_2020-05-09-17-49-00-616_org citra emu](https://user-images.githubusercontent.com/65071602/81472152-4146f700-9220-11ea-8d7f-b90efe37bc97.jpg)
![Screenshot_2020-05-09-17-49-09-826_org citra emu](https://user-images.githubusercontent.com/65071602/81472154-4310ba80-9220-11ea-94d6-64fadca53c1a.jpg)
![Screenshot_2020-05-09-17-49-14-702_org citra emu](https://user-images.githubusercontent.com/65071602/81472155-4441e780-9220-11ea-886d-6c683541d62d.jpg)
![Screenshot_2020-05-09-17-49-20-184_org citra emu](https://user-images.githubusercontent.com/65071602/81472156-44da7e00-9220-11ea-8007-5f7e02b7b7e0.jpg)

I got black screen after defeating tate and liza. After walking out, normally there would be a cut scene but I just got the earthquake scene and then everything goes black. Any idea how to fix this?

**Comment by AndresNorm** [comment]
Disable your cheat first before exiting.
Then on again
