### ISSUE TITLE
To what state Citra MMJ is going to glitch further?

### ISSUE THREAD

**Issue by Tappy-tech** [weihuoya/citra#605]
~~In Pokémon USUM, there are just many graphical glitches that can be counted. They can't be fixed.~~

![Screenshot_2022-07-15-18-41-12-11_53c01e3b6443161a8deff0f1f7f140ba](https://user-images.githubusercontent.com/72254437/180480898-bbf1dc6e-cbb8-4510-9a3f-9b85ca1aebba.jpg)
![Screenshot_2022-07-15-18-39-51-30_53c01e3b6443161a8deff0f1f7f140ba](https://user-images.githubusercontent.com/72254437/180480902-51e8e7d4-dea5-4f36-b5f0-a872e1459a86.jpg)

https://user-images.githubusercontent.com/72254437/180480903-c0ed0788-09da-46b7-9feb-2efdedf1710f.mp4

~~Fire Emblem Echoes start to become unplayable as well, due to major graphical glitches, it also lost most of the sound and music.~~

~~The intro has no music or sound at all. Bottom screen is also white, too many graphical glitches.~~

~~As of now, some games have broken graphics. It may be because of shader cache.~~

~~Metroid Samus Returns has title name, but nothing else.~~

![Screenshot_2022-09-03-12-11-59-95_c198c715d99ba250d5a335743408f64f](https://user-images.githubusercontent.com/72254437/188264152-3fdb1131-8533-4c78-89b9-702d3db4df9a.jpg)

~~In original, without graphical glitches, it should be like this:~~

![Screenshot_2022-09-03-12-16-05-74_53c01e3b6443161a8deff0f1f7f140ba](https://user-images.githubusercontent.com/72254437/188264250-18503e36-9d1c-4c94-b15c-5b5b5db8379e.jpg)

Note, that many of these glitches weren't even present as well.

**Comment by weihuoya** [comment]
turn on accurate multiplication?

**Comment by Tappy-tech** [comment]
> turn on accurate multiplication?

It won't work. It's already on from settings.

**Comment by weihuoya** [comment]
upload game save data, please

**Comment by Tappy-tech** [comment]
> upload game save data, please

![main](https://user-images.githubusercontent.com/72254437/181886225-ac3993ee-8830-4483-ab9b-d63a189aee9d.png)

Since for some reason it doesn't allow me to upload the default file, I added .png extension. When applying save file, remove .png extension.

**Comment by AlexS2412** [comment]
#627 is proof that this will not be fixed. @weihuoya doesnt seem to care that mali gpu have issues and would rather ignore them than try to debug and fix. same for seperate shader.
