### ISSUE TITLE
Separate Shader fails to compile on Mali, Resulting in black screen.

### ISSUE THREAD

**Issue by AlexS2412** [weihuoya/citra#606]
with separate shader i am unable to get any game to work on the pixel 6.
![Screenshot_20220723-115540](https://user-images.githubusercontent.com/14182708/180612751-1a77b3f2-1626-408a-b920-c1e7cfa814a6.png)
please fix this if possible.

**Comment by jsiwjddkoqa** [comment]
why not using shader with cache

**Comment by weihuoya** [comment]
Mali doesn't support it

**Comment by jsiwjddkoqa** [comment]
i see
