### ISSUE TITLE
Cryogonal has the longest line caused by graphical glitch (USUM/SM)

### ISSUE THREAD

**Issue by Tappy-tech** [weihuoya/citra#607]
![IMG_20220727_122935](https://user-images.githubusercontent.com/72254437/181213799-5e6fb8b2-0bcd-46fa-9de8-98fe45c0fd66.jpg)
The line can extend even further. This screenshot was cut to only match the main outline of this graphical glitch.

**Comment by weihuoya** [comment]
https://github.com/weihuoya/citra/releases/tag/20220810

**Comment by Tappy-tech** [comment]
> https://github.com/weihuoya/citra/releases/tag/20220810

I'm not yet able to view Cryogonal and Qwilfish, but if it's supposed to fix the others too, then I don't think they had graphical glitches fixed.

**Comment by Tappy-tech** [comment]
Looks like Disabling Hardware Shader fixes glitches, but still, before the glitches happened, when I played USUM yet, I didn't have a need to disable it.
