### ISSUE TITLE
'Still' Can't enter SM/USUM Hall of Fame

### ISSUE THREAD

**Issue by Platinum7765** [weihuoya/citra#608]
![Screenshot_20220729-155719](https://user-images.githubusercontent.com/109387320/181701443-ceb368f4-665e-4ebb-b559-9d9748afe856.jpg)

If I play USUM with carrying 6 pokemon and beat champion and enter hall of fame, there's just black screen and game freezes. Only when I carry 3 pokemons, this issue doesn't happen.

I could found this issue existed since 2018 on other comunities.

**Comment by weihuoya** [comment]
upload game save data, please
I will test later

**Comment by Gelo021** [comment]
Thats my issue before. Kinda bypass it by downloading one on google play, its kinda laggy but u can switch back to mmj once its finish
