### ISSUE TITLE
Lot of bugs recently

### ISSUE THREAD

**Issue by Gelo021** [weihuoya/citra#612]
![Screenshot_2022-07-31-03-07-58-43_53c01e3b6443161a8deff0f1f7f140ba](https://user-images.githubusercontent.com/67460268/182037049-feda8ac2-bbfb-4309-8e71-828e0a7e4add.jpg)
![Screenshot_2022-07-31-03-07-48-33_53c01e3b6443161a8deff0f1f7f140ba](https://user-images.githubusercontent.com/67460268/182037052-ddfd8f1e-c026-4148-8487-a652936256cb.jpg)

Havent tested on other games but all the mh games knda mess up when GS si on

**Comment by Gelo021** [comment]
https://user-images.githubusercontent.com/67460268/182038246-da996fe5-a68a-4ab8-914f-d1728c4ce393.mp4

Just downloaded the game today 

Ever Oasis
X2
Accurate Multi On
Memorry reuse Off

**Comment by Gelo021** [comment]
https://user-images.githubusercontent.com/67460268/182504690-209c3a82-105d-4f90-8afe-c4c278fc9f3d.mp4

@weihuoya cant play any more 😭

**Comment by Gelo021** [comment]
Btw im using the default setting nothing change

**Comment by weihuoya** [comment]
geometry shader doesn't work properly on mali gpu

**Comment by weihuoya** [comment]
``
