### ISSUE TITLE
Citra MMJ Portrait and Landscape Issue.

### ISSUE THREAD

**Issue by Walegy** [weihuoya/citra#618]
Whenever I turn my phone landscape it still is in the portrait side but stretched out from end to end.

**Comment by weihuoya** [comment]
which device? any screenshot?

**Comment by Walegy** [comment]
> 

![Screenshot_20220807-184247](https://user-images.githubusercontent.com/107286645/183313821-6c0c3747-57aa-47ba-a115-2705f3a5d441.png)
![Screenshot_20220807-184250](https://user-images.githubusercontent.com/107286645/183313823-e850a554-1f5b-4b15-a84f-4915e8eb5c61.png)
These are the screenshots sorry if I replied late I've been working on my N64 port of OOT called "Legends of Scorchwings!"

**Comment by Walegy** [comment]
But as you can see the background for Landscape.jpg is very off and my Device is an LG v60

**Comment by weihuoya** [comment]
https://github.com/weihuoya/citra/releases/tag/20220810
