### ISSUE TITLE
Pokemon alpha sapphire Black Screen

### ISSUE THREAD

**Issue by Eduardo00425** [weihuoya/citra#622]
Hola, no se si alguien hablara español aquí pero también lo pondré en ingles, y es que tengo un problema con Pokemon alfa zafiro cuando aquiles esta a punto de despertar a Kyogre Primigenio, cuando va a salir la cinematica la pantalla se pone en negro y se queda en 15 fps a veces subiendo a 19,no se si alguien pueda ayudarme con ello

I have a problem with Pokemon alpha sapphire when Archie is about to wake up Primal Kyogre, when the cinematic is going to come out the screen goes black and stays at 15 fps sometimes going up to 19, I don't know if someone can help me with it

![Screenshot_2022-08-04-15-03-41-513_org citra emu](https://user-images.githubusercontent.com/110643069/182976622-ade66b70-ce49-4a63-8f3f-9de08b361224.jpg)

**Comment by weihuoya** [comment]
upload your game save data, please

**Comment by Eduardo00425** [comment]
> upload your game save data, please

Sure, but how i do it? Sorry i'm new on this

**Comment by weihuoya** [comment]
pack `citra-emu\sdmc` directory to zip, and upload

**Comment by Eduardo00425** [comment]
> pack `citra-emu\sdmc` directory to zip, and upload

[0011c500.zip](https://github.com/weihuoya/citra/files/9264786/0011c500.zip)

**Comment by Eduardo00425** [comment]
If it helps you, my phone is a Poco M3 with 4gb of Ram and snapdragon 662

**Comment by weihuoya** [comment]
https://github.com/weihuoya/citra/releases/tag/20220806

**Comment by Eduardo00425** [comment]
Thanks you, it's working!
