### ISSUE TITLE
MHXX not opening

### ISSUE THREAD

**Issue by Icho24** [weihuoya/citra#623]

**Comment by Deka710** [comment]
whats your phone? which citra ver?  and please explain your problem instead just `MHXX not opening`
because works fine for me

**Comment by Icho24** [comment]
Realme 6i mediatek G80 and the version of my citra is the latest version here on github. So the problem is that, if i open the game, it shows black screen then forcing my device to exit the game

**Comment by Deka710** [comment]
thats explain better,looksnlike mali gpu issue

**Comment by Icho24** [comment]
Ok thank you
