### ISSUE TITLE
DSi (dsi to 3ds) .cia games do not work on Citra MMJ

### ISSUE THREAD

**Issue by ptnnx** [weihuoya/citra#626]
DSi converted **.cia** games NOT work on MMJ!
It's showing error!, I don't know why.
![Screenshot_2022-08-05-10-56-25-59_53c01e3b6443161a8deff0f1f7f140ba](https://user-images.githubusercontent.com/81209454/183007643-3303a7ed-ade9-4d54-b14d-566ad317a8ad.jpg)

**Comment by weihuoya** [comment]
yes, try nds version
