### ISSUE TITLE
Fix Hardware Shader for Mali

### ISSUE THREAD

**Issue by AlexS2412** [weihuoya/citra#627]
Ive posted this issue before but i guess it got ignored. the texture warping in games caused by mali, happens in Ocarina of Time, Majora's Mask, Luigi's Mansion Dark moon, and many other grezzo titles. Also the same issue caused games to miss or repeate frames like an old gpu in Super Mario 3D Land, New Super Mario Bros 2, and many others. i am begging you @weihuoya please fix these issues i will PAY you to fix them.

**Comment by weihuoya** [comment]
known issues and no solution

**Comment by AlexS2412** [comment]
This was prematurely clsoed. as a developer you can't just say" there is no fix." this is immature and not how bug reporting works @weihuoya

**Comment by Deka710** [comment]
stop being entitled its free app,get a better phone instead

**Comment by AlexS2412** [comment]
> stop being entitled its free app,get a better phone instead

That's not how development works. this is not entitlement. the code has issues that cause the bug to happen. this must be fixed for the code to improve or any future updates can have more problems related to it. there is a reason emulators like dolphin were built with accuracy first. by ignoring the issue it doesn't make the emulation more accurate, and pretending its just one device with issue obviously isnt so. there is so many other instances of this same issue.

**Comment by Deka710** [comment]
first of all citra android is abandonend project,u must be thankful theres someone adding such feature i.e multiplayer etc,weihouya said no solution so i guess he cant fix everything on this abandoned project.
