### ISSUE TITLE
Any chance that we'll see a .5x internal resolution option?

### ISSUE THREAD

**Issue by dmar3000** [weihuoya/citra#629]
Using the Antutu version on the Retroid Pocket 2 Plus (2GB RAM). Have had decent success with playing games like Spy Hunter and even Tekken 3ds.
https://youtu.be/lQ4jfmCoZbg
https://youtu.be/xRcUHfBq-q0

Was curious to see if there would ever be an option available to lower resolution under 1x for low end devices, thanks!

**Comment by KSHADOWK** [comment]
Si esto puede aumentar fps en dispositivos gama baja
