### ISSUE TITLE
Resident Evil Revelations /Mercenaries

### ISSUE THREAD

**Issue by Hisham735** [weihuoya/citra#634]
These 2 Games not running well on Kirin 980 with Mali-G76 only 10~15fps on 1x 2x 3x 4x
While both run 30fps on old snapdragon phones..

**Comment by Deka710** [comment]
Mali GPU issue and yes,any emulators are better on snapdragon devices

**Comment by Hisham735** [comment]
> 



> Mali GPU issue and yes,any emulators are perform better on snapdragon devices

Do u say it's normal that Snapdragon 665 with Adreno 610 can run Resident Evil games 30fps while Kirin 980 with Mali G76 MP10 can only run it 15fps 😬

**Comment by Deka710** [comment]
yes

**Comment by Deka710** [comment]
Mali GPU drivers are horribel

**Comment by Hisham735** [comment]
> Mali GPU drivers are horrible

Then explain why Mali-G76 outperform Adreno 610 in the rest of 3ds games PS2/GC/WII
For example Snapdragon 665 (Adreno 610) runs Dead or Alive Dimension on 1x resolution 45fps while Kirin 980 (Mali-G76) can run it on 4x 60fps
Another example Snapdragon 665 (Adreno 610) can barely run Resident Evil 4 ps2 version using AetherSX2 on 1x while Kirin 980 (Mali-G76) can run it smoothly on x3.5?
That's a tiny examples.. The difference is huge between the two

**Comment by Hisham735** [comment]
Fixed by using Vulkan on Citra beta v2 (Vulkan testing build)
