### ISSUE TITLE
ProjectXzone black screen on battles, On 3 last citra mmj builds.

### ISSUE THREAD

**Issue by OskarKota** [weihuoya/citra#636]
Problem solved only in version 104eb229d of citra mmj, error continues on last version.
![image](https://user-images.githubusercontent.com/111063244/184384903-a7f42f2c-06f0-4dae-924e-dacf330309e1.png)
P.D. here's my savefile (citrammj last version, projectXzone EUR version)
https://www22.zippyshare.com/v/rgsidDpt/file.html

Please read the FAQ:
https://citra-emu.org/wiki/faq/

THIS IS NOT A SUPPORT FORUM, FOR SUPPORT GO TO:
https://community.citra-emu.org/

If the FAQ does not answer your question, please go to:
https://community.citra-emu.org/

====================================================

When submitting an issue, please check the following:

- You have read the above.
- You have provided the version (commit hash) of Citra you are using.
- You have provided sufficient detail for the issue to be reproduced.
- You have provided system specs (if relevant).
- Please also provide:
  - For any issues, a log file
  - For crashes, a backtrace.
  - For graphical issues, comparison screenshots with real hardware.
  - For emulation inaccuracies, a test-case (if able).

--->

**Comment by weihuoya** [comment]
try reset settings

**Comment by OskarKota** [comment]
Cache deleted and reset cfg, not working.

**Comment by weihuoya** [comment]
how about this https://github.com/weihuoya/citra/releases/tag/20220815 ?
if it not working, upload your game save data, please

**Comment by weihuoya** [comment]
> 

upload your game save data, please

**Comment by weihuoya** [comment]
> Hey i use the latest version and it still black screen

upload your game save data, please

**Comment by OskarKota** [comment]
P.D. here's my savedata(from last version of citra mmj and the game is: projectXzone eur version)

**Comment by weihuoya** [comment]
upload any files in "citra-emu/log" directory, and upload your game save data, please

**Comment by boygo2239** [comment]
20220815, I also have a black screen situation in some of the battles.
https://youtu.be/Xr7Bx2m8xtY
