### ISSUE TITLE
Citra not installing on 8.1 Device.

### ISSUE THREAD

**Issue by AmpedgamR** [weihuoya/citra#64]
I'm sorry if I'm bothering any of you but the mmj build is saying not installed, is it because of the cache data or what?

**Comment by RangerKevin2** [comment]
Maybe your phone is not powerful enough

**Comment by AmpedgamR** [comment]
I just searched up now that it's because I have a 32bit Device. Is there a
way to either make the app have 32bit support on the app or am I screwed?

**Comment by RangerKevin2** [comment]
[my english may have errors] I tried to install citra on two different 32bit phones, unfortunately citra works only on 64bit phones and there is no way to fix this, except buy a new phone if you have a pc maybe citra will work on it

**Comment by AmpedgamR** [comment]
Thanks for the pc suggestion, and thank you for replying.

**Comment by RangerKevin2** [comment]
Citra works better on pc, citra for Android needs an expensive phone to work fine

**Comment by Hakdogboi** [comment]
Hi mines a samsung 10, and google said its a 64 bit but every time I install citra it always says not installed, even though I have a 64 bit phone. I wanted to try it in my phone since my laptop is just so slow and laggy.

**Comment by AmpedgamR** [comment]
It's probably space or your sdk.

**Comment by Hakdogboi** [comment]
No I have a lot of space but even though I have a lot of space it still doesn't work

**Comment by AmpedgamR** [comment]
It might be sdk then, luckily for you I know how to change it if that
doesn't work then try changing the install path to internal only by using
all editor.

**Comment by Hakdogboi** [comment]
Ah really you know how? Would you mind telling me?

**Comment by AmpedgamR** [comment]
Ok for off, you want to check your sdk, download sdk reader from Google
play and tell me what it says.

**Comment by Hakdogboi** [comment]
Uh..  it keeps stoping, like everytime I try to open it, it always says Sdk Reader keeps stopping

**Comment by Hakdogboi** [comment]
Should I try to install other apps?

**Comment by AmpedgamR** [comment]
Yes install another app that says sdk reader, I'm sorry I forgot to mention
that the other one crashes on some devices.

**Comment by Hakdogboi** [comment]
Uhhh random question the bit part like 32 or 64 is it part of like the cpu?

**Comment by Hakdogboi** [comment]
Oh crap Google was wrong my phone is a 32 bit I'm really sorry for wasting your time.

**Comment by AmpedgamR** [comment]
What do you mean like is it required to run citra, is that what you are
asking or is it part of your sdk?

**Comment by Hakdogboi** [comment]
Well in the top comment it said that the phone needs to be a 64 bit

**Comment by AmpedgamR** [comment]
Oh its fine. Google is crap sometimes. I'm just glad that you are
interested in citra like I am. One of the developers said that he tried on
PC that's the best option right now.😁

**Comment by Hakdogboi** [comment]
Yep google is crap, citra is best at computer though I'm still sorry.

**Comment by AmpedgamR** [comment]
Yeah Which sucks.😑 But I'm using PC right now which is actually great.

**Comment by Hakdogboi** [comment]
Lol

**Comment by AkiraGX1** [comment]
Solution for "Citra not installed"



My citra was also not installing, the solution is to uninstall updates from google play services, right after doing this the emulator will install normally.

**Comment by faroukabd000** [comment]
Citra mmj support  only 64 bit cpu + powerful gpu driver (adreno 500~.......)
Good ram(around 2 and up) ,
Nouga system and up
Sooo  citra team are working on that to make it suitable for medium devices

**Comment by faroukabd000** [comment]
New Telegram group 

https://t.me/joinchat/QQ8ysBs5jgnf1_GbwXiuaQ
