### ISSUE TITLE
ProjectXzone black screen on battles



### ISSUE THREAD

**Issue by NoMad012** [weihuoya/citra#640]
I use the latest version and it still blackscreen [Screenshot_2022-08-17-09-14-38-45_c198c715d99ba250d5a335743408f64f.jpg](https://user-images.githubusercontent.com/106659307/185016544-d533f095-cc65-4c73-a9d0- - -4e1990f1e322.jpg)

**Comment by weihuoya** [comment]
upload any files in "citra-emu/log" directory, and upload your game save data, please

**Comment by OskarKota** [comment]
Thanks to citra mmj team, they fix the bugs on the last build(20220912), great work guys.
