### ISSUE TITLE
项目编译报错

### ISSUE THREAD

**Issue by android-1995** [weihuoya/citra#649]
https://github.com/weihuoya/citra/commit/08529f89fd54434d631404cda4ff2b402fd6e212 @weihuoya 大佬，这个提交的代码不完整。

1.NativeLibrary.SetBackgroundGLSL方法不存在
2.org.citra.emu.overlay.InputOverlay的R.integer.BUTTON_x_x这些id都不存在了

**Comment by trexguo** [comment]
+1

**Comment by trexguo** [comment]
修一下吧~
