### ISSUE TITLE
Ultra Sun Graphics Fail

### ISSUE THREAD

**Issue by AetheralMeowstic** [weihuoya/citra#652]
The graphics in _Pokémon Ultra Sun_ work just fine in the previous version, but fail in this build.

Shown here is a screen recording from Antutu 20220902

https://user-images.githubusercontent.com/85904844/188219878-a02dd4ff-b7eb-4960-9142-7ccbb60cd5a0.mp4

No amount of changing and clearing the settings works. I had to revert to the previous build just to make the game playable. Galaxy A53 5G, Exynos 1280

**Comment by Jalildann** [comment]
This happen in several games, I tried 3 and they are broke, stay in the last build at least wait for the next update.

**Comment by weihuoya** [comment]
upload files in `citra-emu\log` directory, please

**Comment by nicolapace** [comment]
Resetting settings I can see that the problem is the Memory Reuse option. Buy even with Memory Resue disabled the game still has graphic glitches.

**Comment by weihuoya** [comment]
https://github.com/weihuoya/citra/releases/tag/20220906
