### ISSUE TITLE
Mario kart y algunos juegos

### ISSUE THREAD

**Issue by Fbn316** [weihuoya/citra#653]
https://user-images.githubusercontent.com/108166313/188226753-9d15146d-5d30-4659-b339-2781e6ce438c.mp4

**Comment by Jalildann** [comment]
I have the same problem here, this build broke some games, in my case tried Loz a link between worlds, Majora's mask, super Mario 3d land, those are some of the games thar broke the graphics for me, I'm using SD 860,

**Comment by weihuoya** [comment]
upload files in `citra-emu\log` directory, please

**Comment by weihuoya** [comment]
https://github.com/weihuoya/citra/releases/tag/20220906
