### ISSUE TITLE
New shader cache break a lot of games

### ISSUE THREAD

**Issue by Deka710** [weihuoya/citra#654]
both normal shader with cache and separate shader are broken in 20220902 build
![Screenshot_2022-09-03-05-36-41-482_org citra emu](https://user-images.githubusercontent.com/97207704/188243260-38886e54-af12-44c0-b0cc-d16c4b9d8d47.jpg)
![Screenshot_2022-09-03-05-37-11-509_org citra emu](https://user-images.githubusercontent.com/97207704/188243266-c99f8358-9498-40cc-9f14-c4c9e9b03fea.jpg)
![Screenshot_2022-09-03-05-37-32-875_org citra emu](https://user-images.githubusercontent.com/97207704/188243268-cf9210a2-3071-4219-9916-558d6b1da057.jpg)

**Comment by Deka710** [comment]
tested on my games
e.x. troopers,all monster hunter series,pokemon omega  ruby/as,new super mario bros 2,super mario 3d land are broken

**Comment by Jalildann** [comment]
And some legend of Zelda game are broken too.

**Comment by weihuoya** [comment]
upload files in `citra-emu\log` directory, please

**Comment by Deka710** [comment]
theres no log :(

**Comment by weihuoya** [comment]
which device?

**Comment by Jalildann** [comment]
The problem is that I had change to the previous build and its no log file in the folder

**Comment by AetheralMeowstic** [comment]
> tested on my games e.x. troopers,all monster hunter series,pokemon omega ruby/as,new super mario bros 2,super mario 3d land are broken

_Pokémon Ultra Sun_ is broken, too.
