### ISSUE TITLE
I can't play pokemon X, street fighter IV, super smash bros 3ds.

### ISSUE THREAD

**Issue by MarcoV14** [weihuoya/citra#656]

**Comment by Jalildann** [comment]
upload files in citra-emu\log directory, please

**Comment by MarcoV14** [comment]
What? I don't understand.

**Comment by Jalildann** [comment]
Yes, you can upload in here files, go to that directory and look for the log file, and upload it in here, so that the developer can see what's the problem.

**Comment by MarcoV14** [comment]
I don't know how to upload a file from a mobile.

**Comment by MarcoV14** [comment]
Do I have to upload a document that is in the archive? Or do I have to upload the whole file?
Because if it's the file I don't know how to upload it on mobile.

**Comment by weihuoya** [comment]
https://github.com/weihuoya/citra/releases/tag/20220906
