### ISSUE TITLE
prevents to download old shader cache on github

### ISSUE THREAD

**Issue by Deka710** [weihuoya/citra#657]
on ver 20220902 when connected to the internet it tries to download old shader cache on github which is cause graphical glitch in a lot of games:
https://github.com/weihuoya/citra/issues/654#issue-1360662884

then i delete the shader cache and turned off the internet the games works without graphical glitch:
![Screenshot_2022-09-04-12-28-37-579_org citra emu](https://user-images.githubusercontent.com/97207704/188299011-96a92daa-efef-4fd8-8038-c46b95e5cff0.jpg)
![Screenshot_2022-09-04-12-29-37-964_org citra emu](https://user-images.githubusercontent.com/97207704/188299014-cad8ab27-7cb8-4e0d-89f2-53e44ab4110d.jpg)

**Comment by MarcoV14** [comment]
With or without internet it keeps giving me graphic failures.

**Comment by Deka710** [comment]
> With or without internet it keeps giving me graphic failures.

clear your cache first,then try without internet

**Comment by MarcoV14** [comment]
But clearing my cache wouldn't harm my other emulators or my apps?

**Comment by Deka710** [comment]
> But clearing my cache wouldn't harm my other emulators or my apps?

no,shader cache in `citra-emu/cache`

**Comment by MarcoV14** [comment]
Do you think they will fix this in future updates?

**Comment by Deka710** [comment]
yes,just wait for fix

**Comment by MarcoV14** [comment]
I see well thank you for the advice and for your opinion.

**Comment by Gelo021** [comment]
https://user-images.githubusercontent.com/67460268/188329745-7d3d658c-1fe7-43c5-aafd-ff4681b926af.mp4

I think its a failed update 
will wait for @weihuoya to fix this

**Comment by VorgonBattlecruiser** [comment]
I was sadly facing the same issues in "Zelda Link between Worlds" European version.
Backgrounds and most things were either completely black or invisible.

Will the actual App get a release to fix this or will this be a fix in the backend (where the shaders get downloaded from)?
Will i find out eventually if i can turn on internet again while using Citra MMJ?

**Comment by Deka710** [comment]
> I was sadly facing the same issues in "Zelda Link between Worlds" European version. Backgrounds and most things were either completely black or invisible.
> 
> Will the actual App get a release to fix this or will this be a fix in the backend (where the shaders get downloaded from)? Will i find out eventually if i can turn on internet again while using Citra MMJ?

automatically downloaded from github when u connected to the internet
![IMG_20220905_222818](https://user-images.githubusercontent.com/97207704/188481703-366b9a71-6d87-4f59-827e-0c98eb3bcb38.jpg)

**Comment by VorgonBattlecruiser** [comment]
@Deka710 So is this something that needs to be fixed about the files on Github (the shaders that were downloaded) or something that needs to be updated in the app?
Is it maybe fixed already and i can enable internet while playing Citra MMJ again or should i wait for an update?

**Comment by VorgonBattlecruiser** [comment]
@Deka710 Thank you!

**Comment by weihuoya** [comment]
how about this version?
[app-release.zip](https://github.com/weihuoya/citra/files/9491063/app-release.zip)

**Comment by Gelo021** [comment]
https://user-images.githubusercontent.com/67460268/188485366-22fd461a-bef2-4c2c-bcd3-497885301723.mp4

Still broken 20220815 doesnt have issue like this

**Comment by Gelo021** [comment]
Ill just use [20220815](https://github.com/weihuoya/citra/releases/tag/20220815)  version while @weihuoya  is fixing things up

**Comment by MarcoV14** [comment]
In my case there are not so many graphic failures anymore but some games like pokemon x, super smash bros 3ds, street fighter IV are still broken.

**Comment by MarcoV14** [comment]
There to delete the entire folder called cache in citra-emu?

**Comment by Deka710** [comment]
> delete cache directory and test again

i did,still the same

**Comment by Gelo021** [comment]
Na we've tried that many times on the latest build @weihuoya

**Comment by Deka710** [comment]
![Screenshot_2022-09-05-23-06-37-871_org citra emu](https://user-images.githubusercontent.com/97207704/188486864-37c00a46-8583-43db-9270-ad9e86fd7699.png)
downloaded shader make it broken

**Comment by Deka710** [comment]
if it didnt download the shader from github its fine,no graphical glitch

**Comment by MarcoV14** [comment]
Could someone please tell me if I have to delete all that folder called cache in citra-emu or just the documents that are in that folder?

**Comment by Gelo021** [comment]
> Could someone please tell me if I have to delete all that folder called cache in citra-emu or just the documents that are in that folder?

U can delete the entire cache folder in citra-emu

**Comment by MarcoV14** [comment]
Thanks bro

**Comment by weihuoya** [comment]
how about this
https://github.com/weihuoya/citra/releases/tag/20220906

**Comment by Deka710** [comment]
> how about this https://github.com/weihuoya/citra/releases/tag/20220906

![Screenshot_2022-09-06-09-57-06-621_org citra emu](https://user-images.githubusercontent.com/97207704/188537630-c497dd0d-d701-49cf-a012-c1ff5e028548.jpg)
its fine now,thank you!!!

**Comment by Gelo021** [comment]
@weihuoya thankyou for the fix ♥️
