### ISSUE TITLE
Huge GLITCH Issue with DKCR 3D

### ISSUE THREAD

**Issue by Walegy** [weihuoya/citra#658]
There's a manor glitch issue on DKCR 3D which glitches the screen intro and lowers FPS drastically!
![Screenshot_20220905-130541](https://user-images.githubusercontent.com/107286645/188493224-4323a880-af0e-4a31-a2a5-94e6728da913.png)
Also here's the name for the device I'm still using.

Device name - LG-V60 Thinq 5G

I hope.this issue gets resolved the sooner the better!

**Comment by saurabd** [comment]
With which version build are you facing the issue ?
Did you tried the previous build - [20220815](https://github.com/weihuoya/citra/releases/tag/20220815)

**Comment by Walegy** [comment]
> 

I'm using the latest build which is the 95th release I believe. I just wish this can get a better update ngl and the only game.without much graphical glitches (except in specific cutscenes) is Luigi's Mansion: Dark Moon.

**Comment by weihuoya** [comment]
https://github.com/weihuoya/citra/releases/tag/20220906
