### ISSUE TITLE
Zero Escape - Zero Time Dilemma [Cutscenes Constant Blacks Lines] [Android] [Citra MMJ]

### ISSUE THREAD

**Issue by RFL0WGitPR** [weihuoya/citra#663]
Zero Escape Zero Time Dilemma has constant black lines during Cutscenes / In Game Cutscenes on Citra MMJ. 

The game however is playable from start to finish 

Game functions with minor graphical or audio glitches and is playable from start to finish.

You'll notice it as soon you start the game

Needs work during all cutscenes (buggy, glitchy black lines on all character shaders during game cutscenes / in game cutscenes).

Game: Zero Escape - Zero Time Dilemma [Decrypted.3ds]
Title ID : 000400000017B200
Platform: Android 11
Citra MMJ: version 20220912
Device: Motorola One Ace 5g
RAM : 6GB RAM.
CPU: Qualcomm Snapdragon 750G 

I hope y'all can test and fix these cutscenes glitches soon

![Screenshot_20220913-013312.png](https://user-images.githubusercontent.com/49012507/189817086-f2ff68f7-d2dd-47b2-aeb7-ce7c04527757.png)

![Screenshot_20220913-013319.png](https://user-images.githubusercontent.com/49012507/189817113-ae029f81-064f-4a4b-b8fd-0aef50f3a333.png)

![Screenshot_20220913-013325.png](https://user-images.githubusercontent.com/49012507/189817140-1dea24d8-ccc9-4fb6-9fab-4afa6d978990.png)

**Comment by weihuoya** [comment]
turn off hardware shader

**Comment by RFL0WGitPR** [comment]
Nope, Issue still remains...

Even after trying your suggestions and workarounds.

I notice the glitchy black lines appear when a characters or objects appear in a cutscene. 

Even on the game title screen before starting a new game there's an 3D object on the title screen  " A Watch" and the object starts to show the black lines 

Maybe the character shaders aren't rendering correctly on this current build

The cutscenes FPS runs normally and audio works well (doesn't lag)

The black glitchy lines are related to the characters / 3D objects on screen during cutscenes.

maybe its a bug for this specific game on Citra MMJ for Android.

Hopefully in a future build update it will be fixed. 

Thank you kindly.

**Comment by weihuoya** [comment]
known issue, turn off hardware shader
