### ISSUE TITLE
Citra sub-region

### ISSUE THREAD

**Issue by Pedroxuy** [weihuoya/citra#664]
In Citra's settings, you can only put the region and country of the console, and for some games to work correctly it is also necessary to indicate the sub-region of the console, and this function does not appear in Citra on android, but only in the PC version.

**Comment by Tappy-tech** [comment]
Are you talking about countries? You can change them in (3DS) System Settings.

**Comment by Pedroxuy** [comment]
It's not that. The subregion is the Home State of the 3DS. For example, it is not possible to put the 3DS as USA and select the sub-region as New York.

**Comment by Pedroxuy** [comment]
> 

It's not that. The subregion is the Home State of the 3DS. For example, it is not possible to put the 3DS as USA and select the sub-region as New York.

**Comment by Pedroxuy** [comment]
> Are you talking about countries? You can change them in (3DS) System Settings.

In all pokemon games, if you don't put the console subregion, the pokemons caught become illegal and can't be traded in online mode.

**Comment by Pedroxuy** [comment]
> Are you talking about countries? You can change them in (3DS) System Settings.

It's not that. The subregion is the Home State of the 3DS. For example, it is not possible to put the 3DS as USA and select the sub-region as New York.

**Comment by Pedroxuy** [comment]
> Are you talking about countries? You can change them in (3DS) System Settings.

In all pokemon games, if you don't put the console subregion, the pokemons caught become illegal and can't be traded in online mode.

**Comment by Tappy-tech** [comment]
> > Are you talking about countries? You can change them in (3DS) System Settings.
> 
> In all pokemon games, if you don't put the console subregion, the pokemons caught become illegal and can't be traded in online mode.

Do you know what is System Settings app?

**Comment by Pedroxuy** [comment]
> > > Are you talking about countries? You can change them in (3DS) System Settings.
> > 
> > 
> > In all pokemon games, if you don't put the console subregion, the pokemons caught become illegal and can't be traded in online mode.
> 
> Do you know what is System Settings app?

Yup. But in citra you don't have this option to change the sub-region, but only the region, right?
