### ISSUE TITLE
Add option to choose console country

### ISSUE THREAD

**Issue by Pedroxuy** [weihuoya/citra#669]
On android citra you don't have the option to choose the console country, but only the emulation region, please add the option to select the console country.

**Comment by Pedroxuy** [comment]
In all pokemon games, if you don't put the console country, captured pokemons become illegal and cannot be traded in online mode.

**Comment by Tappy-tech** [comment]
Again, use System Settings for that.

**Comment by Tappy-tech** [comment]
If you still have problems, try editing hex value in PKSM that is thought to be illegal. You will know which hex value is for and which number is for.

**Comment by Tappy-tech** [comment]
Oh, I'm sorry, it was rather a suggestion. The above will be for those, looking to solution of similiar problem.

**Comment by Pedroxuy** [comment]
> Again, use System Settings for that.

Are you referring to the citra system settings?

**Comment by Tappy-tech** [comment]
> > Again, use System Settings for that.
> 
> Are you referring to the citra system settings?

No. 3DS System Settings, which can be obtained by installing 3DS nand.

**Comment by Pedroxuy** [comment]
> > > Again, use System Settings for that.
> > 
> > 
> > Are you referring to the citra system settings?
> 
> No. 3DS System Settings, which can be obtained by installing 3DS nand.


I didn't know this is possible

**Comment by Pedroxuy** [comment]
> > > Again, use System Settings for that.
> > 
> > 
> > Are you referring to the citra system settings?
> 
> No. 3DS System Settings, which can be obtained by installing 3DS nand.


So is it possible to install nand in citra emulator?
