### ISSUE TITLE
Water type Pokémon are white, despite that accurate multiplication is enabled (XY/ORAS)

### ISSUE THREAD

**Issue by Tappy-tech** [weihuoya/citra#670]
![Screenshot_2022-09-16-17-21-21-07_c198c715d99ba250d5a335743408f64f](https://user-images.githubusercontent.com/72254437/190662185-c1972e3d-e322-4c5f-a4d4-102b17d3bf5e.jpg)
![Screenshot_2022-09-16-17-23-11-07_c198c715d99ba250d5a335743408f64f](https://user-images.githubusercontent.com/72254437/190662218-2de5aabc-8381-44d3-b8d9-2d6ed7d0609a.jpg)

**Comment by weihuoya** [comment]
reset settings

**Comment by Tappy-tech** [comment]
> reset settings

Didn't work.

**Comment by katyurua** [comment]
![deqd123](https://user-images.githubusercontent.com/59998095/190853485-e1fd1c14-7376-4d83-b9da-94c2dcb5f5ae.jpg)

![1663413047497](https://user-images.githubusercontent.com/59998095/190853727-a85e903c-e619-49f5-8213-cb5bfdc19546.jpg)

## not just water type. :joy: (fresh new install, lateset version)
GAME : pokemon ORAS

**Comment by Tappy-tech** [comment]
> ![deqd123](https://user-images.githubusercontent.com/59998095/190853485-e1fd1c14-7376-4d83-b9da-94c2dcb5f5ae.jpg)
> 
> ![1663413047497](https://user-images.githubusercontent.com/59998095/190853727-a85e903c-e619-49f5-8213-cb5bfdc19546.jpg)
> 
> ## not just water type. 😂 (fresh new install, lateset version)
> GAME : pokemon ORAS

Do you even know how Silcoon looks?

**Comment by katyurua** [comment]
> 

PINK？I GUESS？
BUT MARSHTOMP IS BLUE FOR SURE

**Comment by Tappy-tech** [comment]
> > 
> 
> PINK？I GUESS？ BUT MARSHTOMP IS BLUE FOR SURE

![Uploading Screenshot_2022-09-17-14-45-00-88_40deb401b9ffe8e1df2f1cc5ba480b12.jpg…]()

**Comment by weihuoya** [comment]
delete `config-games.ini`, there are some new settings add in latest version.

**Comment by katyurua** [comment]
> delete `config-games.ini`, there are some new settings add in latest version.

THANKS , PROBLEM SOLVED
BOTH TWO  TEXTURE FIXED
![1663428697845](https://user-images.githubusercontent.com/59998095/190864729-5263f1da-4869-4fb0-b6ad-995d1013a003.jpg)
![1663428697841](https://user-images.githubusercontent.com/59998095/190864740-a27ca270-f875-4bd7-9ee3-cc35e86b0cdc.jpg)
