### ISSUE TITLE
Pokemon Omega Ruby and Alpha Saphire water type pokemon image glitch.

### ISSUE THREAD

**Issue by romuloolivers** [weihuoya/citra#671]
In the new version, the Accurate Multiplication function that fixes the water type pokemon bug is no longer working.

Version: 20220913

Sorry for the English I speak from Brazil.

**Comment by weihuoya** [comment]
reset settings, or delete `config-games.ini` in citra-emu/config directory

**Comment by romuloolivers** [comment]
It worked thank you very much

**Comment by Tappy-tech** [comment]
Why not close the issue already?
