### ISSUE TITLE
a question

### ISSUE THREAD

**Issue by Deka710** [weihuoya/citra#674]
out of curiousity,what geometry shader do? in monster hunter games it break some effects
![Screenshot_2022-09-23-15-59-45-989_org citra emu](https://user-images.githubusercontent.com/97207704/191927430-e7f86bff-e3ef-4f35-9633-9332f3ccb2c2.jpg)

**Comment by weihuoya** [comment]
geometry shader only works in a few games.

**Comment by Deka710** [comment]
may i ask in which games?

**Comment by weihuoya** [comment]
https://github.com/citra-emu/citra/pull/2865

**Comment by weihuoya** [comment]
github.com/citra-emu/citra/pull/2865

**Comment by Deka710** [comment]
thanks!
