### ISSUE TITLE
subregion issue cause pokemon illegal

### ISSUE THREAD

**Issue by Deka710** [weihuoya/citra#683]
PR : https://github.com/citra-emu/citra/pull/5901

**Comment by Deka710** [comment]
the sub region on citra mmj is blank cause pokemon mark as illegal on pkhex.
citra mmj:
![IMG_20221013_135251](https://user-images.githubusercontent.com/97207704/195524015-89ac4d3c-7334-468a-86d4-dcf3a0b26f15.jpg)

citra pc:
![IMG_20221013_135348](https://user-images.githubusercontent.com/97207704/195524051-bc228129-db85-4bb5-818e-ddb435a6ce1e.jpg)

**Comment by Tappy-tech** [comment]
> the subregion on citra mmj is blank cause pokemon mark as illegal on pkhex. citra mmj: ![IMG_20221013_135251](https://user-images.githubusercontent.com/97207704/195524015-89ac4d3c-7334-468a-86d4-dcf3a0b26f15.jpg)
> 
> citra pc: ![IMG_20221013_135348](https://user-images.githubusercontent.com/97207704/195524051-bc228129-db85-4bb5-818e-ddb435a6ce1e.jpg)

Still, you can fix it, by marking needed region/sub-region/Geolocation

**Comment by Deka710** [comment]
> > the subregion on citra mmj is blank cause pokemon mark as illegal on pkhex. citra mmj: ![IMG_20221013_135251](https://user-images.githubusercontent.com/97207704/195524015-89ac4d3c-7334-468a-86d4-dcf3a0b26f15.jpg)
> > citra pc: ![IMG_20221013_135348](https://user-images.githubusercontent.com/97207704/195524051-bc228129-db85-4bb5-818e-ddb435a6ce1e.jpg)
> 
> Still, you can fix it, by marking needed region/sub-region/Geolocation

how?

**Comment by Tappy-tech** [comment]
> how?

With PkHex/PKSM.

**Comment by Deka710** [comment]
> > how?
> 
> With PkHex/PKSM.

oh wait how to do it with PKSM ?,my craptop is broken big sad

**Comment by Deka710** [comment]
![Screenshot_2022-10-13-16-05-50-040_org citra emu](https://user-images.githubusercontent.com/97207704/195553952-df360d15-8ce5-404d-94f2-89810dc2c1da.jpg)
i guess this one

**Comment by Deka710** [comment]
![Screenshot_2022-10-13-16-41-09-500_org citra emu](https://user-images.githubusercontent.com/97207704/195562535-3ea0c5f7-8c3c-4ad6-a15a-096fbd4e3e59.jpg)
citra canary android already fixed this problem,i've tried breed pokemon in citra canary android and the region id wasnt 00 or blank

**Comment by Tappy-tech** [comment]
Maybe it's still because the regions of Citra official and Citra MMJ (Set in normal citra settings, not 3DS) are different? Try changing in Citra MMJ the one, that Citra Official has, if they're not same.
