### ISSUE TITLE
Texture and performance in pokemon

### ISSUE THREAD

**Issue by AugustinKkkjkkj** [weihuoya/citra#707]
First of all, I'm not a native English speaker, so please forgive me for using machine translated English.

I'm currently playing Pokémon Alpha Sapphire on my Galaxy S20 FE and I noticed that the texture of water type pokemons are white, but I researched and tested the tutorials, I put Accurate Multiplication in Accutate and I couldn't solve it.
Later, I was fiddling with Citra's options and found that I needed to disable the Hardware Shader to fix the textures, but that took away from the game's performance, causing it to crash endlessly.
If someone has a way to play with the correct textures but without losing performance I would be very grateful, because the part where Kyogre leaves the sea and goes towards Sootopolis loses all the impact because the pokemon is with the texture all white.

**Comment by Tappy-tech** [comment]
Delete config-games.ini.

**Comment by AugustinKkkjkkj** [comment]
> Exclua config-games.ini.

It worked, thank you. I will finally be able to see my Kyogre.
