### ISSUE TITLE
Citra Android official today confirmed

### ISSUE THREAD

**Issue by vvanelslande** [weihuoya/citra#71]
![image](https://user-images.githubusercontent.com/62673824/82608284-fb732280-9b7f-11ea-8923-a84b89997fc6.png)

**Comment by AndresNorm** [comment]
😱

**Comment by Tiganjos** [comment]
What is citra official released ?

чет, 21. мај 2020. 23:34 Valentin Vanelslande <notifications@github.com> је
написао/ла:

**Comment by vvanelslande** [comment]
no

**Comment by Tiganjos** [comment]
They hype up people why breadfish64 sent you this message?
