### ISSUE TITLE
New update please 🙏

### ISSUE THREAD

**Issue by pokeholmes001** [weihuoya/citra#730]
New update Please 🙏

**Comment by Gelo021** [comment]
Weihouya maybe taking a rest for the upcoming vulkan

**Comment by iCorazone30** [comment]
still waiting for new update 😔

**Comment by iCorazone30** [comment]
yeah i know but vulkan still beta

**Comment by AndresNorm** [comment]
WeiHuoya Drop the Project (as always) but thanks to him
