### ISSUE TITLE
Error:12 problem on redmi note 5 pro

### ISSUE THREAD

**Issue by shabbirmahmud** [weihuoya/citra#75]
When I try to load any ROM the game screen opens and instantly show a pop-up meseeage like error:12.So I can't play any games on it.I tried Pokemon omega ruby,Pokemon x.Same For every game..Please help me😭😭

**Comment by RangerKevin2** [comment]
[my english may have errors] go to the settings of citra, click "emulated region" and select "auto". If it doesn't work, select the region of your ROM:
If your ROM is Japanese select japan in the settings. The region of your ROM is indicated on the photo
![Screenshot_20200523-204134191_1](https://user-images.githubusercontent.com/64848329/82738201-3cad3300-9d36-11ea-8dd5-4f3a53f41de5.jpg)

**Comment by shabbirmahmud** [comment]
> [my english may have errors] go to the settings of citra, click "emulated region" and select "auto". If it doesn't work, select the region of your ROM:
> If your ROM is Japanese select japan in the settings. The region of your ROM is indicated on the photo
> ![Screenshot_20200523-204134191_1](https://user-images.githubusercontent.com/64848329/82738201-3cad3300-9d36-11ea-8dd5-4f3a53f41de5.jpg)

I tried but it didn't work😔😔😔

**Comment by shabbirmahmud** [comment]
Problem solved😃😃😃
