### ISSUE TITLE
installing CIA(Update) doesn't work in latest version

### ISSUE THREAD

**Issue by Deka710** [weihuoya/citra#752]
it says installed but the update doesn't apply,
here the video:

https://user-images.githubusercontent.com/97207704/229035149-010a76ca-e55d-4165-adf6-954e1d4805bc.mp4

**Comment by weihuoya** [comment]
https://github.com/weihuoya/citra/releases/tag/20230331

**Comment by Deka710** [comment]
> https://github.com/weihuoya/citra/releases/tag/20230331

still deosnt work sadly😅

**Comment by weihuoya** [comment]
download again, apk get update

**Comment by Deka710** [comment]
> download again, apk get update

thank you!!😁 it works now
