### ISSUE TITLE
Fix Ironfall invasion 

### ISSUE THREAD

**Issue by ajay9634** [weihuoya/citra#759]
Please fix Ironfall invasion , screen is rotating automatically, game is unplayable in mmj.
This game is working perfectly in the official Citra.

**Comment by weihuoya** [comment]
https://github.com/weihuoya/citra/releases/tag/20230406

**Comment by ajay9634** [comment]
https://user-images.githubusercontent.com/78233144/230325961-214077c7-018a-4e57-89fc-5fc9e9cc819b.mp4
I am talking about this issue

**Comment by ajay9634** [comment]
Not fixed in the latest build
