### ISSUE TITLE
toggle to turn off texture filter

### ISSUE THREAD

**Issue by Deka710** [weihuoya/citra#768]
theres any way to turn off texture filter?, because in some case it fucked the outline in pokemon game
![Screenshot_2023-04-05-11-26-57-354_org citra emu](https://user-images.githubusercontent.com/97207704/229981176-22a791c7-6978-481f-a795-d506baa91ae7.jpg)
![Screenshot_2023-04-05-11-26-36-839_org citra emu](https://user-images.githubusercontent.com/97207704/229981188-989f62ab-b19f-4271-bc04-33779a9f48a1.jpg)
i didnt even using no outline cheat

**Comment by Tappy-tech** [comment]
Which settings did you use?

**Comment by Deka710** [comment]
> Which settings did you use?

auto

**Comment by Deka710** [comment]
never used any resolution hack, also linear filter still fucked the outlines
