### ISSUE TITLE
a question

### ISSUE THREAD

**Issue by Deka710** [weihuoya/citra#775]
can u explain what compatible mode do?
![Screenshot_2023-04-20-16-43-14-697_org citra emu](https://user-images.githubusercontent.com/97207704/233327641-c0cc042a-c193-4350-b3e1-da8d2fb8e42c.png)

**Comment by weihuoya** [comment]
fx some glitches on mali gpu and virtual console display

**Comment by Deka710** [comment]
i see,thanks
