### ISSUE TITLE
Vulkan backend

### ISSUE THREAD

**Issue by Deka710** [weihuoya/citra#788]
Vulkan backend just released in Citra Official, its possible to port it over to Citra MMJ?
![Screenshot_2023-05-16-09-46-34-721_com discord](https://github.com/weihuoya/citra/assets/97207704/3b9ff879-b51c-48b6-990f-7f32c6416de2)

**Comment by Hisham735** [comment]
Citra MMJ + Vulkan = ✈️✈️
