### ISSUE TITLE
MH4G display issue on latest version

### ISSUE THREAD

**Issue by Deka710** [weihuoya/citra#792]
the screen became darker when monster roaring and doing some certain moves, this is doesnt happen on previous version

**Comment by Deka710** [comment]
here the video:
https://github.com/weihuoya/citra/assets/97207704/086d9972-13fa-4317-a9c4-8a6f5807cfcf

**Comment by Gelo021** [comment]
I think its async shader

Mh4u works fine for me ill try 4g

**Comment by Gelo021** [comment]
Whats your setting?

**Comment by Deka710** [comment]
> Whats your setting?

default,as i said only happen on latest version
