### ISSUE TITLE
Error opening MHXX 

### ISSUE THREAD

**Issue by Govas1** [weihuoya/citra#849]
Error 11: Generic when you open MHXX v1.4
![Screenshot_20231006-234928](https://github.com/weihuoya/citra/assets/141814920/25af8eca-42fb-47b5-8a4f-5809f91ecba7)

**Comment by jsdteve** [comment]
I think that's one of them settings, how about resetting the app?
![Screenshot_20231012-124830](https://github.com/weihuoya/citra/assets/142978782/bb82149b-5e41-4182-bfae-6776a772f1c8)

**Comment by Govas1** [comment]
> I think that's one of them settings, how about resetting the app? ![Screenshot_20231012-124830](https://user-images.githubusercontent.com/142978782/274494065-bb82149b-5e41-4182-bfae-6776a772f1c8.jpg)

Apparently it is an error where the "cpu skip" is activated and it can be solved by deleting the citra-emu folder
