### ISSUE TITLE
With the new update the pokemon games slowed down 

### ISSUE THREAD

**Issue by shaodwmax007** [weihuoya/citra#99]
With the release of the new version if citra mmj, the earlier pokemon games that were running in 30-50 fps suddenly slowed down to 10-15 fps please a solution is needed 

The games that slowed down
Pokemon alpha sapphire
Pokemon x
Pokemon y 
Specs of the phone
Snapdragon 710
4gb ram 
64gb internal storage 

Please recommend a solution for this

**Comment by neganx276** [comment]
On which version game was running at 30 fps?

**Comment by shaodwmax007** [comment]
Its running on v 1.5

**Comment by shaodwmax007** [comment]
Sorry it was the version e5e858cf5

**Comment by neganx276** [comment]
Am am official citra  playing Pokemon x Sd675 8 gb tam 15 to 20 fps pfft let me try urs

**Comment by shaodwmax007** [comment]
Well I don't know how it happened but i did yours give more fps because of
the extra ram

**Comment by neganx276** [comment]
I don't its ram problem..and couldn't find ur version...btw finished the
game on 20 fps lol

**Comment by shaodwmax007** [comment]
Lol good for ya i finished it back when it ran on 50 fps

**Comment by neganx276** [comment]
Am jealous!!argh

**Comment by shaodwmax007** [comment]
😂😂 no worries bro

**Comment by albertserrano** [comment]
_translated from spanish_

Try to disable the cheats for pokemon, I have Sd660 4gb ram and I have 30 fps in alpha sapphire, although the other pkm are regular for me ... I am in the official Beta version ... I have not tried MMJ for a long time, they recommend me return?

**Comment by Lemoncak3** [comment]
In mine runs at around 25-28 fps without the 60 fps cheat though, can't wait till the save state is established so i can play anywhere.

**Comment by Eselter** [comment]
Last version of this app where pokemon working fine for me is Citra_MMJ_20200428.apk, all newer versions are much slower. On last official version all working fine.
